### ISSUE TITLE
[inline TODO] Remove validator compatibility layer (deprecated in 4.6)

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1016]
**Background**
This issue is part of a project (https://github.com/textpattern/textpattern/issues/1004) to migrate inline TODOs to GitHub issues. If this issue is still relevant, please assign milestone(s) and team member(s) accordingly.

On acceptance as a valid issue, the code should be annotated with a comment pointing back to this issue.

On completion of the issue, the code should be updated to remove the comment and the pointer to the issue.

**TODO and surrounding code**
https://github.com/textpattern/textpattern/blob/dev/textpattern/lib/txplib_validator.php#L27

```php
/**
 * Main Validator class.
 *
 * @since   4.5.0
 * @deprecated in 4.6.0
 * @package Validator
 */
class Validator extends \Textpattern\Validator\Validator
{
}
/**
 * Constraint.
 *
 * Defines a single validation rule.
 *
 * @since   4.5.0
 * @deprecated in 4.6.0
 * @package Validator
 */
class Constraint extends \Textpattern\Validator\Constraint
{
}
```

**Comment by philwareham** [comment]
IMO If this was deprecated in 4.6 then it should be removed in 4.7 - since we have never had a major (i.e. 5.0) release our point releases (i.e. 4.7) serves as our major releases.

Seriously, Textpattern should have had major releases (like yeah, 4.7 *really* should be lumped in the same release cycle as 4.0.1?!) but that a decision from way before my time.

**Comment by petecooper** [comment]
Closing for now - see https://github.com/textpattern/textpattern/issues/1004#issuecomment-353670101
