### ISSUE TITLE
Something is broken with the en-gb textpack

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1033]
(4.7.0-dev (bb450694e6d8387736ea5571c13f38d2))

Install the English (British) text pack.
* In debug mode, PHP spits out a whole bunch of warnings (see below). 
* Every time I reload the language panel PHP spits out those warnings.
* In the User language `select` the language is listed as EN-GB (instead of the expected name).
* In the list of installed languages, there is an entry for language, but it has no name:

![screen shot 2017-11-27 at 8 34 58 am](https://user-images.githubusercontent.com/8944809/33245649-01c97302-d34e-11e7-8cec-02453b095952.png)

PHP bable:

```
<pre dir="auto">Notice "Undefined index: name"
in /Users/user/Sites/_txp472/textpattern/vendors/Textpattern/L10n/Lang.php at line 549.</pre>
<pre class="backtrace" dir="ltr"><code>textpattern/vendors/Textpattern/L10n/Lang.php:549 adminErrorHandler()
textpattern/include/txp_lang.php:72 Textpattern\L10n\Lang-&gt;languageSelect()
textpattern/include/txp_lang.php:273 list_languages()
textpattern/include/txp_lang.php:48 save_language_ui()
textpattern/index.php:225 include()</code></pre><pre dir="auto">Notice "Undefined index: name"
in /Users/user/Sites/_txp472/textpattern/vendors/Textpattern/L10n/Lang.php at line 549.</pre>
<pre class="backtrace" dir="ltr"><code>textpattern/vendors/Textpattern/L10n/Lang.php:549 adminErrorHandler()
textpattern/include/txp_lang.php:81 Textpattern\L10n\Lang-&gt;languageSelect()
textpattern/include/txp_lang.php:273 list_languages()
textpattern/include/txp_lang.php:48 save_language_ui()
textpattern/index.php:225 include()</code></pre><pre dir="auto">Notice "Undefined index: file_lastmod"
in /Users/user/Sites/_txp472/textpattern/include/txp_lang.php at line 103.</pre>
<pre class="backtrace" dir="ltr"><code>textpattern/include/txp_lang.php:103 adminErrorHandler()
textpattern/include/txp_lang.php:273 list_languages()
textpattern/include/txp_lang.php:48 save_language_ui()
textpattern/index.php:225 include()</code></pre><pre dir="auto">Notice "Undefined index: name"
in /Users/user/Sites/_txp472/textpattern/include/txp_lang.php at line 155.</pre>
<pre class="backtrace" dir="ltr"><code>textpattern/include/txp_lang.php:155 adminErrorHandler()
textpattern/include/txp_lang.php:273 list_languages()
textpattern/include/txp_lang.php:48 save_language_ui()
textpattern/index.php:225 include()</code></pre>
```

**Comment by makss** [comment]
[Done](https://github.com/textpattern/textpattern/commit/b262e25ce8c54965308fa654666650ca83990def), please test.

**Comment by phiw13** [comment]
Yes! Thank you. Tested across 2 installs.

Closing.

**Comment by makss** [comment]
There is another bug. This happens when select `Site language` to `en`:
`No locale available for language English. Using default locale instead.`

Probably [need to specify en locale](https://github.com/textpattern/textpattern/blob/b262e25ce8c54965308fa654666650ca83990def/textpattern/vendors/Textpattern/L10n/Locale.php#L54).

**Comment by Bloke** [comment]
Yeah, Phil and I considered this but didn't reach a satisfactory conclusion. `en` (as a language) equates to "Oxford English" which is a sort of hybrid between `en-gb` and `en-us`. There's no official locale for it, so which would we pick? Date formats differ between the two, for example.

If we want to just use the `en-gb` locale for `en` then there's an argument for not bothering with the Oxford version of the language at all. Does it inconvenience people in non-English countries if `en-gb` becomes default again? Is the `en-gb` locale one of the ones that is available on everybody's system?

**Comment by makss** [comment]
I'm not at all oriented in the differences between `en- *`, but need to specify something for the `en` locale. Otherwise, it will look weird if we display any warnings with each choice of the main language of our system.

**Comment by philwareham** [comment]
The whole intention of the `en` language was that it was supposed to have no specific default locale. So in that sense the message is correct. If we are adamant that every language has a default locale then we will have to go back to `en-GB` and delete the locale-less `en` Textpack. That kind of shuts out Canada, Australia, etc from using the `<txp:lang />` tag to some extent. Up to you guys.

**Comment by Bloke** [comment]
I like the idea of a region-agnostic language. And the fact it falls back on your default locale is kind of good because you get a good approximation of English with region-specific dates, etc.

If we keep it - and I think we should - the question really becomes: "do we really need to issue a warning if the exact locale can't be found?"

If you try and switch to a language that your system doesn't understand and has no locale info, then one could argue that it's important as you might get weird output. But do we make an exception for `en` since we _know_ there will never be a locale for it? i.e. throw a warning for all missing locales _except_ `en`?

**Comment by phiw13** [comment]
Does Textpattern actually rely much on the @locale@? Date/Time formatting, sorting maybe? Anything else? Most TXP generated strings the visitor on the front-end will see comes from the `lang` files, I think.

On Dreamhost, with `en` set for the site language, I get the warning (and only because I toggled the language), and Diagnostics tell me the `locale` is `C`.

I would be inclined to *not* display a message on the Languages panel, but instead an informative note on the Diagnostics panel, with a help item.

**Comment by bloatware** [comment]
Mainly [dates](http://www.iut-fbleau.fr/projet/etc/index.php?id=24), yes, but the issue is important enough to deserve a warning. Wasn't there some `closest()` method before?

**Comment by Bloke** [comment]
> Wasn't there some closest() method before?

Yes, makss removed the need for it when he introduced [recode_locale()](https://github.com/textpattern/textpattern/blob/dev/textpattern/vendors/Textpattern/L10n/Locale.php#L102) so it got axed.

I quite like the idea of showing the message in Diagnostics instead of warning when switching language. But as @bloatware says, there are times when you need to know immediately because it affects date output.

I'm still tempted to throw the warning as we do now, but exclude the check if the language is `en` since it's a made-up ~~drug~~ locale. Any downsides to this?

**Comment by bloatware** [comment]
Sorry, I have not followed L10n branch closely, but wouldn't mapping `en` to `en-gb` or `en-us` or whatever found be more natural than the default locale? On my local setup, English (British) installs just fine, but English issues a warning.

**Comment by Bloke** [comment]
Depends what the default locale is. Let's say you're Canadian English and your default locale is therefore `en_CA`. If we hard-code the fallback locale for `en` to `en_GB`or `en_US`, it misses the opportunity for people to use a "best fit" language and have their own locale used to fill in the locale-specific gaps.

I admit that a lot of the time the locale defaults to "C" which is generic, but for other use cases it does have merit to leave a 'floating, locale-less language' in the system. The question is whether we warn people who use this floating language - which we know will never match a real locale - or not when they use it.

**Comment by bloatware** [comment]
We can check if the default locale "matches" `en` (e.g. `en_CA`) and use it if so; otherwise switch to some other available English locale or, finally, to the default one if nothing is found.

**Comment by Bloke** [comment]
That would work. Wanna give it a spin?
