### ISSUE TITLE
Removing legacy / unused Textpack strings from upgrades

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1039]
@Bloke [writes](https://github.com/textpattern/textpacks/issues/109#issue-99608875):

> […] Consider how to clean up old strings in people's installations. This will help with site speed, as downloading strings on each page load is expensive.

It looks like https://github.com/textpattern/textpacks/issues/109 can be safely closed, this is one item in the todo list that may need attention.

**Comment by philwareham** [comment]
So this is done and this issue can be closed, yes? Sorry I'm confused as to whether further action is needed here? 🙃

**Comment by Bloke** [comment]
Not necessarily done, but I can't think of a better way to achieve this than the following:

1. Just before updating a language file, make a note of the current _core_ string keys in that language.
2. During installation, keep track of all core lang string keys that are installed.
3. When done, remove any strings from the database based on the diff of the keys used in step 1 and step 2.

Now we have fallback strings in place, this _might_ just be a robust enough system to attempt this clean up operation. We'd have to leave plugin strings alone as there's no guarantee that a plugin contains a Textpack.

I'm always wary about deleting stuff on upgrade after the 4.6.0 file system debacle, but I think we can manage this cleanly. Any better suggestions?

P.S. There is one definite way for someone to clean up their strings without the above: remove the language and reinstall it!

P.P.S On the topic of cleanup, should we consider silently deleting `lang/en-gb.txt` since it's been replaced with a `.ini. file now?

**Comment by petecooper** [comment]
> I'm always wary about deleting stuff on upgrade after the 4.6.0 file system debacle, but I think we can manage this cleanly. Any better suggestions?

Defer it to a point release? I mean, in real terms, there's a _lot_ of stuff changing for 4.7.0 and there's plenty of scope to test it before a 4.7.1 release hit the shelves. It is a patch, after all.

**Comment by Bloke** [comment]
That might be a good option.

**Comment by philwareham** [comment]
I've created a v4.7.1 milestone and assigned that to this issue.

It may be wise to remove the `en-gb.txt` itself as part of the v4.7.0 release though.

**Comment by Bloke** [comment]
Yeah, I'll do that.

**Comment by petecooper** [comment]
Bumping this since it's languished a bit, perhaps we can close it. Adding RFC tag to see if there's anything to do.

>P.S. There is one definite way for someone to clean up their strings without the above: remove the language and reinstall it!

Considerations:

* repurpose the Update button to remove then reinstall a language pack, or…
* add a Reset button to do the same, or…
* close the issue, not a priority.

Repurposing Update to splat and repave wouldn't keep any modifications. Adding a Reset option would need a confirmation dialog so the driver knows their strings will be reset, including any they added. Do other tweaks to language handling mitigate the performance overhead of unused / stale strings?

**Comment by bloatware** [comment]
It has auto-closed itself, sorry. Please test whether 'Reset' button behaves well. Its functionality could be merged into update, but then we need to warn user that all extra strings will be removed.
