### ISSUE TITLE
[docs] Update multi-site readme to reflect changes or detach to docs site?

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1049]
Background: https://forum.textpattern.io/viewtopic.php?pid=308038#p308038

The current multi-site readme (`sites/README.txt`) needs overhauling with the proposed `multi-site-fix` branch. I wonder…would it be more appropriate to refresh the readme or detach it to become part of the docs site, or a bit of both?

I've been meaning to learn multi-site for a while, so I can provisionally take dibs on this if needed.

**Comment by jools-r** [comment]
I don't mind doing that – or doing it together with you – but currently it's not finalised. If makss proposed modifications go through (some or all of them), then it's different to how I have it now.

Not sure which is best re readme or docs. The current readme.txt in there is a bit of an anomalie compared with the rest of txp.
Then again, if we detach the `/sites` folder from the main repo, then the readme might make sense.

**Comment by petecooper** [comment]
@jools-r - I'm glad you mentioned the anomaly of the multi-site readme, I was thinking the same thing and it has been left largely untouched since Sam put it together. You're clearly in a far better position than I am to explain how it all works, and I'm very happy to let you do it; how about using me as a (newbie) test subject and I can go through the process, asking questions as I go so we can formulate a FAQ-style section of the document. Would that be helping or hindering?

**Comment by jools-r** [comment]
Sounds perfect. Let's do that when the dust has settled.

**Comment by petecooper** [comment]
Paging @jools-r – I'm aiming to have a shot at testing the updated multisite tomorrow (with fresh eyes) with a view to reporting back and ideally checking off the task in the beta onramp list [here](https://github.com/textpattern/textpattern/issues/1098). Is there anything pertinent I need to know before I start? Thanks!

**Comment by jools-r** [comment]
Erm, yes. A fork compare with my PR and the latest dev as of today reports 449 commits and 273 file changes since I last merged the dev into my personal multi-site-fix branch on 18 Dec! I have some merging to do first…

**Comment by petecooper** [comment]
You the best. Thank you very much!

**Comment by jools-r** [comment]
Ok, my own [PR-branch](https://github.com/textpattern/textpattern/pull/1065) is now up-to-date with the current dev and from initial testing seems to work with both local themes folders and a symlink to a central themes folder. It's not been merged yet, so you'll need to bring in [my multi-site-fix branch](https://github.com/textpattern/textpattern/tree/multi-site-fix) to test it.

Basic options:

1. Leave the `/sites` directory where it is, rename (or duplicate) the `site1` folder and create two subdomains pointing to your `sites/mysite/public` (e.g. www.mysite.com or dev.mysite.com) and `sites/mysite/admin` folders (e.g. admin.mysite.com – admin is the suggested subdomain but you could just as well use edit, login, backend, etc. if you prefer). The symlinks are preset for this configuration and you should be taken straight to the setup routine with a few extra inputs for the multisite details. Everything else should be familiar. To create a new site, duplicate the /site1 folder with its subfolders and rename it accordingly.

1. Shift or copy your `/sites` directory to another location, e.g. parallel to your textpattern folder and follow the above instructions pointing to the respective site's public and admin folders in this directory tree. The pre-install routine should identify the new location and ask you to input the textpattern root path. Once you input that, it (re-)creates the symlinks for you and passes you on to the setup routine as above. It should trap incorrect path input, and if it fails to create symlinks, it offers the relevant platform’s command line commands to cut and paste. This variant allows you to keep your site repos separate from your textpattern directory.

Things to check / play with:
- No more errors or false reports. No more "ignore what it says" bits in the instructions.
- Diagnostics should show correct information including extra multi-site infos. The hide private infos checkbox keeps the two details and tries to redact just the common stub (to help in debugging).
- Test in windows. I don't have a windows machine at my disposal. Maybe also comment out the symlink unlink/creation lines in setup/index.php and delete the `vendors` symlink to see whether the cut-and-paste command line commands actually work properly.
- The cookie domain should make it possible to use maintenance mode plugins and reference the maintenance mode status from frontend and backend.
- If you place your /sites folder outside (e.g. parallel to) your textpattern folder, you can keep several textpattern versions in parallel. To upgrade, simply reconnect the symlinks to the respective version's textpattern folder.

Things to be aware of:
- The pre-install routine is rather bare-bones, visually. This is because it happens before any of textpattern is loaded (only config.php if it is found). We could add a modicum of styling to make it more like the rest of the install routine, but there's no full page markup, just what's necessary to display the messages and ask for an input. Likewise, there's no language handling at this point as none of the language-handling code is present. Is that tolerable?
- The first time you call up the public site, it has the traditional call /setup/ instruction but links to admin.mysite.com/setup/ with a note to use one's own chosen admin subdomain. There's no way of knowing at this point what the user has chosen, so this is just a best-guess suggestion.
- Plugins will need to change `hu."/textpattern"` into `ahu` in order to properly reference the multisite admin area.
- The welcome article points to the wrong admin-side links. Ideally, the correct links should be dropped in during setup. Could this happen much like the language strings?
- There are a few minor language strings for the diagnostics area and some of the setup language strings need updating to including `{configpath}` placeholders etc. so that the setup messages are correct. I've tried to do that where obvious in the PR, but these need backporting to CrowdIn and extending to other languages that word their messages differently.

If you want to go ahead and write instructions, I suggest relegating Sam's frightening-looking virtualhost instructions to some extra specific instructions for self-managed servers. Many / most shared server hosts have a simple way of creating subdomains and pointing them to a directory in their control panel. For many users it's way easier than Sam made it look back then.

**Comment by petecooper** [comment]
I'll defer this until we've figured out why theme/skin importing isn't working as intended and the [associated issue](https://github.com/textpattern/textpattern/issues/1101) is closed.

**Comment by jools-r** [comment]
@petecooper Are you already doing a write-up of the installation procedure, or should I have a first stab at it and you correct it?

**Comment by petecooper** [comment]
@jools-r I'm currently bolting together the parts for the demo site to enable multi-site support, and then I'm going to take a look. If you can have a first pass at it (with your chosen/preferred install method), then I will gladly go over it as a guinea pig and feed back.

**Comment by jools-r** [comment]
[The story so far …](https://gist.github.com/jools-r/dcfd9b45a636c051ec8a0bb70b89ff7b)

**Comment by petecooper** [comment]
Fantastic, @jools-r! I'm hoping to have some time tomorrow evening to get stuck into multisite, all being well.

**Comment by jools-r** [comment]
Just an info: I've done the docs as a proper [PR against the docs repo](https://github.com/textpattern/textpattern.github.io/pull/92). Please refer to that from now on.

@petecooper and others: I added a question over on the PR about any good existing instructions for file transfer via SSH and manual virtualhost configuration. Any ideas there?

**Comment by petecooper** [comment]
>I added a question over on the PR about any good existing instructions for file transfer via SSH and manual virtualhost configuration. Any ideas there?

I was thinking along the same lines. There comes a point where I think we're over-reaching with support – is it safe to assume that folks (especially power users running multi-site setups) should know how to upload and edit virtual host configs?

Forgive me if I'm missing something obvious that I haven't yet found – does your multi-site remix _need_ anything extra in a virtual host config?

**Comment by jools-r** [comment]
You only need to set up an additional subdomain for the admin-side. All 'regular' users will do that via their host's control panel. Only those users running their own servers need to fiddle with virtualhost containers manually as sam originally described. Presumably, those are by definition power users.

With SSH I'm torn. As far as I've been able to find out (correct me if I'm wrong), symlinks can't be transferred via FTP or SFTP, only by SSH or by transferring as a tar.gz and unpacking that on the server (which presumably presupposes command line access, and therefore also shell access). As such, "just enough" instructions on how to do the file transfer via SSH might be sensible here. Most host's instructions on SSH go into too much depth with generating access keys etc. I was thinking along the lines of the bare necessity with a recursive copy or perhaps rsync.

And, even if a user has no SSH access, the pre-installer still tries to create the symlinks via PHP...

**Comment by petecooper** [comment]
…and Transmit 5 doesn't play nicely with symlinks at all now, much to my dismay. Hmm, yes – I see what you mean now. Let me think on it.

**Comment by jools-r** [comment]
I think you're right. That should would work too.

One reason why I think multi-site has been used so little is that Sam's instructions looked a little daunting to the average user with little command-line knowledge, along with all those ignore what it says statements. His instructions were actually okay and those "ignore what it says" anomalies are now no longer. All the same, I think my instructions are already a bit long and I've tried to separate out the extra frills and problems. I suppose I could spread them across more pages to make them seem less … long.

I'd be tempted to leave out any mention of SSH or command-line unzipping or git cloning were it not for the fact that I can't see any good (GUI) way of getting the symlinks onto the server. Originally I thought SFTP (it's FTP over SSH, right?) would do it, but that seems not to be the case. Still, at least the lack of SSH or command line access is no longer the absolute barrier it once was.

My thinking was the act of transferring the files using SSH is closest notionally to that of FTPing. The step is essentially the same but using another method/protocol. The other two ways, while also viable, are alternative paths to the same and I didn't want to elaborate on all possible avenues. I think difficulty-wise, they're all about the same.

**Comment by petecooper** [comment]
Assuming ssh access is available, I would think it's fair to offer:

* a method of downloading the .tar.gz which does all the symlink jazz already
* a walkthrough of uploading files and manually creating the symlinks from the terminal

Also, bluntly, the docs being offloaded to the docs site means they are infinitely tweakable based on feedback and support requests, so as long as there's _some_ way of achieving your overhauled setup, that makes it a lot less time- and deadline-sensitive.

As you say, the multi-site option isn't exactly causing problems on the support forum, perhaps because it's not something people attempt easily - and when people do start using it, we can fine-tune the words appropriately.

**Comment by philwareham** [comment]
Also, by default we offer the single-install .zip version as the download (where IMO we shouldn't have any multi-site stuff since the symlinks aren't there to actually achieve it) which limits users by the fact they just aren't aware of multi-site functionality.

We should probably give some prominence to the multi-site .tar.gz on the main site and via the docs so people discover it better.

**Comment by petecooper** [comment]
I'm derailing a bit again – are there legacy reasons why the .zip doesn't include symlink stuff? On the face of it, it's possible: `zip --symlinks -r foo.zip foo/`

**Comment by Bloke** [comment]
Legacy, I think so, yeah. Traditionally the .zip has been for Windoze users and the .tar.gz for *nix / those that know what they're doing. No idea what happens in 'doze if you extract a package that has symlinks in it. It'll probably explode / complain / turn into a baguette.

**Comment by petecooper** [comment]
Tell you what, I'll find out. To be continued.

**Comment by philwareham** [comment]
IIRC the zip simply refuses to include the symlinks (or at least symlinks that work). I'd like to see a confirmation of that though!

**Comment by jools-r** [comment]
This is not a definitive answer, but as far as I recall, I had no problem with symlinks in a zip downloaded from the github repo the other day (on a mac, tho'). Also, the pre-installer will now (re)create the symlinks via PHP if the host system permits it, so even if they don't come through with the zip or fail to transfer via FTP, all is not lost.

**Comment by Bloke** [comment]
As long as Windoze doesn't choke on symlinks, I'm fine with a single download bundle. Less to maintain and build at release time. Then we just need to holler a bit more about the multi-site features, as Phil says.

**Comment by philwareham** [comment]
This sounds good - a single .zip file instead of the additional .tar.gz would be desirable. So if we can get a definitive answer on whether the zip and/or install fix with symlinks works on Unix/MacOS/Windows then we are good to go to a single zip.

**Comment by petecooper** [comment]
I've got another few hours of work to get done quick style and I'll investigate.

**Comment by Bloke** [comment]
I know it's Minecraft related and from 2013 so things may have moved on, but this guy's [explanation of the pitfalls of zip and symlinks](http://www.minecraftforum.net/forums/off-topic/computer-science-and-technology/hardware-software-support/498688-help-with-symlinks-in-zips#c6) seems fairly logical.

I suspect the only reasons our symlinks might "work" when bundled is because they'd point somewhere local already within the archive so the zip tool has an endpoint when unbundled.  Whether that's encoded in the archive using an absolute or relative path seems to be down to either the OS in which the archive was created or the compression tool (or both). Whether it's read back and applied at unzip time is down to the OS in which the archive is extracted or the decompression tool used (or both).

A .tar.gz will bundle up the symlinks as-is, hence they're safer for transport and recovery. And they're officially supported in the spec,. But .tar.gz isn't natively supported on Windows (at least not in Win7) so you need to rely on people having something like 7-zip installed.

My guess, therefore, is that is why we have the dual format after all.

The good news is that now we have Jools' pre-installer and shiny adaptation with a much more integrated installation process and core support, it might not actually matter which you download and unpack (as long as you have a Linux-based host) because the symlinks will be created if possible anyway.

**Comment by petecooper** [comment]
Thought: if symlinks aren't 100% reliable, is there any magic we can do with `.htaccess` in their place? Guessing not, but you've all had significantly more sleep than me and can think more coherently…

**Comment by jools-r** [comment]
> The good news is that now we have Jools' pre-installer and shiny adaptation with a much more integrated installation process and core support, it might not actually matter which you download and unpack (as long as you have a Linux-based host) because the symlinks will be created if possible anyway.

With the proviso that this needs testing under Windows. The [PHP docs for symlink](http://php.net/manual/en/function.symlink.php) says “This function is now available on Windows platforms (Vista, Server 2008 or greater).” as of PHP 5.3.

The other proviso is that it is not what you would call "shiny" ;-) We could add a CSS file to make it look more pretty but it adds an extra file in the `/sites/sitename/admin/setup/` folder. We can't use the main Textpattern CSS files because the installer doesn't know where that is until the symlinks are created.

**Comment by Bloke** [comment]
I don't mind an extra file in setup - it gets deleted anyway. Shine away if you like.

**Comment by Bloke** [comment]
Should be able to close this now, right?

**Comment by petecooper** [comment]
We got a bit off-track with .zip stuff, but it's +1 from me to close.
