### ISSUE TITLE
[ui/ux] Custom fields don't have any pophelp info

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1083]
### Expected behaviour

Custom fields should have some kind of pophelp.

### Actual behaviour

Custom fields don't appear to have any pophelp.

### Background

I'm going through through pophelp and documentation, and there doesn't appear to be any pophelp links for them, either in the Admin or Write panel.

I don't recall ever seeing any pophelp, and there's value in explaining what they do, both in a concise pophelp and further links to the docs site.

![re](https://user-images.githubusercontent.com/226578/34438595-d627091a-ec9f-11e7-8343-c54dc885ac4c.png)

**Comment by Bloke** [comment]
I think we used to have a generic entry in the pophelp file for custom fields, but maybe it's fallen by the wayside somehow.

**Comment by petecooper** [comment]
Migrated to https://github.com/textpattern/pophelp/issues/40 -- closing.

**Comment by Bloke** [comment]
Incidentally, #1081 may explain why custom fields don't have a pophelp topic any more. From memory, I think pophelp is only rendered automatically if we use `inputLabel()` which is probably not used for headings.

That said, we do render a pophelp link on the heading of the Forms panel so it's not without precedent to do this, we'd just have to figure out how to do a 'special' pophelp entry for the custom fields group topic in prefs. Since the entire panel is generated in a loop by iterating over the prefs, we have no way of handling this (bar writing an exception in the code). Or switch to using `inputLabel()` for headings, which might be possible.

**Comment by petecooper** [comment]
I was wondering. Forms does stand out as the only panel-level pophelp. It's not a huge deal in the grand scheme. I should perhaps just close or defer the issue for further discussion.

I have a proposal to investigate custom fields for all content for 4.9, effectively designating these custom fields as they stand to _article_ custom fields, and have another set for Files, another for Sections, another for Pages, etc. Probably a whole big can of wormy things best explained over a beer.

**Comment by Bloke** [comment]
When we move to unlimited custom fields for all content (4.8ish??) the entire prefs group for custom fields will disappear. Custom fields will have their own dedicated panel for defining their content, defaults, data types, which content types they represent, and so forth.

So for the sake of saving ourselves a pophelp topic and some branching code to handle it, we could probably just squirrel this issue away and pretend we didn't notice :-)

**Comment by petecooper** [comment]
Leave that with me. I'll make it disappear.
