### ISSUE TITLE
admin_site_url or site_url admin="1" tag or similar?

### ISSUE THREAD

**Issue by jools-r** [textpattern/textpattern#1120]
In the current multi-site installation, there's one fly still in the ointment: the admin-side links on the welcome page link are hard-linked to `/textpattern/index.php?…` which means they don't work for first-time visitors on multi-site installations. I'd asked about possibly dropping them into a placeholder during installation, but something like the following would be simpler and has additional uses:

* a new tag `<txp:admin_site_url />`, or …
* an additional `admin="1"` attribute to `<txp:site_url />`, e.g. `<txp:site_url admin="1" />` (or `<txp:site_url admin />` as Oleg has been showing us).

With the multi-site installation, we have a new constant `ahu` which is the link to the admin url. In a standard (non-multi-site) installation, this is `hu."textpattern"` as it was previously. On a multi-site installation, it's the respective admin subdomain.

That would resolve the welcome article problem – we just need to prefix the links with this tag. It also means we can create edit-this-article links or maintenance mode links from the front-end to the admin side.

Should be a quick and easy fix, no?

**Comment by Bloke** [comment]
Sounds great. If this is the only thing standing in the way, then `<txp:site_url type="admin" />` works for me (unless you can come up with a better name for it). I have no problem exposing this to the public site if an admin deems it necessary. Security through obscurity being no security at all.

**Comment by jools-r** [comment]
It's up to the admin what they include. The typical situation would be a link back to the article that shows to logged-in users only, either to edit that article or a warning bar to remember to switch off maintenance mode. In such cases, it wouldn't be exposed to public visitors.

The use as seen in the welcome article is not typical.

`type="admin"` as an attribute works for me too :-)

**Comment by Bloke** [comment]
Yes, and this URL may actually benefit people who want to offer public-side login fatures like cbe_frontauth. Should be a doddle to construct links to the admin side login page or "Edit this article if you're logged in" with just tags.

To support this, one thing I've been toying with is a simple public tag `<txp:if_logged_in />` with optional list of `name`s. That'd save a heap of custom plugin code, as you could just wrap content with it directly in your templates. Should be about five lines of code as we already have an `is_logged_in()` analog function.

Haven't thought it through fully yet, so I might have missed something, but it seems like a good idea on the surface.

**Comment by jools-r** [comment]
> To support this, one thing I've been toying with is a simple public tag <txp:if_logged_in /> with optional list of names.

“Great minds …” ;-)

That would be the icing on the cake, I just didn't want to burden you with more work…

Possibly roles in addition to names would be useful...

**Comment by Bloke** [comment]
> Possibly roles in addition to names would be useful...

That might add a line of code :-)

**Comment by Bloke** [comment]
A note on semantics:

```
<txp:if_logged type="in">
<txp:if_logged type="out">
```

vs

```
<txp:if_logged_in>
<txp:if_logged_out>
```

vs

```
<txp:if_logged_in>
(with 'not' attribute support if you want to test "not logged in")
```

All would support `<txp:else>` plus `user` and `role` attributes. I'm favouring option 3.

**Comment by jools-r** [comment]
Yes, I agree: `<txp:if_logged_in>` with support for `<txp:else />` should cover it.

**Comment by jools-r** [comment]
Nice easy solution. Were you planning on wrapping that back into `txp:site_url` or should we go with `<txp:page_url type="admin_root" />`?

To modify the links in [articles.welcome.xml](https://github.com/textpattern/textpattern/blob/dev/textpattern/setup/articles/articles.welcome.xml), is there any reason why we can't/shouldn't do this:

```
The "article list":<txp:page_url type="admin_root" />index.php?event=list is the place to start.
```

or is there some reason why that wouldn't work? I see that elsewhere in [articles.welcome.xml](https://github.com/textpattern/textpattern/blob/dev/textpattern/setup/articles/articles.welcome.xml) there's already a placeholder called `siteurl`, which made me wonder because `<txp:site_url />` should work in those places... or not?

**Comment by Bloke** [comment]
Yes, my network went down last night after I'd done the first part. Will do the rest today. Still not sure if `admin="1"` or `type="admin"` is best though.

A dedicated `admin` attribute is nicer, and is more succinct to use, as it can be valueless. But it's another attribute.

Using `type` is more flexible for future in case we want to introduce more output from the tag, instead of just the binary choices. If we go with `admin="1"` then we have to introduce another attribute in future if we want to do this. But if that's not a concern and we can't envision using the site_url tag for any other type of site URL output, I might lean on a dedicated attribute. Whaddya reckon?

**Comment by Bloke** [comment]
Oh, and as for the `siteurl` placeholder, yes. @makss coded it so that it replaces that with the tag output. I'm not sure why it's not replaced with a tag and is done in the code. Maybe the URL isn't available at that point because it's not populated in the database yet, so it needs a placeholder for replacement when it does.

If we can't use a tag, worst case is that we can alter the placeholder to return `ahu` and get rid of the enforced `textpattern` in the XML file.

**Comment by jools-r** [comment]
> Still not sure if admin="1" or type="admin" is best though.
and
> Using type is more flexible for future

I think `<txp:site_url type="admin" />` is fine and easy enough to understand.

**Comment by jools-r** [comment]
> Oh, and as for the siteurl placeholder, yes. @makss coded it so that it replaces that with the tag output. I'm not sure why it's not using a tag directly and is done in the code. Maybe the URL isn't available at that point because it's not populated in the database yet, so it needs a placeholder for replacement when it does.

I wondered too, but theoretically it doesn't need to be known it at this point. Could not `<txp:site_url />` and `<txp:site_url type="admin" />` simply appear in the article body itself to be processed on rendering? I wondered if it was a textile notation clash problem, or perhaps it was just because it's not as clean to have URLs with tags in them in the body for a first-time visitor? What do you think @philwareham?

And if it does need replacing, then `siteurl/textpattern/` could be replaced with `ahu` ...

**Comment by Bloke** [comment]
OK. Two commits to play with as promised:

5e6fc44d adds the `type` attribute to `<txp:site_url />`. Takes one optional parameter `admin` to return `ahu`, otherwise `hu` as normal.

9868bb9a adds the `<txp:if_logged_in>` container tag. Optional attributes:

* `name`: the name of a person to check. Defaults to 'current user' (i.e. if anyone is logged in).
* `group`: one or more privilege levels to check as well. You can specify the name of the level (e.g. `publisher`, `copy_editor`, ...) or its number, or a mixture. Without the `user` attribute, anyone with the privs given in the list is allowed to see the contained content.

Supports `<txp:else>` and should (in theory) even work with plugins such as smd_user_manager that extend the groups, but I haven't tested that.

Things to consider:

1. Ability to specify a list of names. Probably requires tweaking `is_logged_in()` to accept a string or array of names using SQL `IN`.
2. Add some cacheing to `is_logged_in()` function. I tried and failed last night but I was tired and won't have time to do it today. If anyone (e.g. @bloatware?) fancies having a stab at it, or to optimize the new tag, please do so.

Test and enjoy!

**Comment by jools-r** [comment]
Using `<txp:site_url type="admin" />` in [articles.welcome.xml](https://github.com/textpattern/textpattern/blob/dev/textpattern/setup/articles/articles.welcome.xml) doesn't get textilised. The tag works perfectly (*yeah*) but:

```
The "article list":<txp:site_url type="admin" />index.php?event=list is the place to start.
```
gets output as:
```
The “article list”:http://admin.multisite.com/index.php?event=list is the place to start.
```

Have I just got my textile notation wrong, or do we need to go with the other approach?

**Comment by petecooper** [comment]
+1 for tags working as expected/described. Thanks, @Bloke!

**Comment by jools-r** [comment]
I went with the other approach and expanded makss' `replaceSiteurl` routine in the XML importer to include replacing the string `adminurl`. See [this PR](https://github.com/textpattern/textpattern/pull/1129).
