### ISSUE TITLE
Diagnostics panel - translated strings in report

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1139]
### Expected behaviour

We have recently made the report textarea use English-only text instead of localised text, so International users can more easily understand the reports. This should be for all of the report.

### Actual behaviour

Certain sections of the report still use localised strings, potential making it harder to understand and fix any errors users experience - see grab where I'm using Chinese to make it easy to spot. This is because strings from the Preflight are simply duplicated into the report. Think we'll need to provide a test to see if in textarea or not and provide English versions of those text strings in the mode.ini file. Might be other cases where this happens such as the GD Graphic Library line - again see grab.

![grab](https://user-images.githubusercontent.com/413665/35561645-e6d5213a-05a8-11e8-9232-363383bd9a9d.png)

**Comment by Bloke** [comment]
I've done this in the themes branch, since that has all the updated strings and will be merged today anyway.

This lightens the Textpack load considerably in the `[diag]` group. I've deleted the strings from `en.ini` only in the commit so the other languages will need syncing at some point once we've checked that we've caught them all.

**Comment by Bloke** [comment]
Okay, this is a bit of a thorny issue. Basically, everything that appears in the pre-flight check is duplicated verbatim in the textarea. I've found a few stray `gTxt()` calls, such as in the gd library checks, that I've cleaned up into English only. But the only way to render the pre-flight check block in English in the textarea is to:

a) Do what I did before and make the entire pre-flight check in English, above the textarea and inside it.
b) Do the pre-flight tests twice, once above the textarea, once inside it. Resource intensive and wasteful, so not pursuing that.
c) Duplicate all pre-flight strings in `mode.ini` and then, for each test, stash two arrays: one with localised strings, and one with English strings. Output the localised array above the textarea, and output the English array inside.

Option 'c' involves a heap of duplicated strings and a duplicated line of code for every test. Is it worth the hassle?

**Comment by philwareham** [comment]
Ok. All in English then! Not the best solution but I guess it’s acceptable.

**Comment by phiw13** [comment]
Sorry no. The point of that panel is to inform the end user about the status (and issues) of the TXP install - if possible in a language that said end-user is familiar with (not everything is fully translated). Helping support people  should only be a very secondary concern (they can use any of the translation sites).

**Comment by philwareham** [comment]
Tend to agree with Philippe here. It would be a shame to lose the translated preflight region. The text area in English is fine though.

**Comment by bloatware** [comment]
I don't like duplication. Would a possibility to temporarily switch to another language (without importing strings into db) be a option? Then we could output the diagnostics in any available language.

**Comment by philwareham** [comment]
We are only talking of around 24 tests where there would need to be both localised and English text string duplicates. Isn't that a price worth paying to allow preflight to be localised and textarea in English? They'd all follow the current pattern of `diag_` prepended to them for the `mode.ini` string versions.

**Comment by Bloke** [comment]
We could perhaps be more clever, like @bloatware says.

At the moment, the strings are rendered into an array called `$fail` and then just dumped to the screen. Perhaps instead, we do something like this:
```
$fail[] = array(name_of_gTxt_key, param1 => value1, param2 => value2, ...);
$warn[] = array(name_of_gTxt_key, param1 => value1, param2 => value2, ...);
$info[] = array(name_of_gTxt_key, param1 => value1, param2 => value2, ...);
```
(or use one array and make the type the second param or something).

That way, we have array(s) of messages so we know all the details about how to render them in. No strings have been built at this stage. We can't use the array keys to store the `gTxt()` tokens, unfortunately, because some messages use the same tokens with different parameters.

At render time, we loop over the array(s) and pass everything through `gTxt()` and `diag_msg_wrap()` to create the strings in the current language. Output them above the textarea.

When we want to drop them in the textarea, temporarily switch admin language to English, render the strings, then switch back. It _should_ automatically pick up the strings from the `mode.ini` if we add them there too.

That's the least amount of duplication I can think of. Anyone come up with anything better or fancies taking a stab at it today, be my guest. If not I'll try and get to it (much) later tonight.

**Comment by Bloke** [comment]
I've started this. Should be done tonight, with luck. Just trying to fathom a neat way around the 'unwritable-directory' messages which share a pophelp but potentially list individual directories alongside. Don't want to have to put the same pophelp by each so my initial idea of putting everything into an array needs tweaking slightly.

**Comment by bloatware** [comment]
Nice, but it seems that `en` language must be installed to make it work properly. Could strings rather be retrieved directly from `en.ini`, without importing them into db?

**Comment by phiw13** [comment]
> Nice, but it seems that `en` language must be installed to make it work properly.

Aah, that is the issue I was seeing. With French on the admin side and `en-gb` on the front end, I saw a raw string in the textarea (`still_exists`, the only issue that ought to appear on this install, setup…). No `en` installed.

**Comment by Bloke** [comment]
D'oh, well spotted. I'll get it to load pack from file, rather than load lang. Bit more expensive, but it's not on the critical path.

**Comment by phiw13** [comment]
@Bloke - Thanks, works fine with your  latest patch.
