### ISSUE TITLE
Importable theme list not updated on theme deletion

### ISSUE THREAD

**Issue by NicolasGraph** [textpattern/textpattern#1146]
This applies to the _themes_ branch.

Once a theme deleted from the DB, if it still exists as an importable directory, it should be automatically added to the import select list. However, it does need a page refresh for now to see it added. I had this kind of issue before but, at the moment, I can't remember how I fixed it…

**Comment by Bloke** [comment]
This is probably a by-product of moving to the `Table` class which, I believe, does AJAX actions by default.

**Comment by NicolasGraph** [comment]
Ok @Bloke, can think about a way to fix? Should the the select list be updated via AJAX? Not sure I would be able to do it.

**Comment by Bloke** [comment]
Well that's the thing. It shouldn't make any difference as long as the code that renders the import selector is refreshed as part of the action of redrawing the table. Look at `txp_file.php` and you'll see in `file_list()` that the `$createBlock` is repopulated every time the function is called, to reset the file import selector.

It may be the order of execution of your multi-edit code (it has to run before you repopulate things) or it may be the fact that your instantiation of things in order to actually preform the multi-edit is cached so that when the page loads, it reads the stale info. Weirdly, from a cursory glance at the code, I can't see anything wrong with the approach you've taken.

ASIDE: Why is your asset class called `Css` now? Shouldn't it be `Style`? Or is there a reason for the name change to make it easier to pass things around or take advantage of reuse?

My tests choke on it because the class refs are `Css` but the class name on disk is `CSS` (upper case). So either:

a) they need to be renamed `Style` throughout (my preferred option, although I know we do 'internally' refer to it stylesheets as 'css' a lot, which we probably shouldn't). But if this name is not possible without a lot of refactoring, then...
b) ... alter the case of CSS to make it consistent, either all-caps or sentence case.

**Comment by NicolasGraph** [comment]
> ASIDE: Why is your asset class called Css now? Shouldn't it be Style? Or is there a reason for the name change to make it easier to pass things around or take advantage of reuse?

I used `Css` to improve consistency between classes, events and tables name as for textpack strings.
While I do not use this a lot for now, we could imagine something like `$class = ucfirst($event)`, `$table = safe_pfx('txp_'.$event)` and like in the `Table` class: `$heading = gTxt('tab_'.$event`).
However, just tell me if it seems not necessary to you. I would apply your preferred name.

**Comment by Bloke** [comment]
Css is fine if it's for consistency with the (poorly named, imo) stuff in the existing codebase. It's just the case sensitivity that needs fixing then. Rename the file `Css.php` and the errors should go away.

**Comment by NicolasGraph** [comment]
My local file is correctly named… It seems it was not renamed when pushed.
I'm going to try again; thanks @Bloke.

**Comment by Bloke** [comment]
Cool. Probably git trying to be too clever...

**Comment by NicolasGraph** [comment]
> Probably git trying to be too clever...

Yes, I needed to rename it `Csss.php` before to come back to `Css.php`.

**Comment by NicolasGraph** [comment]
> Look at txp_file.php and you'll see in file_list() that the $createBlock is repopulated every time the function is called, to reset the file import selector.

In fact, in the _themes_ tab, the import form is correctly updated on import — the imported theme is removed from the list. Wouldn't it be the multi-edit form only which works with AJAX calls? I don't know AJAX well; not sure it makes sense…

**Comment by Bloke** [comment]
> Wouldn't it be the multi-edit form only which works with AJAX calls?

Yes and no. The call itself is an AJAX request. But on completion of the asynchronous call, the last thing it does is call the appropriate `*_list()` function which returns the new table, including any surrounding controls (search control, list options, form controls, pagination options in case the thing you just deleted has changed the number of pages, ...). This is then just chucked on the page as-is in place of the current table, which "refreshes" the screen, albeit without a full page refresh.

The trouble with multi-edit, is that the flow is this:

1. Form submitted (via regular call or AJAX - doesn't matter).
2. Page starts to draw. menu items, language strings loaded, stuff begins to be cached.
3. Action determined: multi-edit. Great.
4. Service the multi-edit action.
5. Carry on drawing the remainder of the page.

The trouble is that if step 4 altered something that was previously cached in step 2, unless you "force" reload the content from disk/DB into the internal variables/globals/statics, when the page rendering reaches step 5, stale content may be drawn.

When you call a static function for the first time or store a static var, it's often coded so that the next call will return a handle to what _used_ to be in that variable when it was first instantiated. I suspect that's what's happening here, but I must admit I can't see where this is happening.

**Comment by bloatware** [comment]
Async updating importable themes list should be easy - just concatenate 'create' and 'content' blocks:
```
            return $table->render(
                compact('total', 'criteria'),
                $this->getSearchBlock($search),
                '',
                $this->getCreateBlock().
                $this->getContentBlock(compact('offset', 'limit', 'total', 'criteria', 'crit', 'search_method', 'page', 'sort', 'dir')),
                $this->getFootBlock(compact('limit', 'numPages', 'total', 'crit', 'search_method', 'page', 'sort', 'dir'))
            );
```
By default, only the third (content) block is async updated. Sorry for the lack of documentation, but `Table` class (and the whole async update thing) is not yet mature enough.

**Comment by NicolasGraph** [comment]
> Async updating importable themes list should be easy - just concatenate 'create' and 'content' blocks…

Corrected in https://github.com/textpattern/textpattern/pull/1148, thanks @bloatware.
