### ISSUE TITLE
Theme terminology namespacing: `theme` and `public-theme`

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1159]
Background: https://github.com/textpattern/textpattern/issues/1158#issuecomment-367025024 and followup from @Bloke https://github.com/textpattern/textpattern/issues/1158#issuecomment-367027542

The Textpattern 4.7.0 automated installer uses JSON for the setup details, and the `site` section (excerpted below) refers to `theme` and `public_theme`:

```
"site": {
        "lang": "",
        "siteurl": "",
        "theme": "",
        "public_theme": "",
        "datadir": ""
    },
```

The admin-side is `theme` and the front-side is `public-theme`. `theme` on its own is vague and many (?most) CMS admins will assume a theme is typically for the front-side of proceedings, not admin-side in this case.

Possible solutions:

* rename `theme` to `admin_theme`, keep `public_theme` as-is
* rename `theme` to `admin_theme`, rename `public_theme` to something in the Textpattern branding handbook (are we referring to "front-side" these days, or something else? I'm a bit out of the loop on that score.)

If this is fairly painless, I'll open another issue on completion to rename a few other strings in the JSON to be more user-friendly and less nerdy (e.g. `db`, `datadir`) and perhaps add a few underscores to split conjoined words.

Thank you in advance.

**Comment by Bloke** [comment]
We should look at all the keys actually, as you suggest. I think datadir, for example, is just something makss chose arbitrarily. It could be anything, as long as we're consistent throughout.

Propose ideas for better key names and we'll get this done.

**Comment by petecooper** [comment]
Assuming the JSON is exhaustive:

* `site` &rarr; leave as-is
** `lang` &rarr; `site_language` (users can have their own local lang, etc)
** `siteurl` &rarr; `site_url`
** `theme` &rarr; `admin_theme`
** `public_theme` &rarr; `front_theme` or leave as-is
** `datadir` &rarr; `data_directory` (I don't know what this does)
* `mysql` &rarr; `database` (leaves scope for non MySQL stuff in future)
** `user` &rarr; `username`
** `pass` &rarr; `password`
** `host` &rarr; leave as-is (can be hostname or IP, after all)
** `db` &rarr; `database`
** `table_prefix` &rarr; leave as-is
* `user` &rarr; leave as-is
** `realname` &rarr; `real_name`
** `name` &rarr; `username`, `login_name` or leave as-is
** `pass` &rarr; `password`

**Comment by Bloke** [comment]
Great start, thank you. A few comments:

1. If we're prefixing the group, can we get away with not repeating the group name in the keys themselves? e.g. `site` -> `site_language` could become `site`-> `language` or (perhaps better for ambiguity) `language_code` since we don't want anyone writing `English` or `French` in there, It needs to be `en`, `fr`, etc. Same with `site_url`. Could just be URL.
2. `mysql` -> `database`. Love it. Means we can introduce a "type" field later that defaults to MySQL without breaking anyone's current automated installs. Forward thinking; I like that.
3. I suspect a lot of these names were chosen for brevity so we could internally just do a sneaky `extract()` in the code and have them overwrite their manually-set counterparts. Certainly things like `name` and `pass` are used in the login credentials box, and `realname` is a database column name. Similarly, `user`, `pass`, `host` and `db` are just the corresponding global variables in our database credentials global object during setup.

There are a couple of ways to approach it:

a. (the proper way) Change the internal array keys during both manual and automatic processes to something more sensible than the short values we present here. Ensure references throughout the manual process match up, and the correct keys are used in setup_lib too when the DB is created and values are injected.
b. (the dirty way) Just translate the JSON keys when they're read in and set the corresponding "internal" vars.

Of course I'd favour (a) but it's a bit more work.

**Comment by petecooper** [comment]
Revised:

Assuming the JSON is exhaustive:

`site`
`lang` &rarr; `language_code`
`siteurl` &rarr; `url`
`theme` &rarr; `admin_theme`
`public_theme` &rarr; `front_theme` or leave as-is
`datadir` &rarr; `data_directory` (I still don't know what this does)

`mysql` &rarr; `database`
`user` &rarr; `username`
`pass` &rarr; `password`
`host` &rarr; leave as-is
`db` &rarr; `database`
`table_prefix` &rarr; lead as-is

`user` &rarr; leave as-is
`realname` &rarr; `real_name`
`name` &rarr; `username`, `login_name` or leave as-is
`pass` &rarr; `password`

There's also option…

c. (the middle ground) Find the quick fixes and document the JSON, either inline via comments (preferred) or another doc elsewhere (yay SEO etc).

…and that's my starter.

**Comment by petecooper** [comment]
+1. Leave `public_theme` as-is (unless anyone objects), then we have `admin_theme` & `public_theme`.

**Comment by Bloke** [comment]
Hopefully 832281e improves things. This is the full list I went with in the end:

```
{
    "site": {
        "language_code": "en",
        "public_url": "",
        "admin_url": "",
        "admin_theme": "",
        "public_theme": "",
        "content_directory": "",
        "cookie_domain": ""
    },
    "database": {
        "user": "",
        "password": "",
        "host": "localhost",
        "db_name": "",
        "charset": "",
        "table_prefix": "",
        "client_flags": ""
    },
    "user": {
        "full_name": "",
        "email": "",
        "login_name": "",
        "password": ""
    }
}
```
Notes and deviations from Pete's proposal:
1. I went with host/user/password/charset for the database section because that's what MySQL calls them and it seemed logical to use that terminology. Most vendors probably follow suit. We can introduce `database->type` or something in future when we officially expand our scope into PDO.
2. Using `database->database` for the database name seemed a bit obtuse. Using `database->name` might be mixed up with user name, so I chose middle ground and went with `database->db_name`. Any better ideas anyone?
3. I chose `user->full_name` over `real_name` as it's more descriptive and plumped for `user->login_name` instead of the other alternatives because it's clearer than just `login` or something like that.
4. It seemed logical to use `site->public_url` instead of just `site->url` since it's possible to specify the `admin_url` for multi-site installations. The admin/public split we chose for themes is echoed here to remain consistent.
5. I selected `site->content_directory` because that's what it is: it holds additional content you may wish to load with your theme. Provided the theme manifest is set up to look for them via a `txp-data` entry, you can import prefs, plugins, articles, and other XML data during theme installation.

@jools-r Hope these are okay and doesn't marmalise the multi-site stuff. I think I've caught them all (e.g. `admin_url` and `cookie_domain`) but if I've missed anything, please shout.

**Comment by Bloke** [comment]
Ack, the `public_theme_name` pophelp and `gTxt()` strings during setup refer to "Front-side theme". Darnit.

**Comment by philwareham** [comment]
We can just change the wording of those texts. I'm sure other languages don't literally translate that anyway.

**Comment by petecooper** [comment]
Top work, @Bloke - thank you.

**Comment by petecooper** [comment]
I've updated OP at https://github.com/textpattern/textpacks/issues/256 - thanks @philwareham.

**Comment by petecooper** [comment]
Job done - closing.
