### ISSUE TITLE
Uncaught Exception while updating

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1183]
Status: logged out of site, lang `ar-dz` installed, `git pull` at [commit](https://github.com/textpattern/textpattern/commit/eb26dfb733d61a05641df4635ba47d22c52de73b):  Fix naked strings on first login after upgrade (previous update was ~14hours ago).

```
Fatal error: Uncaught Exception: update failed in /Users/username/Sites/test-site/textpattern/lib/txplib_misc.php:1719 
Stack trace: 
#0 [internal function]: updateErrorHandler(2, 'file_get_conten...', '/Users/username/S...', 363, Array) #1 /Users/username/Sites/test-site/textpattern/vendors/Textpattern/L10n/Lang.php(363): file_get_contents('') 
#2 /Users/username/Sites/test-site/textpattern/vendors/Textpattern/L10n/Lang.php(391): Textpattern\L10n\Lang->getPack('ar-dz') 
#3 /Users/username/Sites/test-site/textpattern/update/_update.php(121): Textpattern\L10n\Lang->installFile('ar-dz') 
#4 /Users/username/Sites/test-site/textpattern/index.php(218): include('/Users/username/S...') 
#5 {main} thrown in /Users/username/Sites/test-site/textpattern/lib/txplib_misc.php on line 1719
```

Added some line breaks in the stack trace for readability.
Guess I’ll go have a look  at the DB and remove the language pack there.

cc @Bloke

**Comment by phiw13** [comment]
Hmm, reloading the page actually let me in straight to the Lang panel (a truckload of `notice` name something… … …`). Delete the lang (ar-dz) and all was fine.

**Comment by philwareham** [comment]
I’ve changed `ar-`DZ language Textpack to `ar` now as it is not specifically Algerian any more. Maybe this needs some code in the upgrade scripts to convert existing users? @bloke can you confirm?

**Comment by Bloke** [comment]
I spotted a similar thing during my final testing last night (hence the commits) and will fix as soon as I can today. Also need some defensive code to check if a language file has been deleted but is still installed in the DB. That throws some errors on the Languages panel currently when it tries to find the language name from the missing file.

**Comment by phiw13** [comment]
>  spotted a similar thing during my final testing last night (hence the commits) and will fix as soon as I can today. Also need some defensive code to check if a language file has been deleted but is still installed in the DB. 

Ah, good, you are already aware of the issue. I still have one install that is _many_ commits behind (3 weeks worth of it I think). I can install `ar-dz` there as it still exists there, and then test your upcoming work.

> That throws some errors on the Languages panel currently when it tries to find the language name from the missing file.

That is probably what I saw once I got pass the the error and landed on Lang panel

**Comment by Bloke** [comment]
Right, 3c423e59 and 74c041a4 should make things a bit more robust in this department. As well as fixing the OP, if a file is now missing for an installed language, you will now see:

a. the name of the language as 'unknown' in the currently installed lingo.
b. the box in amber. It retains the check mark because it's installed and, as far as the system is concerned, up-to-date since there's no file to compare it against.
c. no update button, since it can't be updated from file.

Short of introducing a new language string for 'missing file' or something on this panel, I figured that was a pretty good compromise.

Please take it for a spin, try upgrading from a language that has had its filename changed, and also try deleting/renaming files in the `lang` directory to see the effects.

**Comment by phiw13** [comment]
So, on that's TXP 4.7.0 dev install, I made sure `ar-dz` was installed. For good measure, I toggled it on as admin language and back to `en-gb`. Logged out.
Updated all the files from latest Git and logged back in (landing on the articles panel, the default) and greeted with the “you’ve been updated…”.  Curse Safari for being stubborn in caching JS / CSS files.

Heading over to the Languages panel: `ar-dz` was transparently updated to `ar`.  Nice.

I renamed one of the installed languages, then revisited the Lang panel. Amber box etc as described.

Good to go!  🥂

**Comment by Bloke** [comment]
Awesome, thanks for testing. The primary culprit was the lack of conversion of `ar-dz` => `ar` in the `validLocale()` call. All the other stuff I did last night and this morning should help smooth upgrades for users of non-English as a primary language.

After logging out and upgrading, I've actually taken to doing force refresh on the login screen as it saves the notification after logging in. The only downside is that the 'name' label above the login box doesn't get translated, because its string is expected to be in a different group than the one in which 4.6.2 had it, and it isn't moved until the upgrade process completes after logging in.
