### ISSUE TITLE
Zip with symlinks - clarification

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1189]
Hi @petecooper and @jools-r - can you possibly test the Zip file download from here https://github.com/textpattern/textpattern/releases/tag/4.7.0-beta and let me know whether it has included the symlinks?

If yes, we can plan to just have a Zip download from the site in future which simplifies things. If not, can you let us know (and possibly provide instructions to get it working) as you are the two designated experts on this now! :)

I gave this basic CLI example to Stef:

    zip --symlinks -r textpattern.zip textpattern/

But he's not sure if by using macOS it has zipped it with symlinks successfully.

Thanks guys!

**Comment by jools-r** [comment]
The regular zip download doesn't include the `/sites` folder at all ;-)

But the source code (zip) does, and … the symlinks are included:

<img width="654" alt="bildschirmfoto 2018-03-08 um 11 43 40" src="https://user-images.githubusercontent.com/1203899/37147135-3044ecc6-22c6-11e8-8502-7f68a55d09ae.png">

(Screenshot from Transmit)

@Bloke: you can unzip and then check with @ls -la@ in the Terminal:

<img width="713" alt="bildschirmfoto 2018-03-08 um 11 47 19" src="https://user-images.githubusercontent.com/1203899/37147249-96d81de6-22c6-11e8-9d40-6cb6702b4531.png">

I can only check on the Mac, though...

**Comment by philwareham** [comment]
Ah, maybe the build/release script currently takes multi-site stuff out of the Zip version (which it probably shouldn't now)?

**Comment by Bloke** [comment]
Yah nuts! Traditionally, the zip doesn't usually contain the `/sites` folder at all. I figured that with the `--symlinks` option in the [build script](https://github.com/textpattern/textpattern-toolbelt/blob/master/release/txp-gitdist.sh) it would just roll them in, but it doesn't seem to do so. The reason? `--exclude textpattern-$VER/sites/`

*Forehead smack*

**Comment by philwareham** [comment]
It's fine Stef - that's why we have beta releases. If we can get this honed down for beta 2 then we don't have to generate a Gzip version in future.

**Comment by Bloke** [comment]
The attached might be better. Please try that and report if the symlinks are true links. They look good to my untrained eye.

[textpattern-4.7.0-beta-zip.zip](https://github.com/textpattern/textpattern/files/1792883/textpattern-4.7.0-beta-zip.zip)

**Comment by jools-r** [comment]
Yup, that's fine.

**Comment by philwareham** [comment]
Yep, I can see the symlinks here in the new zip. Should we upload that to the GitHub tag release to replace the current Zip - it does not affect the tag and there is no codebase changes whatsoever so I can't see a reason not to. If so, please remember to generate a new SHA256 too!

**Comment by Bloke** [comment]
Here they are:

[textpattern-4.7.0-beta.zip](https://github.com/textpattern/textpattern/files/1792920/textpattern-4.7.0-beta.zip)

[textpattern-4.7.0-beta.zip.SHA256SUM.txt](https://github.com/textpattern/textpattern/files/1792922/textpattern-4.7.0-beta.zip.SHA256SUM.txt)

Note I had to add `.txt` to the end of the checksums file so GitHub would accept it.

**Comment by philwareham** [comment]
Cheers, have you updated the files on the Github tag already?

**Comment by Bloke** [comment]
Not updated those, no.

But I have just tweaked the [toolbelt readme](https://github.com/textpattern/textpattern-toolbelt/commit/86308924a7d064fcaf4f62f481687ff66e467c7d). I've assumed that you'll use category names without any indication of their type in parentheses. Please update that if you intend to use a different category naming scheme.

**Comment by petecooper** [comment]
It's one thing being able to see symlinks in the .zip, but do they extract and work on Windows systems? That's the legacy snag.

**Comment by Bloke** [comment]
True dat.

**Comment by philwareham** [comment]
I though @jools-r had built round that with the setup scripts - symlinks are created if they were missing?

**Comment by petecooper** [comment]
Recursive `diff` here shows zero differences between the extracted output of https://github.com/textpattern/textpattern/files/1792883/textpattern-4.7.0-beta-zip.zip and https://github.com/textpattern/textpattern/files/1792887/textpattern-4.7.0-beta-zip.tar.gz

**Comment by jools-r** [comment]
> do they extract and work on Windows systems? That's the legacy snag.

That would be interesting to know

> I though @jools-r had built round that with the setup scripts - symlinks are created if they were missing?

It's in the pre-installer, yes, so it should catch situations where it doesn't work. But: that needs testing on windows to see if it really works as planned!

**Comment by Bloke** [comment]
Results:

* .zip unzips fine on Windoze (7). Symlinks, however, aren't created per se. The files exist, but you can't double click them (Win asks what you want to do with it). Opening one in vi shows the path it _should_ resolve to (e.g. `../../../textpattern/vendors`) as file content.
* .tar.gz doesn't unzip in 7-Zip on Windoze. The .gz is fine, but extracting the .tar results in a failure message "Cannot create symbolic link: access is denied". In this case, the files are created as before but editing them in vi reveals no content whatsoever.

So either way, Windoze users are out in the cold and will have to rely on the setup process to create symlinks if it can. If I get a chance I'll try and run it on Windoze but I don't have a LAMP stack installed right now.

**Comment by petecooper** [comment]
Confirming Windows 7 doesn't factor in symlinks when using TarTool to extract the .tar.gz:

![virtualbox_w7p base_08_03_2018_11_55_52](https://user-images.githubusercontent.com/226578/37149952-d1e1f528-22c7-11e8-90db-f7cf710625c4.png)

**Comment by petecooper** [comment]
How big a deal is this in the grand scheme? Windows users running multisite, I mean. I would expect an uptick in people using it since @jools-r's big rewrite of it, sure, but what magnitude is this issue?

Also, related, what's the ratio of .zip vs .tar.gz downloads, roughly? Is there a sane way to check?

**Comment by philwareham** [comment]
Yes I have download figures from the .com site. Gzip makes up 8.4% of downloads of v4.6.2 so we can safely ditch it I think for two reasons:

1. Pretty much any modern Unix system can handle .zip files natively
2. The Gzip clearly doesn't work well on Windows due to the symlink warning messages (in 7-Zip anyway)

**Comment by Bloke** [comment]
So even before we included symlinks in the zip, nobody could get symlinks on Windows, using either package. Right now:

* *nix users can use the .zip and extract the symlinks just fine.
* OSX users ditto.
* Windows users can use the .zip to extract them, but they'll not be true symlinks. But they never had them anyway, regardless so it's not a backwards-compatibility issue.

The only unknown now is what happens if the multi-site pre-installer sees a file where a symlink _should be_, but it's not actually a symlink. Essentially, in Windows, it's a text file with the symlink location inside it as ASCII content. Will the pre-installer go "Cool, got them" and then fall over? Is it actually better if they're totally missing so the multi-site pre-installer can detect this?

In which case, we'll need to:

a) work around that (test if they're actually links); or
b) remove the symlinks from the zip, and reinstate the `.tar.gz` so that non-windows users who want multi-site can get a package with them in.

**Comment by petecooper** [comment]
and:

c) clearly document the steps required for users to recreate the symlinks as required, on UNIX-based servers (`ln -s`) and Windows-based servers (`mklink` under NTFS)

**Comment by petecooper** [comment]
Windows git (GUI) installed with symlink support does clone the symlink files, but doesn't make them into anything usable (i.e. they don't work):

![virtualbox_w7p base_08_03_2018_12_10_50](https://user-images.githubusercontent.com/226578/37150702-9a84d7e6-22ca-11e8-8389-7012829cf3dc.png)
![virtualbox_w7p base_08_03_2018_12_13_53](https://user-images.githubusercontent.com/226578/37150703-9aa379a8-22ca-11e8-9d03-342523cf33ce.png)
![virtualbox_w7p base_08_03_2018_12_14_58](https://user-images.githubusercontent.com/226578/37150704-9abd3294-22ca-11e8-9fce-00f0d8ddb2b1.png)

…which leads me to wonder: if a Windows host can clone the repo, make symlinks on an NTFS system to match the UNIX-style symlinks and then raise a PR to merge them in, would that resolve the issue? Too edge case-y?

**Comment by Bloke** [comment]
> Windows git (GUI) installed with symlink support does clone the symlink files, but doesn't make them into anything usable (i.e. they don't work)

Looks like a similar result to extracting the `.zip` package: files created (essentially) as dumb text files. Do they contain any content if you open them in a text editor?

**Comment by petecooper** [comment]
@Bloke 
>Do they contain any content if you open them in a text editor?

Yes, a relative path to its target:

![virtualbox_w7p base_08_03_2018_12_48_38](https://user-images.githubusercontent.com/226578/37151828-0b80ef4e-22cf-11e8-951c-10926c1da88d.png)

**Comment by petecooper** [comment]
>…which leads me to wonder: if a Windows host can clone the repo, make symlinks on an NTFS system to match the UNIX-style symlinks and then raise a PR to merge them in, would that resolve the issue? 

It doesn't. Can't have two files called the same thing, so no dice.

**Comment by jools-r** [comment]
> The only unknown now is what happens if the multi-site pre-installer sees a file where a symlink should be, but it's not actually a symlink. Essentially, in Windows, it's a text file with the symlink location inside it as ASCII content. Will the pre-installer go "Cool, got them" and then fall over? Is it actually better if they're totally missing so the multi-site pre-installer can detect this?

The preinstaller tries to ascertain whether the vendors symlink resolves correctly [here](https://github.com/textpattern/textpattern/blob/dev/sites/site1/admin/setup/index.php#L32):

```
if (!is_dir(realpath($multisite_admin_path.'/vendors'))) {
```

Presumably that fails if the file is there but not an actual symlink? (but: can you check that to be sure?)

> c) clearly document the steps required for users to recreate the symlinks as required, on UNIX-based servers (ln -s) and Windows-based servers (mklink under NTFS)

The preinstaller does this too [here](https://github.com/textpattern/textpattern/blob/dev/sites/site1/admin/setup/index.php#L156) :-). If the symlink-creation doesn't resolve it provides copy-paste instructions to switch to the right directory and the three `ln -sf` or `mklink` commands. There was a screenshot in one of the commits/PRs showing that.

I'd love someone to test that. While my shared office colleagues use windows machines, I can't install a lamp stack on their computers.

**Comment by jools-r** [comment]
Am I right in assuming I could test this by installing [WAMP](http://ampps.com/wamp) or [XAMPP](https://www.apachefriends.org/index.html) on a Windows VM? As long as it's not **L**AMP, it should be running on a windows server, right?

I've started downloading a VM from the [MS Edge](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) site but a) I'm not sure if the VM prevents you installing something like that and b) whether my version of VM 8.5.2 still works on High Sierra. I'll give it a go.

**Comment by petecooper** [comment]
I've got a full set of Windows Server installers. Let me know what I can do.

**Comment by jools-r** [comment]
> I've got a full set of Windows Server installers. Let me know what I can do.

Can you try a multisite install on windows and report back whether the pre-installer correctly (re)creates the symlinks that are broken and then proceeds with the installation?

(@petecooper: weirdly I gut your message per mail but don't see it in this thread on GitHub.)

**Comment by petecooper** [comment]
@jools-r - sure thing. I've never installed a WAMP server before, so I'll learn by doing! It might take a while for me to get my head around it, but bear with me.

Do you want a copy of the installer ISO (30 day eval) to prod and poke?

**Comment by jools-r** [comment]
I would simply have tried WAMP/XAMPP or MAMP for windows (the VM download was still in progress when I left the office). But – excuse the naive question – is a WAMP/AMP stack on Windows the same thing as a Windows IIS server that a user might have with a webhost? 

Another idea: I know some web hosts allow you to trial a webserver for x days before committing. Perhaps there are web hosts that offer that for windows servers. The tricky bit there is that you need to be able set subdomains are most such test accounts are usually themselves a subdomain of their host until you hook it up to your own domain. Or can one create sub.sub.domains?

**Comment by jools-r** [comment]
> We should put a call out on the forum to see if anyone with an existing Windows server can take a look, perhaps saving me some of the Friday evening astonishment and occurrences of "HOW DO PEOPLE LIVE LIKE THIS?" etc.

:-) exactly my thoughts!

**Comment by petecooper** [comment]
Call to action posted: https://forum.textpattern.io/viewtopic.php?id=48506

**Comment by petecooper** [comment]
This issue has strayed from the OP – symlinks in archives _don't_ work on Windows, whatever the format of the archive, and I'm setting up a Windows 2016 test rig to ensure the multisite stuff works as intended with symlink creation.

With that in mind, my vote would be to close this issue since we've established there's no reliable way to have cross-platform symlinks, and if they're created correctly then it's a non-issue.

Whether or not the .tar.gz is retired is another matter and outside this issue's scope.

So, close?

**Comment by Bloke** [comment]
So I think we've established:

1. *nix/OSX users can use the `.zip` just fine and extract the symlinks as intended, the same as they used to do with the `.tar.gz` only.
2. Windows users can extract the `.zip` contents as before. The symlinks are broken, resulting in text files with the symlink destination embedded.
3. Thus there's no need for the `.tar.gz` file to be distributed any more.

The only issue on Windows is that the pre-installer will detect the symlinks don't resolve properly, offer the instructions for creating them by hand, _but the files where the symlinks need to reside already exist_ because they were in the archive and have been extracted as regular, bogus text files.

Options:

a. Expand the instructions (if necessary) to include information about deleting any in-the-way fake symlink files before trying to use `ln -s`.
b. Revert to previous behaviour: embed no symlinks in `.zip` file and reinstate the `.tar.gz` for those that need the multi-site functionality.

In the absence of a third option (anyone? Bueller? anyone?) which of the above is the lesser of two evils?

**Comment by philwareham** [comment]
I think option b would be my preferred option. The zip still allows you to create missing symlinks on install doesn't it?

**Comment by Bloke** [comment]
Yep, the pre-installer takes care of trying to create symlinks and if it can't it'll prompt you (in theory - would love to prove it all works on Windows!)

**Comment by philwareham** [comment]
OK, let's continue to provide a zip (with no symlinks) and a Gzip (with symlinks).

**Comment by philwareham** [comment]
Closing - cheers all!

**Comment by petecooper** [comment]
@Bloke in https://github.com/textpattern/textpattern/issues/1189#issuecomment-373693096
>(in theory - would love to prove it all works on Windows!)

Working on it, haven't forgotten – had a very full week and I'm a bit behind schedule, but I've started the server build. Virtualbox is a bit…crash-y for me, for some reason, but the base OS (Windows 2012 R2) is set up:

![virtualbox_w2012 base_16_03_2018_12_23_05](https://user-images.githubusercontent.com/226578/37520438-e3af662a-2914-11e8-8081-eaf21ea5f8af.png)

**Comment by jools-r** [comment]
FWIW: I tried with XAMPP using a modernIE VM but it fails due to a lack of administrator rights. So inconclusive up to now.

**Comment by Bloke** [comment]
Reinstated `.tar.gz` output in the textpattern-toolbelt.

**Comment by vanmelick** [comment]
On 08/03/18 13:05, Phil Wareham wrote:
>
> Yes I have download figures from the .com site. Gzip makes up 8.4% of 
> downloads of v4.6.2 so we can safely ditch it I think for two reasons:
>
>  1. Pretty much any modern Unix system can handle .zip files natively
>  2. The Gzip clearly doesn't work well on Windows due to the symlink
>     warning messages (in 7-Zip anyway)
>

Of course .tar.gz has lesser downloads... because the download link on 
the homepage links only to the .zip file and you have to actively search 
for the page where you can download the tar.gz file.
Look at how Wordpress does it, their download button on the homepage 
links to the /download page where both formats are available (as they 
should be!).
Personally, as a Linux user, I always prefer to download in tar.gz 
format. Just having a ZIP for software that mostly runs on Linux feels 
weird.

PS. It has been amazing to see the amount of communication here. Can't 
really keep up with it all anymore, but it's great to see that the 
project is more alive that it has ever been.

--Ruud

**Comment by philwareham** [comment]
I can easily change the homepage button to go to the download page instead. I will do that when we launch 4.7 proper I think.
