### ISSUE TITLE
Finer articles associated to sections view

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1207]
For the next 4.8 release.

Devs, would you consider to introduce a new way to publish within sections like the `rah_wrach` plugin can do.

Just because it can be a headhache. Keeping the actual article list for search and/or for consultation of associated elements attached to them (such as categories, statuses, comments, date/time and so on), so "Articles" entry from the main menu could display a grid (`rah_wrach` like UI) and a new one named "Articles List" for the existing display.

However, a such visual and accessibility improvement may imply a *new preference* into the individual "Section" view in order to set each section for *only administrators access* and all others included into the new view (as explaned above).

**Comment by Bloke** [comment]
Confused. What's wrong with rah_wrach? It still works beautifully under 4.7.0 (aside from the prefs not showing up, but that's a minor tweak), so if it fits your needs, why change core for everyone?

I could perhaps see a slightly modified version of the plugin that links to the `default_publish_section` pref (on the Sections panel). Instead of offering the per-user choice of sections as a pref on the prefs panel, it could permit the default publish section dropdown to be a multi-select list. If you only pick one, the Write panel behaves as it does now. If you select more than one, it offers the 'choose your section' first.

That may be something we consider as a core feature, but it seems it's still best left to a plugin imo. I could be swayed either way.

**Comment by cara-tm** [comment]
Yes. May be a core integration ;)

**Comment by cara-tm** [comment]
Ok. Hidden some sections from the dropdown list into the write panel is the main demand here. Lot of us create some "statics" pages to display a contact form for example. Not intended to display dynamic articles/content. This feature is not a complex one (I do it myself into an old TXP version years ago): just add an new "hidden" entry into the txp_section table and invoque this field within sections requests. Can be even done for this release.

**Comment by Bloke** [comment]
I wrote a tiny plugin once to filter the list of sections, per privilege group, from the Write panel and the Articles panel:

1. It's not very clever. You can still search for articles in the hidden sections and find them, for example, so it could do with being hardened a little.
2. It requires you to hack the plugin to list the sections you _don't_ want to display. This could be exposed as proper prefs instead. And could be altered to list ones you _do_ want to display if that's easier.
3. The returned section list on the Write panel should be rendered using `inputLabel()` not constructed by hand.

With those caveats in mind, the general idea is this:

```php
register_callback('smd_filtlist', 'admin_criteria', 'list_list');
register_callback('smd_filtlist_article_section', 'article_ui', 'section');

global $smd_filtlist_exclusions;
// -----------------------------------------------------------
// Configure which section _names_ to exclude per priv level.
// Each level has its own row and the sections should be listed like this:
//   level => array('section1', 'section2', ...),
$smd_filtlist_exclusions = array(
	0 => array(), // None (unused)
	1 => array(), // Publisher
	2 => array(), // Managing Editor
	3 => array(), // Copy editor
	4 => array(), // Staff writer
	5 => array(), // Freelancer
	6 => array(), // Designer
);

// -----------------------------------------------------------
function smd_filtlist($step, $event) {
	global $smd_filtlist_exclusions;

	$priv = smd_filtlist_priv();
	return " AND section NOT IN (".doQuote(join("','", $smd_filtlist_exclusions[$priv])).")";
}

// -----------------------------------------------------------
function smd_filtlist_article_section($step, $event, $orig, $data) {
	global $smd_filtlist_exclusions;

	$priv = smd_filtlist_priv();
	$selSec = empty($data['Section']) ? getDefaultSection() : $data['Section'];

	$rs = safe_column('name', 'txp_section', "name != 'default' AND name NOT IN (".doQuote(join("','", $smd_filtlist_exclusions[$priv])).")");

	if ($rs) {
		return n.graf('<label for="section">'.gTxt('section').'</label> '.
				'<span class="small">['.eLink('section', '', '', '', gTxt('edit')).']</span>'.br.
				selectInput('Section', $rs, $selSec, false, '', 'section')).
				n.'</fieldset>';
	} else {
		return ' ';
	}
}

// -----------------------------------------------------------
function smd_filtlist_priv() {
	global $txp_user;

	$authinfo = safe_row('*', 'txp_users', "name = '$txp_user'");
	return $authinfo['privs'];
}
```

**Comment by Bloke** [comment]
Interesting idea. So sections get another property "content publishable" (or something)? My concern is that this breaks the notion of content assigned to any section. Consider the following:

Is the implication of such a checkbox that you (as admin/publisher) can still access all articles for all sections? So you can add an article to your "contact" section that explains how to get in touch, but regular Copy Editors can only publish to a handful of sections like 'blog', and 'archive'?

Or is it locked out for all users? So if you want to publish somethingin a restricted section, you need to uncheck it from teh Sections panel, go and edit content, then "lock" it again for writing? Seems a lot of work.

And what about other user groups? All governed by the same policy? Or might some groups write to one set of sections, and another user group have access to another set of sections?

You see the sort of issues we run into here when trying to create a tool that is useful to many people in many workflow scenarios? This is why we try and adopt the "least intrusive" and most open architecture, then allow plugins to narrow the scope on a case-by-case basis.

If we can improve the section definition to allow custom flags (or something) then that would enable plugins to use them and interpret them however they see fit. Otherwise, I'm not sure how we could sensibly offer such a feature without making it more difficult to "Just write".

**Comment by cara-tm** [comment]
I well understand your point of view for Textpattern and its "Just write" paradigm.

May be you could offer your plugin above to the community and starting a thread about the opportunity to hide some sections to the dropdown list?

**Comment by Bloke** [comment]
Sure, I can do that. I'll try and polish it up a bit first.

**Comment by petecooper** [comment]
Since this is being outsourced to a spiffy @Bloke plugin, is it safe to close this?

It looks like https://github.com/textpattern/textpattern/issues/1256 is also related to this, but not directly.

**Comment by philwareham** [comment]
Bump! Can this be closed?
