### ISSUE TITLE
Categories list widget (admin side): it is possible to assign a child as parent

### ISSUE THREAD

**Issue by bloatware** [textpattern/textpattern#1211]
### Expected behaviour

Not as above

### Actual behaviour

As above

### Steps to reproduce

Create a category `A`, then `B` child of `A`. On the categories list, check `A` and assign `B` as its parent via "With selected" widget.

**Comment by Bloke** [comment]
Woah! That totally blows up the modified preorder binary tree internals. It appears to have "deleted" the new parent but it's still there, pointing to itself without any means of proper traversal. If you try to create it again, it complains it already exists, even though you can't see it because the orders are fubar.

This must have been a bug since, like, 4.0.7 or something. How the hell do we fix it though? Can't very well remove the parent elements of any checked children, as you might legitimately be moving one group to another.

Only thing I can think of is to trap this in the assignment phase. If it can't do it because it'd make a recursive tree, skip that one and leave it where it was and issue an amber warning listing the one(s) affected?

**Comment by bloatware** [comment]
Yeah, `rebuild_tree_full()` is perplex. I will do some tests and report back.

**Comment by Bloke** [comment]
[Bedtime reading](https://www.sitepoint.com/hierarchical-data-database-2/) :-)

**Comment by bloatware** [comment]
Looks [familiar](https://github.com/textpattern/textpattern/blob/73af040ef640806da6a2061bece11dc4658c225b/textpattern/lib/txplib_db.php#L1264)

**Comment by Bloke** [comment]
Nice! Much closer, and now it doesn't disappear up its own butt any more if you try to make a loop.

One slight possible issue:

1. Create two categories: A, B.
2. Assign B as child of A.
3. Use multi-edit to reassign B back to root (empty select entry).

Expected result: assignment is made.
Actual result:

```
Notice "Undefined index: lft"
in /path/to/textpattern/include/txp_category.php at line 343.

textpattern/include/txp_category.php:343 adminErrorHandler()
textpattern/include/txp_category.php:55 cat_category_multiedit()
textpattern/index.php:252 include()
```

**Comment by bloatware** [comment]
Thanks, should be fixed now. We'd still better fool-proof `rebuild_tree()`, but under normal use it should be ok.

**Comment by Bloke** [comment]
Sorted. Top job, thanks.
