### ISSUE TITLE
[RFC] Feasibility of baked-in notification logging

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1233]
I keep coming back to the potential usefulness of a built-in notification/audit log, and whether having actions & notifications logged internally (as per access logs) would be beneficial.

Seeing who logged in, did what and when has value for administrators of multi-user Textpattern instances, especially within organisation hierarchy where auditing is commonplace.

Useful info:
* author logged in, author published/modified/deleted/etc one or more articles/files/images/comments/etc, IP address

Considerations:
* something less verbose than [smd_prognostics ](https://stefdawson.com/sw/plugins/smd_prognostics)
* carries the same condition at access logs in that it can't be auto-truncated outside of visiting the log
* likely much shorter byte-wise than access logs
* GDPR/privacy implications

What do you reckon? Edge case? Plugin territory?

**Comment by Bloke** [comment]
Interesting. Honestly don't know whether it's a core feature or plugin. We have a Visitors Logs panel, which could become a generic "Logging" panel filterable by 'type' of log action, that includes "visitor log" as one of the types.

Whether we could massage the `txp_log` table to store info not only from external sources but internal too (by making the columns more generic) is something we could explore. Otherwise it'd need a new table.

Off the cuff, it could be done like this:

* A logging API so that all potentially loggable actions can "subscribe" to the logging engine (opt-in, FTW).
* The logging engine runs all the time on every action, but only subscribed log actions are stored.
* An admin-editable preferences area (new 'Logging' group) so you could turn on/off the types of logging (alter, edit, upload, log in, log out, ...). Effectively it turns on/off the subscription method mentioned above. Perhaps a dotted notation like we do for privs is suitable internally?
* Plugins can subscribe to the same model and have their subscription prefs added to the core's 'Logging' prefs group if desired, thus taking advantage of core log behaviour.

Alternatively, subscribers could register their interest in being logged and after the action is completed, any log functions attached to that action are served. This permits custom logging functions to be written, rather like we do with callbacks now.

Gut feeling is plugin, but an audit trail does have value if privacy needs can be balanced well.

**Comment by petecooper** [comment]
>Gut feeling is plugin, but an audit trail does have value if privacy needs can be balanced well.

Yeah, I concur. Thanks very much @Bloke – much appreciated!
