### ISSUE TITLE
Multi-site: Invalid login URL in new user's registration mail 

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#125]
_From [r.wetzlmayr](https://code.google.com/u/r.wetzlmayr/) on August 17, 2011 11:01:30_

send_password() contains a hard-coded login URL. This might be misleading for custom multi-site backend URLs.

See http://forum.textpattern.com/viewtopic.php?id=36699

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=121_

**Comment by philwareham** [comment]
Is this still an issue with the updated v4.6 password handling?

**Comment by Bloke** [comment]
Sadly, the URL endpoints for activation and password reset requests are still hard-coded to have `textpattern/` in them. Would love to find a way round this.

**Comment by philwareham** [comment]
Would a new pref field like 'Textpattern directory path' solve this, or is that too dangerous to,allow (potentially could break the system quite easily I guess)?

**Comment by philwareham** [comment]
Could be a hidden pref maybe?

**Comment by Bloke** [comment]
Maybe. I'd rather find a clever way to determine it, in a similar fashion to the way we sniff the domain in other places.

One potential improvement could be to use `txpath` in the links instead of `hu.textpattern`. The `txpath` variable is only overridden in core if it's not already set (e.g. by setting it in `config.php`). That gives multi-site owners an opportunity to set it up in their `config.php` and have the system use it throughout.

Will investigate.

**Comment by Bloke** [comment]
OK, I tried to get round this, but it's pretty labour intensive. Since it's required to be done prior to even going near the database, the only reliable way is either a setting in `config.php` or to do what I did in my tests and introduce a new `settings.php` file in a known location that contained a variable that indicated the admin-side URL path. By default, if that was missing, it would use `textpattern` (as today) but if you set it to, I dunno, `txp-admin` then all your admin-side URLs would become `example.com/txp-admin/index.php?event=whatever`.

It was a wide-ranging hack, requiring changes to `setup` and both front- and admin-side `index.php`, and `css.php` files, plus changes to the multi-site configuration. Things came unstuck there because it required guessing the URL (which wasn't too bad) and having symlinks to files in folders that we do not know the name of up-front.

Unless multi-site can be refactored / simplified a bit, or we can figure out a way to detect if we're in  a multi-site installation or a regular Txp install, I feel this is going to be a tall order.

My patch is attached to this post in case someone wants to take it and improve upon it. It's a few commits old now, so master will need merging in first.

[movable-admin-directory.patch.zip](https://github.com/textpattern/textpattern/files/206240/movable-admin-directory.patch.zip)

**Comment by petecooper** [comment]
This issue appears to be the sole nontrivial thing holding up the release of 4.6, at least according to https://github.com/textpattern/textpattern/issues/633 - can it be bumped to 4.6.* instead and made non-essential for 4.6.0?

It's a couple of years old, and some fresh attention after 4.6.0 is out may well yield some good results. There's already a _huge_ amount of new stuff in 4.6, can this wait?

**Comment by philwareham** [comment]
Agreed - we can go to a 4.6.x branch - releasing minor point versions can be beneficial to project visibility. Bumping to v4.6.1.

**Comment by Bloke** [comment]
I really have no neat way to solve this. Even if we added:

```(php)
define('txpath', $txpcfg['txpath']);
```

by default to the bottom of `config.php`, or somehow cleverly try to 'sniff' the admin directory, it doesn't solve the problem because we still need to load `config.php` in the first place. So we need to be able to find it, and the only way to do that is if it's in a known location.

One possible solution is to move `config.php` out of the `textpattern` (or `private`) directory and put it in the root. If we did that, our 'known' location is agnostic of the admin side route. It can therefore a) always be found by either of the `index.php` files, and b) have `txpath` defined in it and/or introduce a new `$txpcfg` variable called `admin_dir` that defines the name of your admin folder.

From a security standpoint in a regular install, it's no worse in root as it is inside the admin directory, as they're all web accessible anyway. But for multi-site installs -- the precise situation we're trying to target here and fix the annoying incorrect endpoints that are displayed in setup, email messages, and such like -- putting the `config.php` outside the `private` area completely undermines the entire notion of segregating private (admin) code from public code.

So I dunno how to solve this, beyond doing something daft like in my patch above, that introduces an optional second `settings.php` file in the root directory that only contains one item: the admin side directory name/define statement.

**Comment by philwareham** [comment]
I believe Jakob had a 'works good enough' solution to this issue, which he is going to contribute soon?

**Comment by Bloke** [comment]
Yep, he was going through the pain of merging the year-old code and was going to embark on testing it under various conditions then submit a PR.

**Comment by philwareham** [comment]
FYI a satisfactory solution for this issue is in the [multi-site testing branch](https://github.com/textpattern/textpattern/tree/multi-site-fix) now. Feel free to close once the branch is merged.

**Comment by philwareham** [comment]
Bump? @bloke @jools-r was this resolved?

**Comment by jools-r** [comment]
Yep. Works okay now.

**Comment by philwareham** [comment]
Brilliant. Another one closed! Thanks Jakob.
