### ISSUE TITLE
Retaining PHP 5.3 compatibility

### ISSUE THREAD

**Issue by apmuthu** [textpattern/textpattern#1268]
### Expected behaviour

Only a few files have PHP 5.4 constructs which can be reverted. Class named methods and __construct method clashes in PasswordHash class.

### Actual behaviour

Mainly seen in inability to install TextPattern v4.7.0 rc1

Attached herewith are the diff file and changed files to be able to install under PHP 5.3.x servers as well as removal of the class named method for PasswordHash class.
[TP_PHP53_ChangedFiles.zip](https://github.com/textpattern/textpattern/files/1995973/TP_PHP53_ChangedFiles.zip)

**Comment by apmuthu** [comment]
The DB SQL backup of a typical install of TextPattern v4.7.0 rc1 is attached.
[textpattern_2018-05-11.zip](https://github.com/textpattern/textpattern/files/1995986/textpattern_2018-05-11.zip)

**Comment by apmuthu** [comment]
The `textpattern/textpattern/config.php` file contents in a typical install of Textpattern v4.7.0 rc1:
````
<?php
$txpcfg['db'] = 'textpattern';
$txpcfg['user'] = 'root';
$txpcfg['pass'] = '';
$txpcfg['host'] = 'localhost';
$txpcfg['table_prefix'] = '';
$txpcfg['txpath'] = 'D:\XAMPP\htdocs\projects\textpattern\textpattern';
$txpcfg['dbcharset'] = 'utf8';
?>
````

**Comment by apmuthu** [comment]
Remove [Class named method](https://github.com/textpattern/textpattern/blob/dev/textpattern/lib/PasswordHash.php#L48) in PasswordHash class as it already has a constructor.

**Comment by petecooper** [comment]
I am a strong -1 to reverting to include PHP 5.3 support.

The most recent release of PHP 5.3 was released in August 2014, which at this time is 3 years 8 months ago. The security support period of PHP 5.3 has ended. The final release of PHP 5.6 has security support until the end of 2018 – see http://php.net/supported-versions.php for current details.

If you are running PHP 5.3, you have old and insecure hosting, and you will not be able to use Textpattern 4.7.0. You should investigate alternative web hosting, with newer PHP. Alternatively, Textpattern 4.6.2 will continue to work with PHP 5.3.

**Comment by apmuthu** [comment]
For those who have been using TextPattern in their LAN and in secure environments, merely using PHP 5.4+ constructs does not provide any added security. Let the end user decide on what version they wish to follow and the system can state that the minimum version is 5.3 and the recommended version is say 7.0. Even WordPress uses code in the core to install on systems with PHP 5.2.4 whilst most of their plugins use PHP 5.4+ and can be easily fixed to be PHP 5.3 compatible. Some would like to use composer and accept auto updates to versions that worked and then failed on upgrade.

Those on TextPattern v4.6.2 who inadvertantly upgrade to v4.7.0 when it comes about would be in for a rude shock when the upgrade fails if they are still on say PHP 5.3.3. **Consultants** would then have a hey day raking in the [moolah](https://www.urbandictionary.com/define.php?term=moolah) giving Open Source a bad name.

The [README.md](https://github.com/textpattern/textpattern/blob/dev/README.md) file can be updated to state the minimum and recommended versions of PHP / MySQL rather than hunt for the info everywhere and finally find out only when installing it.

Merely upgrading PHP does not provide for enhanced "Security" and everyone is free to compile it securely to suit their needs. Purposely using syntax specific to later PHP versions run the risk of losing users familiar with the old codebase and not wishing to "[learn new tricks](http://www.dictionary.com/browse/you-can-t-teach-an-old-dog-new-tricks)".

**Comment by Bloke** [comment]
We didn't move to 5.4 simply for security or to be bloody minded, or to follow the crowd. It was to take advantage of some of the language features not present in 5.3. I don't recall now exactly what they were, but we hit a point where it was far simpler and more efficient to do stuff using some built-in features that weren't present in PHP 5.3. Plus, the latest version of the 3rd party library for PHPass (which we didn't want to hack) had function names the same as the class.

In the next version of Txp, we'll probably make the minimum PHP 5.5 because there are some other things in there (such as `array_column()`) which will make our code more efficient still.

We haven't updated any of the supporting documentation on the .com site or the docs site yet because that's misleading for users of the current _stable_ code on 4.6.2. On the day we launch, yes, these will be updated to reflect the minimum server specs, and the info will be in the README.md too (I didn't think anyone read it!)

**Comment by petecooper** [comment]
>Those on TextPattern v4.6.2 who inadvertantly upgrade to v4.7.0 when it comes about would be in for a rude shock when the upgrade fails if they are still on say PHP 5.3.3.

They won't be able to. The upgrade scripts will not run if the PHP version detected is older than the minimum required, at which point they will have to restore from the backup they made at the start of the process. As an aside, anyone updating software -- especially in a live corporate environment -- that cannot spend a few minutes reading release notes, system requirements and `HISTORY.txt` prior to upgrading should be reassessing their workflow, because that's not responsible.

Hypothetically, if Textpattern was to continue support for 5.3, when should it be removed? I understand Perch CMS (commercial) supports the most recent EOL'd version of PHP in a given version, and unless that policy has changed then that removes support for PHP 5.4 and below.

>The README.md file can be updated to state the minimum and recommended versions of PHP / MySQL rather than hunt for the info everywhere and finally find out only when installing it.

The `README.md` links to the Textpattern website already, and it's also in [pophelp](https://github.com/textpattern/pophelp/blob/master/help/en_pophelp.xml#L312) and the docs site. A search for `textpattern system requirements` will show it in the first or second link typically, and that's the current _stable_ version (which is 4.6.2 as I write this).

With respect, this isn't a personal vendetta against you @apmuthu – it's not my decision to remove PHP 5.3 support, but if these things never change then we're not moving forward. And if we're not moving forward, then we're doing this wrong.

**Comment by apmuthu** [comment]
Thanks for the various points of view.
[array_columns()](https://www.w3schools.com/php/func_array_column.asp) are awesome indeed.
Certainly, maintaining several PHP version codebases is not tenable.
Keeping the code as universal as is possible will make it PHP version agnostic at the cost of some loss in efficiency / coding elegance.
Small footprint virtual / physical machines running on WinXP/Win2K/Win98/Deb Squeeze using XAMPP 1.7.3/7 is what I had in mind for offline usage and development when I suggested retaining PHP 5.3. It was when the install error-ed out when setting up Txp v4.7.0rc1 that I had to hack my way through.
The PHP 5.4 usage hitherto in use that I've seen here actually makes for saving codelines at the cost of unfamiliarity for a while.

What are the other places that PHP 5.4 has been leveraged here to be efficient?

**Comment by Bloke** [comment]
> What are the other places that PHP 5.4 has been leveraged here to be efficient?

Honestly can't remember, sorry. But I recall we hit _something_ and it made more sense to increase the version than it did to work around it on 5.3.x. It might have been Textile. PHPass may have been another.

**Comment by apmuthu** [comment]
**Array_column()** [recommended implementation](https://github.com/ramsey/array_column/blob/master/src/array_column.php)

**Comment by philwareham** [comment]
Thanks for the discussions, interesting stuff. However I think we should stick to the PHP 5.4 minimum as planned. And as I mentioned we are targeting 5.5 for the next major release so this is a iterative step  towards that requirement. Closing, but @apmuthu feel free to stay involved for future project stuff.
