### ISSUE TITLE
Language chooser on sign in screen

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1288]
### Is your feature request related to a problem?

Yes, partially. Mostly a UX proposal.

### What is the feature?

Offer a language/Textpack selection dropdown on the sign in screen.

The site's language and user(s) languages can be set to different values. Before a user signs in, the UI language is set to the site's language. For multilingual sites this is not smooth UX, especially where the user is not familiar with the login screen layout.

Proposal: if security and practically concerns allow, offer a language switcher for admin-side, unauthenticated users, perhaps by way of a flag or similar non-word icon, and a dropdown menu of  the activated language names (in the localised string) for the user to select from.

**Comment by Bloke** [comment]
I like this. It is a bit jarring when you log out of a site with per-user language set to English, for example, and the login screen shows it in the site language instead. But since the per-user language is only a pref, without a username we have no alternative at present. Options:

* Also store per-user language as a cookie and use that if not logged in.
* Also store per-user language as a localStorage object and use that if not logged in.
* Offer a dropdown, or at least some kind of clickable indicator of the current language with the ability to alter it, on the login screen as per this request. Maybe default the selected language to the one stored in a cookie/localStorage object?

The fallback in the absence of any of the above would be the site language, as now.

Which way is best to jump...?

**Comment by petecooper** [comment]
Thanks @Bloke. FWIW, I'd be inclined to stick with the third bullet (dropdown) as new browsers, cookie-less setups and non-technical users would find this the least challenging.

**Comment by Bloke** [comment]
Agreed. Though I think a cookie-less environment would mean you couldn't use the admin-side without re-logging in every page nav. Can't recall if it uses the session, and only stores the login cookie token if you check the 'remember' box or not.

@philwareham If we were to put a language switcher on the login page, where would it go?

Then there's also the UX consideration: if you set the language outside Txp and log in, does it switch and store your per-user language to the chosen language too, overriding what you may have previously chosen when last logged in? I'd be inclined to say yes, but what does everyone else think?

**Comment by petecooper** [comment]
>cookie-less
I should be more specific: I have a small handful of corporate clients who clear cookies after every session as part of their internal security and GDPR stuff, a bit like -porn- incognito mode on some browsers, so there's no record of any previous sessions each time. While the user is logged in, no worries, but closing the browser zaps the history and cookies, presumably including localStorage items.

**Comment by petecooper** [comment]
>I mean, changing language on the login screen, regardless of your previous preference settings, should probably carry through to the rest of the UI, right?

…which perhaps begs the inevitable question: should _any_ user of any grade be able to install their preferred language from the distributed .txt files? I'm deliberately excluding the ability to install from the Textpack textarea to minimise the attack surface. It would certainly reduce the number of support requests and administrivia heading up the chain of command, especially with distributed teams requiring different languages.

And there's also the consideration that the easier we make language selection, the more likely people are to use it, and the more interests in translations we'll get. Tenuous, but a small factor.

**Comment by Bloke** [comment]
Coming back to this, I'm proposing this is the workflow we adopt:

* Show a language chooser on the login page _if_ there's more than one language installed. When altered, refresh the page to render the login panel in this language. @philwareham to figure out where to put this input control, and whether it's auto-submit (UX/accessibility?) or has a definite 'Go' button. We may be able to use the render method in the Lang class for this (the same method we use to render the admin language switcher on the Languages panel) but it might need tweaking to remove the label or add an action button or alter the event/step or something.
* When logging in, set the per-user admin language to the language chosen from the login panel, regardless of what was set in the now-logged-in user's preference beforehand. If no value is present (i.e. already logged in) continue to use the per-user pref and/or fallback on site language.
* When switching language, or setting the language programmatically, set a cookie/localStorage object that contains the current in-use admin language. In other words, when logging in from a language-aware login screen OR visiting the Languages panel and changing your admin-side language will trigger generation of this browser-based preference. If we're lucky, this can be done once in the 'set language' method but it might be spread throughout the code in a few places.
* After logout - when the user is not known to the system - render the login page (and set the default option in the language dropdown there) with the language designated in the cookie/localStorage object, if available. Otherwise, default (perhaps) to the browser's indicated [accept-language](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language) header or fallback on site language as we do now.
* If there's only one language installed, introduce a hidden form element on the login page set to this value so the cookie/localStorage object can be set on login, for consistency.

I think that covers everything. Holler if you disagree or think there's a better workflow.

**Comment by petecooper** [comment]
@Bloke - that sounds fine to me. The only thing I keep coming back to is the risk/reward of having either an 'install all Textpacks' button for when an admin doesn't know or care what languages their users will have and just wants to offer them, or perhaps if a user logs in and their preferred language isn't available then they could install their own language.

Use case is someone who has English as an additional language, and them being multilingual lends itself to them wanting numerous languages available, either from a familiarity angle or perhaps wanting to stay sharp or whatever. Also less jarring if they're writing in the same language as the UI.

Are there performance considerations when _all_ the Textpacks are loaded? From a size point of view, there's about 5MB difference from just `en` and All The Textpacks when the database is exported.

**Comment by Bloke** [comment]
> the risk/reward of having either an 'install all Textpacks' button

I've never tried installing them all. In theory, performance should not be impacted as it just takes up space in your database: only the current in-use language pack is ever extracted and used on any one page load.

It would take a while to install the lot, though - between 2-5 seconds per language depending on hardware, I expect - so we might hit page timeout limits if we did it in a conventional request. Ajax might be better if possible.

> perhaps if a user logs in and their preferred language isn't available then they could install their own language

It's technically possible to open up the languages panel to anyone if we separate the actions - install and remove - in privs so that only Admins can delete langs. I think we shied away from this in the past and I can't remember the reasons. But now packs are served locally and it's working well, we could revisit this and see whether the risk/reward is acceptable.

In terms of offering a selector on the login screen, we could put it here for example:

![LoginLanguage](https://user-images.githubusercontent.com/21252/54355910-37445b00-4652-11e9-928f-491dad625c94.png)

though I'm not sure if that's a bit odd alongside the 'forgot password' link. Thoughts, @philwareham ?

**Comment by philwareham** [comment]
I would restrict any language chooser to the actual languages that are already installed via the admin area - no 'install all, or install an additional' feature here at all.

And only show the dropdown *if* more than a single language is installed. I'd not want to see it at all in a single language site.

**Comment by Bloke** [comment]
Sure, they're both given. You can't offer languages in ones that aren't in the database because there's nothing for Textpattern to load. We never fetch strings directly from disk except during installation. So if there's only one lang installed, we can make no chooser appear.

Just wondering about the placement of such a chooser if we added it.

**Comment by philwareham** [comment]
Ta-dah!

![Screenshot](https://user-images.githubusercontent.com/413665/54358614-b3da3800-4658-11e9-8095-cf8de3adbba6.png)

HTML guidance here: https://github.com/philwareham/textpattern-hive-admin-theme/commit/c1efbf8dbe5ef4d49563c75aa581b9f6b2f4bc3a#diff-e4d1b3a3c5c8127a859a3d4f99449a88

**Comment by philwareham** [comment]
I can't see the value of an 'Install all' button in admin languages. Who is going to want all ~50 languages installed realistically?

**Comment by Bloke** [comment]
I kind of concur. I can see the value for time-pushed admins like Pete mentions, but I'm not sure many sites are going to have that wide a user base that they'll just install the lot. Plus it's a lot of hassle code-wise.

I'm open to the idea of allowing some lower-level users (which priv levels?) to install their own languages though, one by one like now. Essentially open up the permissions so that `lang.install` and `lang.delete` become available and we can assign them accordingly, hiding the deletion ability from all but 1+2 priv-level users.

I don't think that's too much of a risk. Anyone else?

**Comment by petecooper** [comment]
OP is solved in the strictest sense (thanks very much @philwareham), and…

>I'm open to the idea of allowing some lower-level users (which priv levels?) to install their own languages though, one by one like now.

…is probably more appropriate under the privileges revisiting in https://github.com/textpattern/textpattern/issues/1209

Gonna close this unless anyone fancies a scrappy fight over it.

**Comment by Bloke** [comment]
Well, this could stay open as a placeholder for the lang dropdown on the login panel.

**Comment by Bloke** [comment]
Just a UX concern here. Say we implement it as per Phil's screenshot. If the whole point of doing this is so that the login panel can be rendered in the user's home language from those available (if available), we could argue that the act of choosing a language ought to refresh the page immediately so the fields are all localised.

But as it's the third item in the list, if you enter your login credentials and then choose a language, it'll refresh the page and you'll lose what you typed.

So how should we proceed?

**Comment by philwareham** [comment]
Sorry, my understanding was that this was for the following UX case:

1. Admin user has installed Textpattern, with their preferred language plus one or more additional languages that potential site users are likely to want.
2. Admin user creates/invites a new user.
3. New user goes to login screen - login screen is in admin users language as default.
4. New user selects their own language preference and logins in (previously new user would have to log in, navigate the admin panel in non-familiar language, then select their own language if they can find it.

Of course, in addition to the chooser on the login page, if an admin can invite a new user in the new user's preferred language already then this login chooser is somewhat negated (but still handy to have IMO). That would be the best UX.

**Comment by Bloke** [comment]
Yeah, that would work and is definitely the main intended use; as a login selector to avoid having to navigate the UI once logged in.

As you say, allowing an admin to set a user's preferred language up-front on User creation offers an even greater benefit. If the login panel can take a language param which overrides any language cookie/localStorage object in play, then great. We don't even need to store the preferred language on creation - just use whichever lang is chosen on the _Admin->Users->Add User_ panel and inject it into the login URL we put in the email:

"You've been registered as a contributor to Textpattern, visit https://example.org/textpattern?lang=fr to set a password and log in."

Then even the initial set password process can be localised. And if we pass the lang forward at each step, when they eventually get to the login page, it'll still be rendered in the chosen language, and the dropdown selector could be pre-populated with this value so that, on successful login, we set their `user_language` preference accordingly.

Once that's done, it sets a cookie which can then be used on the login page when there _isn't_ a `lang` param passed in the URL. Thus if there isn't one, it looks for the cookie and sets the dropdown AND user language strings on the login panel to the nominated language. And if neither are present, you get site default, as we do now.

So if we assume at every step of the process that altering the language dropdown on the login panel is _your intended language_ once you log in, that's fine. I like that.

For existing users, when they visit the admin side on upgrade, we'll store their `user_language` as a cookie so that when they log out, the Login panel can be rendered in their chosen language based on the cookie value.

The only situation that's not covered then is if an admin has chosen the wrong language when creating the user account. The receipient will not be able to change the language of the UI elements on the login panel _unless_ they tinker with the URL and add `?lang=some-identifier` there. Is that an acceptable trade-off to bring this Issue to fruition? Or do we need to find a way to allow people to choose the language of the Login panel directly via some user interface element?

**Comment by petecooper** [comment]
Done. Thanks @Bloke!

**Comment by philwareham** [comment]
Needs to be pulled into dev branch as well.

**Comment by Bloke** [comment]
I'll merge this into dev once we're happy it's working okay in the 4.8.2 branch.

**Comment by petecooper** [comment]
Is merged. Am closing.
