### ISSUE TITLE
Allow option to not send login details on new author creation

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1295]
### Is your feature request related to a problem?

Yes, but localised to me.

### What is the feature?

Permit the option to create a new author in the UI, but not send *any* notification via email.

Currently, a new author is auto-emailed with their login credentials when the account is created. A form email is despatched with some details. If email is not available, then an "Email not sent" error is thrown. Activation link doesn't get sent or clicked, and account is in limbo.

**Comment by petecooper** [comment]
>Or do you mean you could set the account up, not send the email then, and issue a password-reset/password-activation event on the account at a later date to send the token out?

Exactly this. I'm building a site at the moment where the authors are pre-filled, but the site is in dev, and so the email isn't sending…hence, limbo.

Related: should a Publisher be able to force-change the password of a user that hasn't received (or clicked) the auth link, and then resend the auth link?

**Comment by Bloke** [comment]
Gotcha.

> should a Publisher be able to force-change the password of a user that hasn't received (or clicked) the auth link, and then resend the auth link

They shouldn't be able to _set_ an arbitrary password of course. But they can resend a token which allows the user to do so. And the act of doing so invalidates any previous tokens. Once the user has changed their password or the token expires, all previous attempts to use any old tokens will fail.

IIRC, if the account has never been used then an activation email is sent. Otherwise a password reset link is sent. Exactly the same animal under the hood, just a different message body.

**Comment by Bloke** [comment]
Yes, probably. I'll amend that, thanks.

**Comment by petecooper** [comment]
Throw a 4.8 milestone on for now and toss on the back burner, or too edgeCasey©?

**Comment by petecooper** [comment]
I've been thinking about this and I'm going to close it - given an MTA is a requirement, and we have a way to create users without triggering a password send (SQL), the work involved with this could be more useful elsewhere.
