### ISSUE TITLE
Check for availability of required & optional PHP functionality in Diagnostics

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1309]
### Is your feature request related to a problem?

Yes, but not with me.

### What is the feature?

I have a gut feeling / theory that some of the `problem_connecting_to_update_server` issues might be down to a missing PHP JSON extension which is not always included in all PHP packages across all operating systems.

In the past, I've had issues myself on new installations where the installer won't continue because an extension is missing (XML, from vague memory) and throws an error. This prompts me to make sure all the required and optional extensions are installed, and installation can continue.

On upgrades, the installer doesn't need to run -- it's an upgrade script that runs, not an installer. An in-place upgrade might function perfectly well without a given extension (i.e. JSON), but when the Diagnostics are accessed, the `json_decode` might not be possible if the extension isn't there.

If a site works 100% fine, and the user decides to switch PHP versions (e.g. 5.6 to 7.2) because of whatever reason, the new version of PHP might not have that extension, and hence the JSON stuff can't happen. A preflight check that passed previously would now fail.

So, my proposal: check for the existence of each required and optional PHP extension in the Diagnostics output, effectively do a readiness check.

**Comment by Bloke** [comment]
Likety like.

Presumably, PHP has "is_extension xyz available" capability? Not really checked. Or, reading .ini variables or something to see if something's on or off or available.

Failing that, we can always fall back on the 'feature-detect' paradigm:

```
try {
   some_command_that_might_not_exist();
   // Yay! Worked.
} catch() {
   // Damn, missing. Skip it or report, as necessary.
}
```

**Comment by petecooper** [comment]
I'm not a coder, as you know, but with my bodger hat on I would run `php -m | grep xml` and see what that spits out.

Alternatively, this might work (from http://php.net/manual/en/function.extension-loaded.php):

```
<?php
if (!extension_loaded('gd')) {
    if (!dl('gd.so')) {
        exit;
    }
}
?>
```

**Comment by petecooper** [comment]
For completeness, current PHP requirements and nice-to-haves:

>PHP extensions (included by default in most PHP installations):
mysqli
XML
JSON

>Optional PHP extensions:
mbstring
zlib

**Comment by petecooper** [comment]
Possibly related: `mod_security` can restrict remote JSON calls.

If Diagnostics can provide a Y/N on whether it's loaded, that could then equip the user with enough knowledge to contact their host and request a rule exemption.

**Comment by petecooper** [comment]
Should we have a check for PHP extensions as part of the preflight check? See above re: changes to PHP version after the initial installation has successfully completed.

There's value in having a dump of loaded PHP extensions in verbose diags mode, and perhaps a Y/N for required & optional extensions in normal diags, but should it be more front-and-centre if a _required_ thing isn't present?

**Comment by Bloke** [comment]
> would it be best code-wise to have a) a single-purpose function to check for a required extension (1x function for 1x extension, rinse and repeat), or b) a function to check for all required extensions, or c) something else?

I'd shy away from (a) as it introduces repetition and we're moving as much towards DRY coding as we can. (b) would work and is nice and encapsulated but if you want to maintain a central list of 'required' things, then you have to hunt for the function to find the list of extensions that are available. General rule of thumb is to try and put any such "constants" either in our `constants.php` file or at the top of the file in which they are used, then refer to them in code later.

So that leaves option (c) as either:

* A general-purpose function that reads the list of known-good extensions from some well-known location (constants file or, in this case, probably better at the top of `diagnostics.php`).
* Same as above, but the function can accept additional extensions as an argument (or takes an argument that replaces the default set of extensions).
* Same as above, but the function expects a list/array of extensions to be passed and it's up to the calling environment to pass them in - e.g. by passing in the well-known constant.

Which one you use is a matter of finding the one that produces the most efficient, most logical and least head-scratching code for future maintainability. When the admin panels eventually move to class-based widgets and things like that, any such functions introduced now will likely become methods of the panel's class.

**Comment by petecooper** [comment]
For info: just encountered a site where `mail()` was disabled via `php.ini`. Cheap hosting, PHP locked down with: `disable_functions = phpinfo, system, mail, exec`.

**Comment by petecooper** [comment]
Adding the (PHP 5-era) Magento preflight check in case it's any use to crib from.

[magento-check.zip](https://github.com/textpattern/textpattern/files/11121066/magento-check.zip)

**Comment by petecooper** [comment]
Nice one @Bloke - thank you very much!

**Comment by Bloke** [comment]
You're welcome. Only took me 4.5 years to finish it, as well :)

**Comment by petecooper** [comment]
Send me a bill…
