### ISSUE TITLE
Theme panel deletion stumbles on author-created subdirectories

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1319]
### Expected behaviour

Themes panel deletion should take care of theme author-created subdirectories.

### Actual behaviour

Themes panel deletion appears to choke on the deletion of theme author-provided subdirectories.

### Steps to reproduce

* add a theme with a subdirectory of a standard issue directory (e.g. `/styles/fonts`)
* ensure web server user has rights to delete the files
* delete the theme, and delete the files from disk
* note the success + warning alert

#### Additional information

Textpattern version: 4.7.1

Screencast attached (no sound, I'm tired and words are hard).

In the example provided, web server runs as `www-data`, which is in a group called `www-data`. The `pete` account is also in `www-data`, hence I can upload and delete etc. I used Terminal to change ownership and file permissions, which permit the web server to delete the whole theme.

The issue seems to stem from my extra `fonts` directory inside `styles` – which perhaps isn't permitted, I don't know for certain – file permissions don't appear to be a problem.

Possible solutions: either permit the deletion of subdirectories inside the standard theme structures, or add something to the docs explaining that _only_ the standard directories can be used for themes.

[subdir.mp4.zip](https://github.com/textpattern/textpattern/files/2259698/subdir.mp4.zip)

Tangentially connected to https://github.com/textpattern/textpattern/issues/1248

**Comment by Bloke** [comment]
This is kind of by design. We took the decision that:

* A theme at present is only Pages, Forms ad Styles + manifest.
* Any custom-provided content would NOT be deleted in case you'd spent time making up folders of theme images, JavaScript or any other third-party content that you wanted to distribute with your theme.

The thinking behind it was that if you'd spent time creating additional content outside of Txp channels, it's not right for Txp to stomp on your work, so it only removes stuff it _understands_ as core theme functionality.

But to warn you of the fact it hasn't completely removed everything, it issues an amber alert so you go check it out manually and can remove it through other channels if you really don't want it..

Is this the right decision? Not sure. Yes, on some levels to avoid nasty surprises for theme authors. No on others, perhaps for theme consumers.

Can we have a second level checkbox like 'Delete all assets including anything you may have also added'? Perhaps. But then in the next version we might have extended Txp Themes to include more file types, as alluded to in #1248 so we may then feel justified in deleting any such assets. That still won't necessarily remove files and images from the theme folder, though.

Not entirely sure the best way to move forward here. Options welcome.

**Comment by petecooper** [comment]
Thanks again @Bloke - good points well made, and now I understand. As-designed, will close. I will update theme docs to indicate the as-designed-ness.
