### ISSUE TITLE
Offer two factor authentication

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1320]
### Is your feature request related to a problem?

For added security, should we offer the use of two factor authentication when logging in?

### What is the feature?

There a plenty of PHP solutions for this, for example: https://github.com/RobThree/TwoFactorAuth

**Comment by Bloke** [comment]
Without delving into it ore deeply, my gut feeling would be against this, sorry.

Anyone who's read my blog posts on it knows my stance on this already. But I won't let my personal views stand in the way of introducing it if there's a solid argument for it.

Thus I'm genuinely curious what introducing it into Txp will do for us (besides adding a buzzword to the list of features) especially in the following situations:

1. When your email program/SMS service and browser are on the same device.
2. When you don't own a device with a QR scanner.
3. When you log into Txp on your mobile.

Assuming you've managed to jump through the hoops to establish a (second) secret besides the password, and we've stashed it with the user record, please run me through how it works when you log in. And if you log into Txp on your mobile, how does having 2FA enabled make it harder for someone who swipes the phone out of your hands while you're using it to log into Txp? Is the challenge sent to an email address?

I'm not being facetious here, I'm genuinely interested in how this makes the login process more secure than a single 25+ character pass code typed in every time. And how does 2FA interact with the auto-login cookie mechanism? Does it make it redundant because of the need to issue a challenge every time? Or does the cookie provide the first factor automatically and then you have to supply the second? Which begs the question... isn't that 1FA if you have cookies enabled?

I just can't fathom how the examples or the demo linked in the OP would fit into the Txp login process. I'm probably just being dim, so please humour me!

**Comment by philwareham** [comment]
OK, all seems like fair points. It was just to start the discussion really. If you feel the security would not improve I'm happy to close.
