### ISSUE TITLE
Weird UI issue with Firefox 61 on W7

### ISSUE THREAD

**Issue by bloatware** [textpattern/textpattern#1324]
When I log in, the main core tabs (Content etc) are not left/right clickable until I click somewhere else. Funnily, Extensions tab is clickable.

#### Additional information

Textpattern version: 4.7.2-dev, Hive theme, Firefox 61.0.1 on W7.

**Comment by philwareham** [comment]
Tested in Firefox Dev Edition 62b14 on my Mac and can't reproduce this - all works fine on log in and caking the nav bar items. Can someone else on a PC try and replicate this issue so we can confirm it's not an isolated issue? Thanks.

**Comment by petecooper** [comment]
I'll have a look, I have a Windows 7 Pro VM I can update and test - give me 30 mins.

**Comment by petecooper** [comment]
Cannot reproduce. Fresh W7SP1/FF61.0.1 x64, 4.7.2-dev via the dev-demo, nothing untoward - mouse clicks working as expected.

I'm guessing that a plugin is possibly the culprit here, since Extensions is not shown in vanilla installs.

[ff61.mp4.zip](https://github.com/textpattern/textpattern/files/2265802/ff61.mp4.zip)

**Comment by bloatware** [comment]
It looks like a browsers quirk: the "Would you like Firefox to save this password..." popup was transparent for some reason, but still present and prevented focus on these tabs. Crazy!
