### ISSUE TITLE
Login page enhancement

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1342]
### Is your feature request related to a problem?

No. Just a UI enhancement.

### What is the feature?

For the login page, as any of other tools, TXP 4.8 could be an opportunity to add a "show/hidde" icon and a password visualisator feature.
Other thing to consider: the ability to accept either a name or an email address as a user identifer.

**Comment by Bloke** [comment]
I'm on the fence.

1) Show/hide is traditionally only for when you are _creating_ passwords so you can verify you are making it right (which then means we don't need a second verify box). But I admit that sometimes it might be nice to see what you typed when logging in, especially when using long passwords, so this might be a consideration.

2) Currently, the email address is not a unique field, but `name` is. Thus you can create different users and have the same email (I do this a lot during development, btw, for testing user priv levels). We'd have to make the email field unique to permit this, which is a backwards-incompatible change.

You can actually use email addresses as login names now, you just need to encourage users to supply them when the account is created and put them in the 'name' field. Not ideal, of course!

**Comment by cara-tm** [comment]
Ok.

**Comment by petecooper** [comment]
Also, there are some browser extensions/plugins to achieve this - perhaps defer to third-party solutions?

**Comment by philwareham** [comment]
As password managers are pretty prevalent now (indeed macOS has one built in last couple of releases - and of course 1password is awesome for mobile and desktop) I don't see a great need to change the login panel functionality.

**Comment by cara-tm** [comment]
Okay no worries.
What about to add/restaure a link to the front-end within the login page as used into the "Dark Space" admin theme?

**Comment by phiw13** [comment]
> As password managers are pretty prevalent now (indeed macOS has one built in last couple of releases - and of course 1password is awesome for mobile and desktop) I don't see a great need to change the login panel functionality.

(nitpicking - MacOS has had the Keychain password manager like forever 10.2? I think, and iCloud keychain since 10.7, to share passwords with iOS devices etc. Firefox has a password manager since 1.0, I think. Note: memory, holes, etc)

Time would be better spent to make sure the login panel, and password **creation** fields (setup / password reset) play nice with password managers, including their ability to create strong passwords for the user. See for example this [forum thread](https://forum.textpattern.io/viewtopic.php?id=48791) for Apple’s recent additions, supported by 1Password, and possibly others, and discussed in some WhatWG Github thread.

@cara-tm -  yes, that is one of the things that I miss in Hive.

**Comment by philwareham** [comment]
Site link is now in login panel, as are the improvements for password management. Closing, thanks.
