### ISSUE TITLE
Official Composer support for plugins and themes install

### ISSUE THREAD

**Issue by NicolasGraph** [textpattern/textpattern#1343]
### Is your feature request related to a problem?

Kind of; @Gocom does not maintain its Textpattern related repos anymore making the Composer support obsolete on Txp 4.7+.

### What is the feature?

As discuused [here](https://forum.textpattern.io/viewtopic.php?pid=313549#p313549), could the [installer](https://github.com/gocom/textpattern-installer)/[lock](https://github.com/gocom/textpattern-lock) couple be officially adopted and maintained?

Note: I would also like to see [MassPlugCompiler](https://github.com/gocom/MassPlugCompiler) promoted one day; it really makes plugin developpment and compilation handy by allowing to complile multiple source files (a new plugin template could be created as a filetree from there).

**Comment by philwareham** [comment]
I've forked the two repos here...

https://github.com/textpattern/textpattern-composer-installer
https://github.com/textpattern/textpattern-composer-lock

...and created a pull request for Gocom to update lock and release a new version.

If no response within a week I'll assume these repos are now unmaintained and adopt them (with suitable credit to original author). We would need to register them with different names at Packagist as the original names are owned by the author (hence why I have put 'composer' into the repo names of our forked versions).

**Comment by NicolasGraph** [comment]
Can we expect to see the two repos adopted next week?

**Comment by philwareham** [comment]
Yes, or later today if I get all my other work done.

**Comment by philwareham** [comment]
Hi @NicolasGraph - I've started work on adopting these. You will need to amend your composer.json requires from:

    textpattern/lock
    textpattern/installer

To:

    textpattern/composer-lock
    textpattern/composer-installer

Because I don't have access to the original names via Packagist (Gocom has those).

The installer needs modernising and fixing in a few places but it *seems* to be working on  basic level in my very limited testing here. Things like public theme installation at the very least needs to be amended for Textpattern 4.7 onwards. If you'd like access to the repo to help out that would be good - as I'm not a PHP dev - although I do use Composer sometimes.

**Comment by NicolasGraph** [comment]
Hi @philwareham - Thanks for adopting these, I will take a look at the theme installer ; probably not this week, but the next one should be ok.

**Comment by philwareham** [comment]
@NicolasGraph OK, great. I've added you as a collaborator on both those repos (installer and lock) so you can commit directly to them without needing to fork.

I'll help out where I can.

I'll close this issue now - any new issues can be created directly in those repos.
