### ISSUE TITLE
Pref `switch_dev_live` propose rename to `enable_switch_dev_live`

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1362]
### Expected behaviour

To avoid use of duplicate name (and empty text string) the pref `switch_dev_live` should be renamed - suggest to `enable_switch_dev_live`.

### Actual behaviour

The pref tries to use the text string `switch_dev_live` which is reserved for use in section panel only - so it display raw text string. Simply moving that text string to common (global) scope doesn't really suffice as the pref needs a more descriptive text anyway.

#### Additional information

Textpattern version: 4.7.2-dev

**Comment by bloatware** [comment]
Good point, this pref is actually more than `switch_dev_live`. Ok if we call it `enable_dev_preview`? That's what it does, anyway.

**Comment by philwareham** [comment]
Seems good - I'll update the Textpacks when this lands. Slightly off topic, but maybe same goes for enabling/disabling `Advanced options` pref - a unique text string name would be handy?

**Comment by bloatware** [comment]
Before I commit: should we still use on/off or rather yes/no radios for `enable_dev_preview`? Depends on its translation (`Developer preview` or `Enable developer preview`) I guess.

Not sure for a new pref for `Advanced options` - it's only used on prefs tab atm.

**Comment by philwareham** [comment]
I think 'Enable ... ?' wording and a yes/no button are the right choice.

What do you envisage going into the Advanced options eventually? I can see things like a web hook URL code for injecting theme files from disk to database in there, for example.

**Comment by bloatware** [comment]
The general idea is to put in `Advanced options` everything that

- optional
- extends core possibilities
- has no predefined values
- requires some caution/knowledge

An example is `ini`-formatted custom form type definitions array. If one day (unlimited custom fields?) we create a cleaner interface for custom definitions, it could migrate there.

Another example could be a list of functions (i.e. `preg_replace`) available in `<txp:evaluate />` tag or `escape` attribute. Web hooks URL might go there too, since it's a sensible parameter.

**Comment by philwareham** [comment]
Thanks Oleg - done and closing.
