### ISSUE TITLE
Localised pophelps - empty strings don't use English fallback

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1364]
### Expected behaviour

For non-English pophelp files, if there is not a translation of the string available, it should revert to the English `en` fallback text. As we already do for Textpack strings.

### Actual behaviour

I've just uploaded the start of the French pophelp file taken from the setup I have just configured at Crowdin (now that out pophelp is in a stable position). Lowel has very kindly translated around half of the help strings so far and I've brought that into the Textpattern core.

On testing, all translated help texts display fine, however any empty strings just have blank help windows.

### Steps to reproduce

Use latest dev branch, where you'll see the French pophelp file in the `lang` directory. Note how the XML is formatted when there are empty strings (this is how it exports from Crowdin). Click on a pophelp that hasn't been translated (i.e. one in the preferences panel).

#### Additional information

Textpattern version: latest dev branch.

**Comment by Bloke** [comment]
Hmmm, the way this is currently built doesn't lend itself to fallback easily:

* If the desired file is entirely missing, it loads the one from the default language - tries twice for reasons I haven't yet fathomed.
* If the desired file exists, it loads the entire file into an XML structure and then hunts for the desired item.
* Any failure to find an item will result in pophelp_missing being thrown.
* If it finds the item, it displays it.
* If it finds the item and it's empty, it still displays it (i.e. displays nothing).

What we kind of need to do is...

### Option 1

1. Load both desired lang file and fallback file (if the langs differ).
2. Try to locate item as above. If it fails, switch to the fallback and hunt for it there.
3. If that fails, or returns empty content, show pophelp_missing.

### Option 2

1. Load both desired lang file and fallback file (if the langs differ).
2. Merge the contents of the structures such that the fallback is the baseline and the desired language replaces nodes with any strings in the target language.
3. Continue as it does now - fallback will be automatic.

I think Option 2 is probably more elegant, but may be overkill, especially since this isn't cached in any way - every request does the same process. Option 1 is simpler at the expense of having both structures in memory (but then it has to load them both into memory first to merge them anyway). And merging structures might be processor intensive anyway for little gain.

I'm going to go with Option 1 but if anyone can think of a neater way of approaching this, then by all means we can undo/tweak it later.

**Comment by Bloke** [comment]
Option 1 works well in local testing and falls back nicely. The only issue is the following, but I'm not sure I care:

1) In `config.php`, set your `TEXTPATTERN_DEFAULT_LANG` to a language that has no pophelp file.
2) Set your admin language to something that does have a (semi-)translated pophelp file.
3) Visit Write panel, or any panel except Prefs: pophelps available if in admin lang file and not otherwise (as expected).
4) Visit Prefs panel: pophelps not available at all.

This is because the prefs panel works slightly differently. It *only* looks in the default lang file for the keys to use. That determines what topics it displays, then regular pophelp processing takes over with whatever it has figured out.

This isn't usually a problem, because the assumption is that you'd choose your default site language as one that is fully populated. It's only a problem if you break that assumption.

Do we care? Do we work around this and make the prefs panel try the admin language file first for keys, then fill in the gaps if it can? Or do we just ignore this problem and, if you choose a default language that is only partially or not translated, it's your funeral?

**Comment by philwareham** [comment]
Can we have `en` Pophelp as the default fallback? It's guaranteed to be fully populated at all times.

**Comment by Bloke** [comment]
Sure, but it kind of tramples on the notion of permitting people to set their own default fallback in `config.php`.

**Comment by Bloke** [comment]
Yep, we preset the fallback to `en` but you're free to override that if you so desire. And in that case, the Prefs panel currently shows no pophelp topics if you choose a language that has no pophelp file as your site default.

I honestly can't see anyone doing that for any sane reason, so I'm tempted to live with it as-is rather than try to code around a situation that probably won't arise, but if I've missed something then by all means we can see what can be done about it.

**Comment by philwareham** [comment]
Yeah, that's fine. Don't worry about it!

**Comment by philwareham** [comment]
Did you see this one too? Not sure what it is but since you are the languages guru maybe you can decipher it: https://github.com/textpattern/textpattern/issues/1328

**Comment by philwareham** [comment]
I'm just testing locally using latest code and I'm still getting missing pophelps when a partially translated pophelp language it used (it's working as expected now for all other scenarios). This is because sometimes an XML item *is* defined in the localised Textpack but the content is empty (basically, the title attribute has been translated by author in Crowdin but the author hasn't written the body content yet for the help item). For example:

        <item id="custom_form_types" title="Modèles types de modules personnalisés"><![CDATA[]]></item>

To test, with current 4.7-dev build:

1. Select language as French as the user language.
2. Go to preferences, advanced, and click on the `custom_form_types` pref’s pophelp.
3. You'll see `pophelp_missing: custom_form_types`

Since I don't have control over what is exported from Crowdin (without manually deleting all empty pophelp XML items) we probably need to test for this scenario and also fallback to default.

So, check if item content is just `<![CDATA[]]>` and deal with accordingly.

Sorryfor the extra work needed, but it's best to catch this I think.

**Comment by Bloke** [comment]
Like that?

**Comment by philwareham** [comment]
```
awesome="impressionnant"
```

😀
