### ISSUE TITLE
Locale strings extension for front-end

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1374]
### Is your feature request related to a problem?

No.

### What is the feature?

Considering add a few strings into the language packages for front-end conveniences to use with the `<txp:text item />` tag (i.e. "*Read more*", "*Search here...*" and so on: kind of common  strings read on websites).

**Comment by philwareham** [comment]
Yes this is something I have bumped up against when writing my first theme for Textpattern.

In the long term, we should offer a way of themes having their own language packs. Possibly as part of the package, i.e.:

```
themes
  - mytheme
    - forms
    - lang
      - ar.ini
      - en.ini
      - en-gb.ini
      - fr.ini
    - pages
    - sections
    - styles
```

But for now, a handful of extra common language phrases used on public websites is definitely viable. Just need to agree on what those are (and not too many of them).

**Comment by petecooper** [comment]
@philwareham - I have a few hours spare today, you want a hand with this?

**Comment by philwareham** [comment]
Sure, more help the better. Just need to list out here a few (couple of dozen max) common terms used on front-end websites. Once agreed we can then put into the en.ini file and I'll upload to Crowdin.

On a totally unrelated note, could you possible look at turning off the security thin on the Textile site that causes the HTML comment to appear in output? Just turn off for that site if possible?

**Comment by petecooper** [comment]
>On a totally unrelated note, could you possible look at turning off the security thin on the Textile site that causes the HTML comment to appear in output? Just turn off for that site if possible?

Done.

**Comment by philwareham** [comment]
OK, here's the start of a list - feel free to add/argue against anything below:

```
continue_reading="Continue reading"
current="(current)" (required for Bootstrap framework)
learn_more="Learn more"
more_pages="(more pages)" (required for Bootstrap framework)
page_nav="Page navigation" (required for Bootstrap framework)
read_more="Read more"
search_here="Search here…"
select_language="Select language"
site_nav="Site navigation"
welcome="Welcome"
```

**Comment by petecooper** [comment]
Do we need to namespace these? e.g. `theme_site_nav`, `theme_welcome` etc. Some are quite generic, which is no bad thing - but it might save collisions later on.

**Comment by petecooper** [comment]
>unless that clashes with plugin author's Textpacks

This was basically my concern. The absence of proper namespacing makes it a nagging concern, albeit a small one for me personally since I don't use plugins. I suppose if Textpattern decides on the string names and everyone abides, that removes the collision element.

**Comment by Bloke** [comment]
We haven't traditionally namespaced lang string keys beyond:

1. Putting them in their own groups ('events')
2. Permitting an 'owner' to be specified. Empty owner = core string, if memory serves.

It's pretty loose, I admit. Plugins should _always_ namespace (ahem, prefix) their own strings, as the assumption is that anything non-prefixed is core. With the advent of 'owner' the enforced prefix kind of goes away (because you can use the owner to indicate either authorship by you, or authorship by a specific plugin - although `event` is probably a better use for plugin ownership as that'll autoload the strings on your plugin's admin panel) BUT the database indexes only permit unique keys _per language_. So you can't redefine a string with the same key as another one anyway. Hence, no collisions are possible.

If we were going to make theme-specific strings, we could introduce a `theme` event that we could also include on the public site in addition to `common` and `public` but I'm not sure it's warranted.

The real issue will come if you want _different_ strings with the same key for different themes in the same language:

Theme A: site_nav => "Site navigation"
Theme B: site_nav => "Site sections"

Not possible right now. We need to think about this as we move towards multi-lingual content in a future version.

**Comment by bloatware** [comment]
I like the idea of making `public` strings theme-related. This would possibly mean creating a much smaller separate table with `skin` field, which is a good thing performance-wise. We will also need an interface for adding custom strings one day, but definitely not in 4.7.2.

**Comment by bloatware** [comment]
@Bloke great, and I'm pretty sure that custom strings will go in pair with custom fields, so core seems unavoidable.

@philwareham I'm fine with those atm. It's possible that we integrate theme strings even before 4.8, say, at the moment of new themes site release.

**Comment by philwareham** [comment]
OK, I'll add those 4 now and close this issue. Please open a new issue for theme-based localisations when the time is right. Hopefully a few translators can translate these new strings in time for 4.7.2 release in next day or so.
