### ISSUE TITLE
Textpattern CMS has a storage XSS vulnerability

### ISSUE THREAD

**Issue by yundiao** [textpattern/textpattern#1401]
### Expected behaviour

storage XSS

### Actual behaviour

storage XSS

### Steps to reproduce

**I.	 Vulnerability Analysis**
XSS filtering is not done in the blog background writing article.  XSS code can be written when writing articles, resulting in storage-type XSS vulnerabilities.

About Blog Filtering:
	SQL injection filtering is done in the writing section, XSS and SQL injection filtering are done in the front comments section.
	If XSS filter is added to the writing article, it can be repaired and blog security can be improved.

**II.	Vulnerability Exploitation**
When writing an article in the background, write the following code in the content:
`<script>alert(document.cookie);</script>`
![write_article](https://user-images.githubusercontent.com/47202604/55305199-e326dc80-5481-11e9-8504-0d3a26cd45de.png)

After clicking Publish to publish.
It can be triggered at the front page or at the place of article viewing.
![xss](https://user-images.githubusercontent.com/47202604/55305227-f174f880-5481-11e9-9450-592b02513a70.png)

**III.	 POC**
`<script>alert(document.cookie);</script>`

#### Additional information

Textpattern version: v4.7.3

**Comment by Bloke** [comment]
This is kind of by design. If you don't trust your authors not to put malicious code in articles, you should hire more trustworthy people :)

SQL injection filtering is standard behaviour with any database system and will become even more robust when we move to PDO. It is performed as standard on all queries.

The XSS checks are in comments because of the increased attack vectors. We don't know who's out there and might comment. Content authorship is a more controlled environment.

We could maybe filter such content in articles too, forcing all client-side code to be put in Pages/Forms. It'd be a backwards-incompatible change. But if you have untrustworthy editors, you should (untested) be able to do this anyway in your template code by adding `escape="script"` in your `<txp:body />` and `<txp:excerpt />` tags.

**Comment by bloatware** [comment]
You'd need also filter `onevent` attributes and probably styles/xml/etc. We could impose lite Textile to "content-only" users, as we do for comments, leaving the eventual conversion to full Textile decision with site admins.

**Comment by petecooper** [comment]
>This is kind of by design.

Safe and/or appropriate to close?

**Comment by philwareham** [comment]
Fine to close IMO

**Comment by petecooper** [comment]
Closing, please re-open If/as required.
