### ISSUE TITLE
Additional SMTP header configuration

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1410]
### Is your feature request related to a problem?

Small problem, not a deal breaker.

### What is the feature?

Optionally specify `Reply-To` and `Return-Path` headers in outgoing emails.

We currently have the `From` header for outgoing SMTP emails, and it works well. I'm encountering a few email systems that compare the various headers and are soft rejecting incoming Texpattern emails, marking them as spam initially. Subsequent user intervention (i.e. marking as not spam) seems to clear this up in the limited testing I've done.

The ongoing issues of email deliverability becoming gradually more tricky over time will likely continue, and with this functionality there's a fighting chance of affected Textpattern instances being able to overcome it, especially on shared servers where the MTA is configured for everyone and not a single site.

Considerations:

* presumably reusing SMTP `From` header code in a similar fashion for other headers would achieve the above;
* new or updated documention;

**Comment by petecooper** [comment]
Related forum issue https://forum.textpattern.com/viewtopic.php?pid=318338#p318338

**Comment by AmritasyaPutra** [comment]
Yes, this is a much needed change.

I am a normal user. My email id is with gmail.com. If a new comment comes on my article, the site sends email alert to me, the email has from address as my gmail address itself. It is marked as  spam (justifiably). I expected "SMTP envelope sender address" configuration value to be used to send the email. Why is it used only for smtp.mailfrom, Return-Path and envelope-from but not for From field? It is counter-intuitive to me.

**Comment by Bloke** [comment]
Do we still need `Return-Path`? I notice that our `txpMail()` function (which uses the `/vendors/Textpattern/Mail/Adapter/Mail` class now) does support `Reply-To`, but none of our internal functions use it. So it's omitted. 

Fixes, individually or in combination:

1. Add the `reply_to` parameter to all our internal calls to `txpMail()`.
1. Wire things up so we automatically retrofit the Mail class to add Reply-To. Not very friendly to plugins who might not want that feature.
1. Add `Return-Path` support to the Mail class and find a way to use it (like option 1).
1. Leave everything as it is and introduce SMTP mail support already, dammit.

**Comment by petecooper** [comment]
>Leave everything as it is and introduce SMTP mail support already, dammit.

[PHPMailer](https://github.com/PHPMailer/PHPMailer) might save us a lot of work. It's LGPL v2.1, which appears to be a good fit with GPL v2, especially since we're already using LGPL libraries with appropriate attribution.

Tagging https://github.com/textpattern/textpattern/issues/1133 in the spirit of two birds with one stone.

**Comment by vanmelick** [comment]
On 26/09/2019 17:42, Stef Dawson wrote:
>
> Do we still need |Return-Path|? I notice that our |txpMail()| function 
> (which uses the |/vendors/Textpattern/Mail/Adapter/Mail| class now) 
> does support |Reply-To|, but none of our internal functions use it. So 
> it's omitted.
>

Unless you're implementing a complete MTA (mail transfer agent), you 
must not add a Return-Path header at all, because it's supposed to be 
added by the sending MTA which in turn gets it from:
* the -f<sender@example.com> parameter in the sendmail call, if you're 
using the PHP mail function, which you're already doing via the smtpFrom 
attribute in |/vendors/Textpattern/Mail/Adapter/Mail|
* the "MAIL FROM: <sender@example.com>" header sent if you're doing a 
SMTP handshake.

> Fixes, individually or in combination:
>
>  1. Add the |reply_to| parameter to all our internal calls to |txpMail()|.
>

Yes, definitely as an optional (!) parameter.

>  1. Wire things up so we automatically retrofit the Mail class to add
>     Reply-To. Not very friendly to plugins who might not want that
>     feature.
>

No. You do not want to set the Reply-To address, unless it's different 
from the From address. It's not unthinkable that having identical From 
and Reply-To addresses counts when calculating a spam score.

>  1. Add |Return-Path| support to the Mail class and find a way to use
>     it (like option 1).
>

No. See explanation above.

>  1. Leave everything as it is and introduce SMTP mail support already,
>     dammit.
>

+1 on implementing SMTP mail, preferably by reusing something that has 
seen a lot of review and is actively maintained. No point in reinventing 
the wheel.

I've had a discussion last week with a large mail delivery service about 
the effect of using the PHP mail() function on the spam score in their 
outbound filters. They've made it clear to me that they prefer mail sent 
via authenticated SMTP instead of via PHP mail() due to the amount of 
spam that is sent via PHP mail(). Looking at the flags used in their 
spam score, I also found a few other things that matter:
* don't use (base64 or quoted printable) encoding in the 
from/to/reply-to/subject/etc headers unless it includes characters that 
require encoding. Both the Mail class in TXP and PHPmailer seem to 
handle this correctly.
* envelope sender address preferably equal to the from address. While 
technically there's nothing wrong with having the From address be 
different from the envelope sender, it seems that nowadays it can affect 
the spam score. Recently someone requested to expand the use of the 
smtp_from preference, which I opposed at the time, partly because the 
preference label is very specific. I propose renaming it to a more 
neutral "Default sender email address" and use that as both From and 
SMTP envelope sender address, while still making it possible to override 
this.

--Ruud

**Comment by petecooper** [comment]
@vanmelick - an excellent and informative post, thank you! I respectfully stand corrected.

**Comment by petecooper** [comment]
I'm erring towards closing this in favour of focusing on https://github.com/textpattern/textpattern/issues/1133 since we'd achieve the OP result with an appropriate library (taking into account overall functions and size, of course), and we'd avoid reinventing any wheels.

So, closing this as part of housekeeping - please reopen if you believe it's sufficiently different from the linked issue. Thank you.
