### ISSUE TITLE
Adding a special theme with the distribution

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1414]
### Is your feature request related to a problem?

No. Just a suggestion for the next version.

### What is the feature?

Choosing "empty theme" during an installation is useful for starting a new website without a theme.

What do you think about offering a special theme for live sites during development? The asomption is to inform search engine bots the website is currently not finished. This theme will be only one single page and a simple design but starting with this code in it:

    <txp:header name="HTTP/1.1 503 Service Temporarily Unavailable" />
    <txp:header name="Status" value="503 Service Temporarily Unavailable" />
    <txp:header name="Retry-After: 3600" /><!DOCTYPE html>

The design would be at your discretion and its name too (maybe: "Maintenance").

**Comment by Bloke** [comment]
I kind of like the idea of doing this in a theme because it allows a nice easy way to switch a site 'off' while a site is in development. It might be a nice theme to offer on the Themes site when it comes online, but I don't know about shipping it in core.

The reason for my reticence? Currently, Themes in Textpattern are designed in such a way that - if you're careful - you can actually run development and live versions side-by-side with no ill effects. So there's often no need for 'Maintenance' at all. When you're happy with the dev theme that you test as a logged-in user, you can switch it over on any Section(s) immediately using the multi-edit tool.

Let's see what @philwareham thinks, but I'm tentative: no-for-core-but-yes-on-the-theme-site.

**Comment by petecooper** [comment]
I really like this as a Textpattern tip (or similar) write up, I like it as a standalone theme, but respectfully I am -1 for including in the distribution release. I would also be +1 for a subsection of themes for maintenance, under construction, etc - that's a great idea.

Search engine friendliness is a personal choice, there are some people who are very self-aware when search engines are involved…other people don't care…and other people are very anti-search engines. Everyone has their reasons.

**Comment by cara-tm** [comment]
I'm working on such a kind of theme.

**Comment by petecooper** [comment]
@philwareham - what's your take on this as design dude?

**Comment by cara-tm** [comment]
Note: if you are interested, I can change the author name by "Textpattern community" and allow the first image uploaded as the main illustration. Even more: you can change the theme as you want. ;)

**Comment by Bloke** [comment]
Tagging @jools-r in on this, as it may be beneficial as a txp.tip. Otherwise, I think we can probably close this here?

**Comment by petecooper** [comment]
Closing this - anyone requiring an in-development temporary them should refer to the URL in https://github.com/textpattern/textpattern/issues/1414#issuecomment-519037983 for information.
