### ISSUE TITLE
NTS: rework README.md

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1420]
There's a funny mix of end user info and developer info, could probably be best served by a couple of files aimed more at each audience rather than crammed into one.

Considerations & audiences:

* users;
* administrators;
* developers;
  * plugins
  * themes
* contributors;
  * docs;
* sponsors;

**Comment by Bloke** [comment]
Or a single README separated into concerns like you cited above. Or with a single user/developer split to make it more targeted.

The only reason we have README is due to that long-standing tradition from Unix days gone by. If we want to play with that tradition, that's fine by me as long as the filenames stay roughly the same - those people that do upload the README(s) to their server, contrary to advice, won't be able to serve any sections/articles of the names given to the files.

**Comment by petecooper** [comment]
>Or a single README separated into concerns like you cited above. Or with a single user/developer split to make it more targeted.

Yep - like this. Thanks!

**Comment by petecooper** [comment]
Thinking about this some more…there's a `README.txt` and `README.md`, the latter being the GitHub billboard, effectively. It'd make sense to me to leave .txt as it is, 'cos that works fine and has done forever (and, as you say, the UNIX heads are happy with that). Perhaps a split on the .md front to include `CONTRIBUTING.md` (see https://help.github.com/en/articles/setting-guidelines-for-repository-contributors for info) and spin out some of the info from `README.md`, which makes it a bit less muddy.

**Comment by petecooper** [comment]
Closing this for now, I will rethink from a docs point of view.
