### ISSUE TITLE
MySQL username and password - required at setup?

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1438]
### Expected behaviour

@bloke I think the MySQL username and password are required fields when running through the setup process, yes?

### Actual behaviour

Currently those two fields are not indicated as required.

### Steps to reproduce

Run setup, note the fields lack a `required` attribute.

#### Additional information

Textpattern version: dev-4.8

**Comment by Bloke** [comment]
Not sure. All parameters, bar the link, in [mysqli_real_connect()](https://www.php.net/manual/en/mysqli.real-connect.php) are optional.

If the host is missing, `localhost` is assumed. If the user is missing, the docs are unclear. [mysqli_connect()](https://www.php.net/manual/en/mysqli.construct.php) says that if the user name is not present it will look in the .ini file to find the default user name. Maybe `mysqli_real_connect()` does the same? Dunno.

In any case, the password is always optional. You can make a user without one and - indeed - it's valid to do so (I sometimes do it in localhost environments when developing). You can set up one user with two rows in the grants table, allowing different permissions to the passworded user vs the same non-passworded user.

If anyone has any insight on what happens if you don't specify a username - what does PHP/MySQL try and do? - it would help us decide if we should make the user name a required field.

**Comment by philwareham** [comment]
From my brief skill of the MySQL documentation, only username and database name are truly essential. Localhost is the fallback for empty host values and you've noted that a user doesn't need a password and technically not a name as it'll try to resolve that if empty.

However, it'd probably be prudent for Textpattern to indicate the username, host and database name *are* required just for good practice and to avoid any pitfalls where MySQL can resolve on its own? Whaddayathink?

**Comment by Bloke** [comment]
Yeah, maybe. I've got no problem with doing it. Just don't want to lock out any people who use advanced processes like `.ini` files, or MySQL config files that contain such credentials in lieu of what we hard-code in`config.php`.

I know that there's a process (somehow, I forget how) by which you can pre-compute hashes for MySQL connections and store them in an encrypted config file. This means you don't have to put plaintext passwords in disk files (like we do in `config.php`) which is a valid concern. Whether anyone does (or even can) do that with Txp, I'm not sure.

**Comment by philwareham** [comment]
OK, alternative would be to take `required` off the host field and leave it as just database name that is required. That technically is the correct minimum requirement. I'm sure most users are savvy enough to know how to input their database details.

**Comment by Bloke** [comment]
Thing is, although PHP is technically geared up to permit empty host and default to localhost, I'm not sure Txp is. I've never tried it. If we remove the 'required' off the host field in the web inspector and test it, I'm sure we'll see what happens!

**Comment by philwareham** [comment]
Yep, works fine!
