### ISSUE TITLE
Extended config.php options (was: https switch in Admin › Site preferences ?)

### ISSUE THREAD

**Issue by jools-r** [textpattern/textpattern#1444]
A simple **Output https:// links?** (or similar wording) on/off radio for the *Admin › Site* preferences. Alternatively a select switch (like the XHTML / HTML switch) along the lines of **http protocol** with `http` / `https` as the options.

Perhaps this could also sneak its way into 4.8 at the last moment as it's now a very common situation and setting `define('PROTOCOL', 'https://');` in the config is not the most intuitive thing for first-time users to find.

To clarify that this setting doesn't magically make your site secure, maybe the associated pophelp should note that:

- it simply means Textpattern's in-built link-forming txp tags output 'https://' rather than 'http://' links.
- a precondition for a correct https-site is a pre-existing SSL certificate (see your host).
- other self-coded links in the page templates, forms and articles must likewise be manually changed to https:// where appropriate.

**Comment by Bloke** [comment]
I'd have to refresh my memory but in the absence of `PROTOCOL` don't we guess the protocol to add to all links via `hu`? It should match the currently-used protocol from the URL, I believe.

Thinking about use cases:

* People who have gone to the trouble of setting their sites up with a valid certificate will likely set their '.htaccess' or Nginx config files to https everywhere, so the automatic protocol prefix will work. Or they'll set their `protocol` in 'config.php' as you describe. You don't need both.
* People who have not set their site with a valid certificate won't benefit from the pref switch because their site will issue a security warning, which is likely to put visitors off.

Forgive the daft question, but who would this pref target and how would it benefit them and/or visitors?

**Comment by jools-r** [comment]
I agree you don't need both the setting in config.php and a switch. I thought it could replace it. My thinking was that now that many hosts have a point-and-click setup routine for setting up Lets Encrypt certificates, less experienced users can implement that fairly safely. I'm not sure how many hosts or users do “force redirect of http -> https” safely (i.e. so that their freshly installed lets encrypt doesn't bork at the next renewal because the ACME challenge renewal method does still need http access).

> don't we guess the protocol to add to all links 

I wasn't aware that Textpattern produced the correct urls on its own if the page is already an https:// url. If that's the case, then you are probably right that this is unnecessary. Maybe it's because until recently when developing locally I rarely set up a self-signed certificate for the local/dev/test domain so I only dealt with the switch when setting up the production site.

Otherwise, I do get the concern that such a switch might lead people to believe that all they need to do to get a secure site is flip the switch.

**Comment by Bloke** [comment]
Yeah, I guess for those that don't set their '.htaccess' up to do the redirect, or who don't configure certbot to do it for them at the Apache mod level, a switch is nicer than having to edit a config file.

Now, I don't know how this works on non-self-hosted setups because it's been ages since I've used cpanel or equivalent. But I know when I set up certs on my host I run `certbot --apache` and the wizard asks for the domain name(s) I want to set up, then asks if I want to auto-renew them and asks if I want to force https for all those domains. If I say yes, it installs the certificates and mucks about with the Apache config at the `sites-available` / `sites-enabled` level so I don't need to modify my Txp's '.htaccess' file at all. It just serves https all the time.

Presuming that cpanel et al just provide a shiny interface over the top of this certbot wizard (perhaps a big assumption, I don't know), I wonder how many people would install a certificate this way, and then choose _not_ to automatically have Apache handle https? Only under those circumstances would I see the benefit of having a switch in Txp, and even then (as you say) we'd need to document it big time so people didn't switch it on and assume it's going to install certs or make their site somehow 'secure'.

Not sure. I'm torn on how to handle this for best without introducing more head-scratching for users / support requests for us.

**Comment by petecooper** [comment]
Bumping this issue with another issue: https://github.com/textpattern/textpattern/issues/1454 - we have a commented entry in config-dist, so it's a _bit_ more doable.

That said, this issue is perhaps a tricky one to solve or diagnose. As time moves forward, it's common sense that https adoption will increase, and that includes automatic https diversion when an http address is used. I daresay browser feedback will push this along further.

I don't know the metrics on who runs Textpattern from cPanel all-in-one consoles versus folks who run their own servers…I would wager that many more people are in the console or web admin camp than the server bodger camp, and they just don't muck around with stuff unless it's not working.

All that said, I like the idea of a proper how-to on enabling https, but there's so much variance in web hosting companies ops that it might just end up being 'contact your web host'.

**Comment by Bloke** [comment]
I'm all for official how-to articles for two reasons. One, we can point people to them from the forum. Two, they're an excellent honeypot for search engine spiders, which can bring visitors to us when they search for generic things like "how do I make my website secure?"

Cross-selling opportunities abound for the right kind of article, even if it merely provides an overview of the options or some explanation of terms within the copy so people feel more informed on the other side and can contact their host and ask the right questions. The fact we mention this never-heard-of-it Textpattern thing in the sidebar, and a few times in the article, is bonus exposure.

I'd rather document the heck out of it than put a potentially misleading switch in the software, but I'm willing to be re-neducated if this view is misguided.

**Comment by jools-r** [comment]
I can go with this too, especially as #1454 means that it is now included commented out in config.dist. I don't suppose people notice this when they use the installer, and its debatable whether commented out options should be included (still commented out) in the generated config.php.

Otherwise, Jonathan documented it long ago on [txptips](https://textpattern.tips/site-links-in-ssl) and I could expand on that article.

**Comment by Bloke** [comment]
Didn't realise we had that on Tips. If we could expand on that to include LetsEncrypt and certificate info, great. If we feel it requires an official blog post on .com, that's fine too. I'm easy either way.

**Comment by petecooper** [comment]
>they're an excellent honeypot for search engine spiders, which can bring visitors to us when they search for generic things like "how do I make my website secure?"

Heavy +1 to this, I was thinking the same thing.

**Comment by petecooper** [comment]
>debatable whether commented out options should be included (still commented out) in the generated config.php

Maybe heading off topic here…but how viable would it be to have a link to the docs site when then config file is presented? Look here for additional options, sort of thing,

**Comment by Bloke** [comment]
Mmmm, a comment link to the docs in the config file. I like that idea.

OT very slightly: Would the installer benefit from such a link too nearby the textarea? Or would the link in the content itself be good enough if it was displayed in the textarea for copy/download?

Perhaps if we write an article on .com that documents the config extension variables, you could add redirect that we could stick in core here?

**Comment by petecooper** [comment]
> Would the installer benefit from such a link too nearby the textarea? Or would the link in the content itself be good enough if it was displayed in the textarea for copy/download?

Gut feeling says most people will just copy & paste and go about their day. That textarea content is code in PHP-ese, so gobbledegook for many people. Localised language wins by a nose. There're no rules to say that the installation has to be as minimal as possible, so I think a single-sentence paragraph before the textarea would suffice. It's also pretty easy to maintain from a translation point of view.

>Perhaps if we write an article on .com that documents the config extension variables, you could add redirect that we could stick in core here?

A docs site article would be more evergreen, at least from a revisions point of view, I don't really fancy trawling through .com articles to update them when we need to tweak. I could've sworn there was already a doc with config options in it…

**Comment by petecooper** [comment]
> If we could expand on that to include LetsEncrypt and certificate info, great

Be wary of offering too much here. I've been around the LE forums on and off, and there are _many_ people who just come clattering in needing urgent help. Links to LE stuff, maybe even extend to ACME providers at a push, that reduces the tech support attack surface!

**Comment by jools-r** [comment]
> A docs site article would be more evergreen, at least from a revisions point of view

How about a single comment in the generated / saved config.php that says see config.dist file for further config options. It doesn't tie the content to help elsewhere that might not be up to date and the config.dist lists other relevant config settings? 

> If we could expand on that to include LetsEncrypt and certificate info, great
> Be wary of offering too much here.

Yes, that could be a minefield. I was thinking more of setting out prerequisites (how you do that is another matter) and then providing some additional pointers to things like htaccess http-to-https options like in HTML5 boilerplate, and best practices such as avoiding mixed http / https sources in one's code, css and articles.

**Comment by Bloke** [comment]
Docs article, sure. Better. Dunno why I even suggested .com. Stupid brain. And yeah, you're way more well-versed in the certs arena than me so whatever you see is suitable is fine by me.

**Comment by petecooper** [comment]
>How about a single comment in the generated / saved config.php that says see config.dist file for further config options.

Actually, yeah - it's less version-specific, so fewer worries about features being introduced and not available to older versions.

**Comment by petecooper** [comment]
>How about a single comment in the generated / saved config.php that says see config.dist file for further config options. It doesn't tie the content to help elsewhere that might not be up to date and the config.dist lists other relevant config settings?

Revisiting this -  I think this route plus a doc would cover most bases.

If we do take this route, should the comment be a translatable string, or left as `en`?

**Comment by Bloke** [comment]
config.php is code, so no need for translations imo.

**Comment by philwareham** [comment]
Does #1531 satisfy this issue too? If so, then please close. Otherwise, keep open.

**Comment by petecooper** [comment]
>Does #1531 satisfy this issue too?

I think it does. We can extend the docs easily enough. Closing for now, please re-open if you disagree.
