### ISSUE TITLE
Lang::findFilename() does not fall back from specific locales like 'de-de' to generic locales like 'de'

### ISSUE THREAD

**Issue by rwetzlmayr** [textpattern/textpattern#1474]
### Expected behaviour

`\Textpattern\L10n\Lang::findFilename()` should fall back and return the file name of an existing generic language file (e.g. _de.ini_) in case the more specific language file (e.g. _de-de.ini_) is not available.

### Actual behaviour

`Lang::findFilename()` returns `null` when it cannot find a file exactly matching the requested `$lang_code`. 

This causes `Lang::getPack()` to throw an exception stating  _file_get_contents(): Filename cannot be empty_ in https://github.com/textpattern/textpattern/blob/0900d940323cbe10227791da5d20bb9616fb4a70/textpattern/vendors/Textpattern/L10n/Lang.php#L373

**This exception prohibits updates to sites** with their language preferences set in older Txp versions where we still had _de-at_ and _de-de_ l10n.

#### Additional information

Textpattern version: 4.8.0

**Comment by Bloke** [comment]
Interestingly, I can't reproduce this on PHP 5.5.38. My method:

* Install and setup bare Txp 4.6.2
* Log in and install a few languages.
* Switch to German site language.
* Confirm via MySQL that the language pref is de-de. Locale is de_DE.UTF-8.
* Logout.
* Replace all system files with Txp 4.8.1-dev (which in terms of Language capability is identical to 4.8.0).
* Log back into Txp.

Result: upgraded. Language still German.

Under which version of PHP does this behaviour manifest itself so I can check any fixes work properly? Also, do you think the locale makes a difference?

As a separate test, I tried the above and manually hacked the txp_prefs `language` and `locale` entries to the (officially unsupported) de-at and de-AT.UTF-8, respectively.

The admin-side rendered untranslated raw strings (as expected) under 4.6.2, but the upgrade to 4.8 still worked, despite not altering the language code to 'de' (as I would have preferred). We could improve this by either:

a) extending our `recodeLocale` table to include more [regional variants](https://www.science.co.il/language/Locale-codes.php).
b) fixing function `validLocale()` so that it tries a bit harder to find a (partial) match if the full code isn't available as a key, thus making a better job of fallback.

**Comment by rwetzlmayr** [comment]
FWIW, I used PHP 7.3.4 on Apache/2.4.39 (Win64)
