### ISSUE TITLE
link_to_next/prev not matching prev/next_title in 4.8.0

### ISSUE THREAD

**Issue by johnnybubonic** [textpattern/textpattern#1476]
### Expected behaviour

When using the following in a form:

```html
<table>
  <caption>Navigation</caption>
  <thead>
    <tr>
      <th>Previous Article</th>
      <th>Next Article</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><txp:link_to_prev><txp:prev_title /></txp:link_to_prev></td>
      <td><txp:link_to_next><txp:next_title /></txp:link_to_next></td>
    </tr>
  </tbody>
</table>
```
One expects to see a table row of links to the articles and their associated titles.

### Actual behaviour

The table row is created, but the link text (`prev_title` and `next_title`) are incorrect. The URL *is* correct, however.

### Steps to reproduce

See above.

#### Additional information

I usually date my articles in the future on creation so they only show on article listings at a specific date/time. I'm not sure if that'd have an effect on associated logic, but the same behaviour occurs whether it is before or after the article's post date/time.

Additionally, I don't suppose there's a way to limit link_to_prev/next and prev/next_title to the current category or section, right?

**Comment by Bloke** [comment]
Try changing your link_to_next/prev containers to:

``` html
<txp:link_to_prev><txp:title /></txp:link_to_prev>
<txp:link_to_next><txp:title /></txp:link_to_next>
```

The way the next/prev is handled has changed so that when you are inside the link_to_next/prev container, you are already "pointing at" the next article. Therefore you need to use the _current_ title tag `<txp:title />` in both cases. Otherwise it skips an article in either direction.

This change brings it in line with other tags for consistency.

The link_to tags _should_ (as far as I recall) automatically limit to the current section. But I think they traverse category. If you need different behaviour, you could try the [smd_horizon](https://github.com/Bloke/smd_horizon/releases) plugin.

**Comment by johnnybubonic** [comment]
that did the trick. thank you so much!
