### ISSUE TITLE
Demo sites are not working at https://textpattern.co/demo

### ISSUE THREAD

**Issue by zgyarmati** [textpattern/textpattern#1482]
On the  project's homepage (https://textpattern.co/demo)  the offered demo sites are not working. It should work to improve the first-contact experience.
The 'Public' site fails with "MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING" and the 'Admin' gives back 502.

**Comment by petecooper** [comment]
Hi @zgyarmati - thanks for your report. I am sorry for my delay in responding.

The `MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING` error is a known issue with Firefox-based browsers, and is typically resolved with a browser refresh. This error happens if you are the first person to access the page after an Nginx (web server) process restart. As the web server is restarted numerous times per day as part of the automated rebuild process, the first visitor in a Firefox-based browser gets the error. I am currently looking for a solution for this, so thank you for the reminder – I will continue to search!

The 502 error occurs when PHP-FPM is in the process of starting up, which is typically around the time of the Nginx restart, so this is unfortunate timing that you hit both of these blocks.

**Comment by petecooper** [comment]
I've rebuilt some of the server infrastructure, so it should be more reliable now. I will close this and keep monitoring for ways to improve the OCSP stapling cache, which is what causes the `MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING` error on Firefox. Thanks again for the report @zgyarmati!
