### ISSUE TITLE
Branch audit and spring cleaning

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1490]
Currently, there are 9 [branches](https://github.com/textpattern/textpattern/branches) in this repo:

![Screenshot 2020-05-28 at 12 45 31](https://user-images.githubusercontent.com/226578/83137535-3aa1f600-a0e1-11ea-9b2a-00367e94bb11.png)

Is it viable to audit and perhaps spring clean before we get too involved with 4.9 development? It's entirely likely that some of the functionality and improvements in the branches have already been merged into `dev` or `master`, so we may be able to safely jettison some of the branches, or work them into `dev`.

@Bloke @bloatware @philwareham – please assign yourself if appropriate. Mucho thanks-o.

**Comment by bloatware** [comment]
IIRC, `bloatware-patch-2` was an attempt to introduce array-like cf filters to `<txp:article />`. Will be superseded by `custom-fields` branch, but is probably worth keeping atm.

`integrity` is a working attempt to send integrity hashes along with txp `.js` and `.css` files. An immediate benefice is stale cached files detection, for example when updating. A drawback is that it requires setting some headers that not all hosting services provide. So they are set via PHP, which means we need to start it even for serving `textpattern.js`. Not a big deal if it's cached, since only logged-in users need it. Will take a look.

**Comment by Bloke** [comment]
Thanks for the precis. Might be worth seeing if any of bloatware-patch-2 can be folded into the custom-fields branch then. Sound like it might be handy.

**Comment by philwareham** [comment]
Closing this, all branches are viable at the moment. Some will disappear as the functionality rolls into dev eventually.
