### ISSUE TITLE
Cross Site Scripting Vulnerability on "Menu Preferences" feature in Textpattern v4.8.1

### ISSUE THREAD

**Issue by luuthehienhbit** [textpattern/textpattern#1495]
### Expected behaviour

An authenticated malicious user can take advantage of a Stored XSS vulnerability in the "Menu Preferences" feature.

### Impact

Commonly include transmitting private data, like cookies or other session information, to the attacker, redirecting the victim to web content controlled by the attacker, or performing other malicious operations on the user’s machine under the guise of the vulnerable site.

### Steps to reproduce

   1. Log into the Admin.
   2. Go to "Menu Preferences"
![image](https://user-images.githubusercontent.com/50371661/83992566-f1706280-a97a-11ea-8d18-472d192dd652.png)
   3. Click "Custom fields"
![image](https://user-images.githubusercontent.com/50371661/83992590-05b45f80-a97b-11ea-8de0-148011566b94.png)
   4. Insert payload to Fields name:
   '><details/open/ontoggle=confirm(1337)>
   5. Click Icon Textpattern:
![image](https://user-images.githubusercontent.com/50371661/83992709-63e14280-a97b-11ea-94c0-01dbe89ab2a3.png)
![image](https://user-images.githubusercontent.com/50371661/83992711-65126f80-a97b-11ea-8bc5-0ca9d6aac3fc.png)
 
#### Additional information
Textpattern version: 4.8.1

**Comment by Bloke** [comment]
Thank you for the report. Although it's a low-level vector (since the only people that can set Custom Field labels are Managing Editors and higher, whom should be inherently trusted), sanitizing the label is good practice as they're not supposed to contain any dubious characters.

This is now fixed in the upcoming 4.8.2 release in commit 8623928. Please test and ensure it has no unintended consequences.

**Comment by luuthehienhbit** [comment]
Hi Bloke.
I will continue testing with your product.
You can a CVE ID assigned and reference change log to "UraSec Team"  👍 
Thanks you!
