### ISSUE TITLE
Blacklist to blocklist for more inclusive code

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1522]
Although we changed references in language packs from 'blacklist' to 'blocklist' many years ago, there are still uses of that terminology in our legacy code. For example the `spam_blacklists` pref.

I propose we change that terminology too.

**Comment by petecooper** [comment]
Aside: there are references to 'whitelist' in the Textile parser, but that's outside our project scope and above my issue-raising pay grade at https://github.com/textile/php-textile/

**Comment by philwareham** [comment]
@Bloke I have also duplicated `master` GitHub branch to `main` (see https://www.cnet.com/news/microsofts-github-is-removing-coding-terms-like-master-and-slave/) - if you are happy it's functioning as intended, I will delete the `master` branch.

**Comment by petecooper** [comment]
Further info for future librarians: https://github.com/github/renaming

**Comment by philwareham** [comment]
Cheers Pete. Just as an addendum, since we've used `dev` as our default branch since forever, the issues raised in that link don't really affect our day-to-day work on the repo - which is good.

**Comment by petecooper** [comment]
Yep, agreed - just looping it in for completeness and future ref, really.

**Comment by Bloke** [comment]
Duplicating it is fine if that's the preferred option to renaming. The issues I see that affect us from the article Pete linked are:

1. Open pull requests need to be retargeted to the new branch
2. (When we do the docs site IF we haven't self hosted by then) GitHub Pages expects content in the master or gh-pages branch

If renaming is going to cause less hassle than duplicating (because Microsoft will auto-update links and branch requests from local repos automatically if we rename) then I say we rename instead.

I'm fine with "main" but you're right that "release" might be better, given it's not our primary branch.

**Comment by philwareham** [comment]
Pull Requests shouldn't be targeting `master` anyway, as we don't use that branch for any development.

**Comment by Bloke** [comment]
Good point on the PRs. They're all targeted elsewhere so we're fine. Sorry. Dumbass moment.

**Comment by philwareham** [comment]
OK, `master` branch in this repo is now gone. We will update the other repos over next few months (as the tools become available) since they **do** use the `master` branch as their defaults.

**Comment by petecooper** [comment]
I've updated build instructions in https://github.com/textpattern/textpattern-toolbelt and tweaked a few internal licence links in https://github.com/textpattern/textpattern/commit/45ddb56c6b1fdba226af1031237dd6adb7a7c1b9

**Comment by phiw13** [comment]
Just a  fwiw, as there is probably very little you –as end user– can do about it, but Github does not seem to send a permanent redirect with the `atom feed`. I had to manually update the URL in Vienna.
