### ISSUE TITLE
RFC: Append version number to `A problem occurred while loading the plugin` notifications

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1593]
### Is your feature request related to a problem?

Yes, but not for me.

### What is the feature?

To aid troubleshooting, how much value is there in appending the plugin version number to the `A problem occurred while loading the plugin` notification. Currently we have (e.g.):

```
A problem occurred while loading the plugin: adi_notes -> User_Warning: Unable to include plugin adi_notes. on line 1438
textpattern/lib/txplib_misc.php:1438 trigger_error()
textpattern/index.php:210 load_plugins()
```

When this is posted to the forum or elsewhere, we don't know the version number, so we ask…and wait. Something like (e.g.):

```
A problem occurred while loading the plugin: adi_notes (1.2.3) -> User_Warning: Unable to include plugin adi_notes. on line 1438
textpattern/lib/txplib_misc.php:1438 trigger_error()
textpattern/index.php:210 load_plugins()
```
…would be helpful, saves a round trip + waiting time.

Cons would be displaying a potentially vulnerable plugin version, I can't immediately think of anything else.

Would appreciate your thoughts, should you have any.

**Comment by Bloke** [comment]
Don't see any major problems with this, presuming we have access to the version number at error time. I could have a look. Leaking the version number isn't a huge issue, imo, unless someone else can see a downside.

**Comment by petecooper** [comment]
The `txp_plugin` table has a `version` column, so I'm guessing if the `name` can be extracted from a row, if there's something in the `version` column it should be possible. Whether or not it's viable or valuable, that's another matter.

**Comment by Bloke** [comment]
Just an addendum to this for completeness: there's a subtle bug in 4.8.5 that probably won't ever rear its head. But if:

a) A plugin is loaded from the cache dir and;
b) It contains a catchable error or;
c) Throws one during the loading phase

then the plugin version number might not be available and core would trigger a warning. The version is not populated until _after_ a plugin is passed through `include()` (because it's part of the plugin template so needs reading first).

Commit 55720403 guards against this corner case by simply omitting the version number if it's not available at the moment the error is triggered.
