### ISSUE TITLE
Adding a new Title field for sections

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1603]
### Is your feature request related to a problem?

No. Only a (useful) suggestion.

### What is the feature?

When building websites, we often use the section names for components such as breadcrumbs, page titles, URL schemes.

Usually, these names are chosen as short as possible (for readability) but never offer a greater possibility for our SEO efforts (a longer sentence with keywords). Currently, we have both the `Title` and the `Description` fields and (a sort of simple name improvement): adding a new field could be another natural possibility for SEO oriented pages but important and (IMHO) needed. It doesn't matter which label - e.g. `SEO title` - it's up to you (and the corresponding new tag associated).

**Comment by philwareham** [comment]
Seems not bad. Although if we were going to look at this I'd suggest it'e expanded to cover articles and categories too for consistency. Theoretically you could have both a title and SEO title for each of those that differ in their content (indeed, I use that method on a large Drupal site we administer).

**Comment by petecooper** [comment]
>a large Drupal site we administer

I feel your pain.

**Comment by petecooper** [comment]
Perhaps a continuation / extension of custom fields for sections, categories, etc?

**Comment by Bloke** [comment]
> Perhaps a continuation / extension of custom fields for sections, categories, etc?

This is planned, btw. Custom fields apply to articles right now but they can (and will) apply to:

* All content types
* Categories
* Authors/Users
* Plugins
* Comments(?)

Notice anything missing? Yep, Sections. The reason is that (currently) our Sections table doesn't have a numeric ID. The custom fields meta joining table requires an id as a foreign key. Although it would be more flexible to use a varchar, for sanity's sake I think we should insist on a numeric key. That means if plugin authors want to use them to augment their own tables, they can _provided those tables have a unique id key_.

This also prevents us (currently) using custom fields on Themes, Pages, Forms and Styles. That's no great hardship since the use cases for such tomfoolery are limited (although it does open up some seriously interesting possibilities, especially in Forms, for defining named parameter arguments or additional payload data per form that could be used for smooshing content in different ways through a single form). The only sticking point in the Presentation area is Section, which would really benefit from custom fields, as cara-tm indicates in the OP.

What we'll probably end up doing is retrofitting the txp_section table with an id column so it can be bolted into the custom fields implementation easily. Nothing else will use it and it'll (probably) remain invisible to the UI but we'll use it under the hood to link fields to sections.

In that regard, I'd be tempted to close this ticket as it will be covered by the CF implementation when that lands.

**Comment by philwareham** [comment]
Covered by custom fields branch work. Closing.
