### ISSUE TITLE
Make success messages disappear after short time period

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1607]
### Is your feature request related to a problem?

No

### What is the feature?

Making a suggestion that we automatically dismiss success alert messages in admin labels after a short period, to reduce unnecessary clutter. Note that it’d only be success messages. Error/warning messages should be persistent.

Needs someone with JS skills to implement (so, not me!).

**Comment by Bloke** [comment]
In principle, yes, but I have some reservations:

1) On some systems where this happens, it annoys me that I either know about the action and want to dismiss it quickly, yet have to wait until it auto-clears.

2) Sometimes I don't get a chance to read it and want to, because I get momentarily distracted or go to another tab while it's doing something that takes a short while, then turn focus back and the info's gone.

At the moment, it's great because I can slap ESCape and lose the message instantly if it's in the way, or leave it there until I do something else/move away. And if I accidentally hit escape before I've read it, I can hit it again to toggle the message back on to read it. I kinda like that.

So if we do put an auto-timeout on the messages, it should (imo) work in tandem with the escape mechanism in case you want to a) get rid of it sooner, b) read it again.

**Comment by bloatware** [comment]
Couldn't it be done via pure CSS by theme authors?

**Comment by phiw13** [comment]
> Couldn't it be done via pure CSS by theme authors?

Only partly. You can hide it after a set time via the themes animation mechanism (`@keyframes {}`), but you are still left with the object; and that is not great for AT, I think.
