### ISSUE TITLE
Allow multiple themes to be included at install time

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1612]
Proposal: allow multiple themes to be installed at time of installation.

Right now, the user selects precisely 1 from the 2 currently available (the default theme, or an empty one) during the install process…but when they're in the admin-side, they have scope to use more than 1 theme, and apply themes to sections, etc.

It's feasible that we might wish to bundle one or more front-side themes with Textpattern in future, and make more of a thing of how to include 3rd party themes in the install process, so I believe there's some merit to considering this.

**Comment by Bloke** [comment]
Great idea. One conundrum in terms of UX: presuming it's a multi-select dropdown or something, how do we let people choose which of the chosen themes are to be assigned to the content? You need one and only one "in force" at install time to be able to successfully assign them to sections, OR we'd somehow need to allow them to choose which sections receive which theme assets.

I think that's the main reason we only allow one selection at install time, and then permit import of the remainder after, because then you have the full interface available to assign assets and make development lanes and all that goodness.

If the 'make this one default' thing can be solved neatly during setup, then we can certainly consider allowing multiple themes to be installed at once.

**Comment by petecooper** [comment]
>If the 'make this one default' thing can be solved neatly during setup, then we can certainly consider allowing multiple themes to be installed at once.

Yeah, this - bang on. From a non-designer view point, using the existing menu works just fine, it's battle-tested and works. Perhaps something below there with checkboxes rather than multi-select, especially with mobile devices being as prolific as they are.

**Comment by philwareham** [comment]
I'd prefer not to over complicated the install procedure. Assigning to a theme after install would still be my preferred route. At least we can control the default/zero themes and know they work. Third party themes we have no control over.

**Comment by petecooper** [comment]
@philwareham - how about just our own themes (default, zero)?

**Comment by Bloke** [comment]
Not sure why you'd install both default and zero out of the gate, unless you wanted a blank slate to copy stuff from the default theme into (or to develop your own).

But then it's no real hardship to go Presentation->Themes, Import>Upload for the latter case or Presentation>Themes, select>Duplicate>Go for the former.

Having given this some thought, I'm not sure how we can still make the installation process easy while permitting more than one theme to be installed. It'd need a new UI element to allow selection of the 'active' theme from the available ones that have been chosen, which implies JavaScript and is therefore a bit messy.

Maybe when we rework the themes installation process to allow directives (perhaps in the manifest or as a separate XML mapping file) such as 'this theme is to be default' or 'use such-and-such assets for section so-and-so' then a multi-import might be more viable. Because you could then tailor it to your needs ahead of time and install many themes in one go, and make the site to your theme spec. That'd allow for some no-hassle boilerplate installs that draw from one or more themes in your arsenal.

I'm thinking that these directives can have a dual purpose. 1) be automatically applied on install, and 2) if you import a theme by hand from the UI, you'll get a second 'verification' step (like we do with plugins) where it'll show you what's coming in and what changes it's going to make. There you'll be allowed to turn off any of the directives you don't want - or reassign them (perhaps) to other sections in case they've been renamed in the database and don't match what's in the file. Essentially some kind of opt-in mapping system to save you having to import and then do the theme asset->section dance separately.

**Comment by petecooper** [comment]
Cool - thanks, both.
