### ISSUE TITLE
Email address as a valid authentication method for admin-side login

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1614]
### Is your feature request related to a problem?

Very minor.

### What is the feature?

Consider adding email as an authentication method for the admin-side login. Currently, we offer real name & username.

See https://forum.textpattern.com/viewtopic.php?id=51249 for discussion.

Considerations:

* users already using email address as their name or username, presumably with the same email address associated with their account
* any security implications for opening up email on login (we do this in some respects with password reset emails)

**Comment by dragondz** [comment]
In txp you can have many account using the same email, if leting people use their email for connecting you should enforce one email/one account rule.

**Comment by petecooper** [comment]
>In txp you can have many account using the same email

This is interesting. How does password reset work for accounts with the same email address?

**Comment by Bloke** [comment]
True. The unique is only applied to the login column. Forgot about that. Hmmmm. Tricky.

Password resets just get sent to the email address associated with the login name supplied in the reset box.

**Comment by petecooper** [comment]
>Password resets just get sent to the email address associated with the login name supplied in the reset box.

I should rephrase, my mistake. If >1 users have the same email address, and said email is used in the forgot password route (instead of the username), does Textpattern find the first then stop, or carry on for any/all matches?

I wrongly assumed emails would be unique, I'm now erring towards closing this. @dragondz @Bloke - what do you think?

**Comment by dragondz** [comment]
Hi, front end login form works using email or username for login and it works when there is only one email/login pair and fail otherwise, i dont know why not permitting this feature without changing txp and let it works when there is only one email/login pair and fail otherwise.

**Comment by Bloke** [comment]
Sorry Pete, I thought you meant the situation _now_. My bad. I replied regarding the admin-side login and admin-side reset currently only working with the login name, so there's no issue with multiple accounts using the same address. In fact, I use this feature (duh, forgot) to get round _thou can only log in with the same account on one device_ restriction when testing multiple browsers.

If we introduce login name and email address uniqueness, then I say we should lift the restriction on single logins per device. It is intensely annoying to hop to mobile to test some admin functionality on a small screen to find you need to log in and, worse, you've been kicked out of the desktop session and have to re-login there afterwards.

I know why it was introduced and it is indeed a good security measure, but over the years in everyday use, it's become more of a hindrance than a help to web development, imo. If we do away with that then I can go back to only having one account on a single site and login wherever I like using that account. Then the single unique email restriction wouldn't feel so much of a backwards step.

**Comment by Bloke** [comment]
There is, however, the issue of backwards compatibility. What would we do with upgraded sites that already have multiple email addresses in use? If we attempted to enforce uniqueness at the column level, MySQL would have a shit fit and it's not something we can reconcile on behalf of the affected user(s).

Therefore it would have to be a software-level restriction. I would guess it's not _much_ of an issue since the person using the same email address is likely to be an administrator trying to get round the problems of multiple logins being forbidden. But even so.

We have these edge cases to consider:

* Someone logging in using an email address instead of a login name: if we pick the first account that matches the email address, this would fail. If we tested each matching account until we found one that worked, that feels a bit, well, security-messy.
* Editing user info on the Admin>Users panel. If you go and alter an account that previously had a duplicate address, you'd be told you can't use this address after you hit save. So the first person that tries this is going to be inconvenienced. Sure, it's likely to be an admin so not much hassle, but a minor concern.
* What if you have a client pool for your site (I'm thinking front-end logins that use the txp_user table) and someone has forgotten their account and not bothered with the password reset? So they gave up and registered a new account instead - different login name, same email address. Should we flag duplicate accounts on the Admin>Users panel somehow? Either in a 'pre-flight' area at the top of the panel, or inline somehow in the table? Or perform this check in the Diagnostics panel?

Lots to think about.

**Comment by petecooper** [comment]
>Lots to think about.

Agreed. How about I park this for now? More pressing stuff to deal with, honestly.

**Comment by dragondz** [comment]
Hi Stef
In my opiniion should keep things simple:
Dont change the possibility to have multile account per email
If permit logging using email : If there is one email/login pair ok, if there is multiple account/email the login should fail that s with an error saying there is multiple account with that email all.

**Comment by Bloke** [comment]
> If there is one email/login pair ok, if there is multiple account/email the login should fail that s with an error saying there is multiple account with that email all.

Hmm, emitting an error message of that nature does leak information I'd rather not leak. We're quite militant about not revealing whether an account exists or not. Whether this remains a founded view, given that Google and Microsoft (among others) emit an error if an address doesn't exist _before_ you've even got to the 'enter password' step, is questionable.

**Comment by petecooper** [comment]
Closing this, status quo is fine.
