### ISSUE TITLE
Do not use "SET NAMES charset" query to set character set 

### ISSUE THREAD

**Issue by MioVisman** [textpattern/textpattern#1631]
### Is your feature request related to a problem?

example
```
$mysqli = new mysqli("localhost", "my_user", "my_password", "world");

// Will NOT affect $mysqli->real_escape_string();
$mysqli->query("SET NAMES utf8mb4");

// Will NOT affect $mysqli->real_escape_string();
$mysqli->query("SET CHARACTER SET utf8mb4");

```
### What is the feature?

example
```
// But, this will affect $mysqli->real_escape_string();
$mysqli->set_charset('utf8mb4');

```

https://www.php.net/manual/en/mysqli.set-charset.php

> This is the preferred way to change the charset. Using mysqli_query() to set it (such as SET NAMES utf8) is not recommended. See the MySQL character set concepts section for more information.

https://www.php.net/manual/en/mysqlinfo.concepts.charset.php

P.S. For PDO use

```
$dsn = 'mysql:host=HOST;dbname=NAME;charset=utf8mb4';
$user = 'dbuser';
$password = 'dbpass';
$options = [];

$db = new PDO($dsn, $user, $password, $options);
```

**Comment by bloatware** [comment]
Thank you. Our current (i.e. txp 4.8) minimal MySQL version requirement (5.0.3) is not fully compatible with
```
To use this function on a Windows platform you need MySQL client library version 4.1.11 or above (for MySQL 5.0 you need 5.0.6 or above). 
```
We could check db server version, but the equivalence between, say, MySQL and MariaDB versions is not clear. We will consider switching to 5.0.6+ in txp 4.9.

**Comment by vanmelick** [comment]
MariaDB / MySQL equivalence:https://mariadb.com/kb/en/mariadb-vs-mysql-compatibility/Database version EOL dates:https://endoflife.software/applications/databases/mysql (oldest supported version: MySQL 5.7.33, unless you count MySQL 5.6 which is supported until feb 5th 2021)https://endoflife.date/mariadb (oldest supported version: MariaDB 10.2.36)Still supported linux distributions (common server OS distros) and their database versions:https://wiki.ubuntu.com/Releases => Ubuntu 14.04 LTS: MySQL 5.5.62, MariaDB 5.5.63https://wiki.centos.org/About/Product => CentOS/RHEL 7: MariaDB 5.5https://wiki.debian.org/DebianReleases => Debian 8: MySQL 5.5.62, MariaDB 10.0.38WHM/cPanel: if you're on such a shared hosting platform which is kept up-to-date, you'll have at least MySQL 5.7 or equivalent MariaDB versions, because otherwise the WHM updates are blocked.DirectAdmin: https://help.directadmin.com/item.php?id=497 becomes EOL on CentOS 6 in 2024. That's the oldest distro (which is already EOL btw) where it is still supported. CentOS 6 has MySQL 5.1.73... but then you'd have no security updates due to CentOS 6 EOL.Plesk (Obsidian): oldest supported OS is RHEL 6 for which you'd have to purchase the extra ELS (extended life support) package if you want the bare minimum of security updates. In that case you'd have MySQL 5.1.73, but chances of a server admin paying USD 1500 per year for ELS in addition to RHEL (USD 1048 per year) for a simple shared hosting server are pretty much zero.So basically, if you're keeping your server OS up-to-date, you're running at least MySQL 5.5.62 or MariaDB 5.5.63.My point is that considering bumping the minimum required MySQL version to 5.0.6 for the next TXP version is perhaps a bit too conservative. You can safely bump it to MySQL 5.5.62 and MariaDB 5.5.63. Anyone using older database versions is on a system that is not updated and is probably not likely to update TXP as well (no point in doing it for security reasons if the OS itself is not up-to-date). One would expect new TXP installs to happen on fairly recently set up systems, not the antiquated ones I used as the lower limit below.CentOS 7 goes EOL on june 30th 2024, so you could keep the requirements static again, once bumped as suggested above, until that date.Regards,--RuudOn Feb 3, 2021 19:55, etc <notifications@github.com> wrote:
Thank you. Our current (i.e. txp 4.8) minimal MySQL version requirement (5.0.3) is not fully compatible with
To use this function on a Windows platform you need MySQL client library version 4.1.11 or above (for MySQL 5.0 you need 5.0.6 or above). 

We could check db server version, but the equivalence between, say, MySQL and MariaDB versions is not clear. We will consider switching to 5.0.6+ in txp 4.9.

**Comment by bloatware** [comment]
Thanks, Ruud, MySQL 5.5+ looks reasonable for txp 4.9. At least, we will assume that `mysqli_set_charset()` function is available and works as expected.

**Comment by petecooper** [comment]
I do get a bit twitchy when I see veeeery old MySQL (or store brand remixes) being on minimum specifications lists. This is a great step forward with newer (but still sensible) database version support.

Heavy +1 from me for bumping to MySQL 5.5 for Textpattern 4.9, that's much more appropriate. Thanks @MioVisman and @vanmelick for bringing this up, and thanks @bloatware for the pragmatism.

**Comment by petecooper** [comment]
Pinging @Bloke @philwareham  for comment – thoughts on MySQL 5.5 minimum for Textpattern 4.9?

If we're in agreement, I'll volunteer to put some words together to get people informed about the system requirements changes for the 4.9 releases.

**Comment by Bloke** [comment]
Yeah! No need to be wallowing in unsupported land. We can tighten a few things too and get rid of some tests for old workarounds, as we've already begun to do.

**Comment by philwareham** [comment]
Fine by me. I’m all for modernising the stack requirements in Textpattern 4.9 if it makes development easier. I’ve already removed support for ie11 in the back end for that reason.

**Comment by Bloke** [comment]
Anything more to do here? Or can we close it now the system requirements for MySQL are decided?

**Comment by bloatware** [comment]
I think it's done and still compatible with older MySQL versions. A check for the function availability does not hurt anyway, even on newer versions.
