### ISSUE TITLE
Allow reset the hour field

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1634]
### Is your feature request related to a problem?

No. An enhancement.

### What is the feature?

Sometimes we need to deal with dates and their timestamp format. In some cases when it is interesting to compare the current date and the published ones. Thanks to `<txp:posted format="%s" />`! 👍

By default, when we click on the "Set to now" button when we write a new article, the hour field is set to now. So, it can be difficult to compare some timestamps with this kind of scheme "%Y-%m-%d"...

Would it be interesting to add a reset button near the hour field in order to allow users to remove its content (and to get midnight time instead)?

**Comment by petecooper** [comment]
Salut Patrick - this feels like plugin territory to me, though I have no strong feelings in either way.

@philwareham - thoughts?

**Comment by Bloke** [comment]
I concur it feels more pluginish than coreish. There's already quite a lot going on there with all the input boxes to add more UI furniture.

However, perhaps when/if we refactor things(?) to use a single date field instead of a bunch of boxes, then the date picker we implement might be able to do something like this to reset the date to 'now' and leave the time alone, or set the time to midnight or (possibly better) midday or something.

The only reason I say midday is that our date handling is... interesting in core and has the potential to shift with DST and timezone changes. If you set an article to appear at midnight, it _can_ (at some times of the year) appear "published" at 11pm the day before. At least if you set it to midday, there's less likelihood of that happening so the Y/M/D permlink scheme (if you use it) and `<txp:posted>` date doesn't change.

**Comment by cara-tm** [comment]
Ok. Stef.

**Comment by philwareham** [comment]
> @philwareham - thoughts?

Not keen on core for this - it's edge case in my opinion and not something I'd want to add extra UI for, sorry!

**Comment by petecooper** [comment]
@cara-tm - thank you for your enhancement proposal - given the feedback from @Bloke and @philwareham I will close this issue, it would be better as a plugin.
