### ISSUE TITLE
RFC: expose Diagnostics as JSON endpoint

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1638]
### Is your feature request related to a problem?

No.

### What is the feature?

Expose Diagnostics panel information in JSON or similar format endpoint, behind an appropriate authentication method (e.g. HTTP auth per RFC 7235), to appropriate user levels (i.e. whoever currently has Diagnostics access).

Textpattern administrators might have multiple instances of Textpattern running across different domains, servers and hosting orgs. Administration of these instances would be more easily done with insight into the state of each, for example if upgrades need done, or preflight errors occur.

Having a method for a fleet of Textpatterns to be monitored from a given location, using a JSON endpoint for each and appropriate parsing at the client side would be beneficial. This could perhaps be done with a custom page and some http auth in the web server setup, but something baked into core might be an attractive option to server techs.

Tagged with RFC since this might be a really dumb idea. Please critique and comment without prejudice.

**Comment by Bloke** [comment]
Woah, a lot going on here. Let's see.

1. Exposing endpoints means we either need another authentication password or we extend the existing authentication password to be supplied over a different channel that's not covered by txp_auth.php (ot a bad thing, per se, just worthy of consideration given it's another attack vector). or... something else.
2. If going with user authentication, each site that you want to display on your 'diagnostics dashboard' (for want of a better term) means you need to log into each one before it'll spit out the JSON. Assuming good security practice that each of your sites uses a different password (which they should, but, y'know), faced with having to log in multiple accounts from a single location, most people would, I expect, store their passwords in plaintext to ease the burden, which is not a good idea since those accounts are likely to have Publisher-level privileges.
3. Give the above, some kind of salted token/hash auth method would be better. But if that token never changes or is easily rainbowable, then it's as useful as a bad password. Some mechanism to vary the token and trust it for a period of time would be better, but managing that seems heavy.
4. What data would we expose? Preflight? Low? High? Would it be obfuscated? COuld it be configurable when you make the request? Maybe. But Diagnostics still only shows some of the story of your site's overall "health". If there's a plugin issue, it might only show up when you view the front end, or a particular panel. If there's an error due to a PHP upgrade, for example, we can't serve the data anyway so you'll get a sea of error output on your dashboard depending on how good our failover is (in a way, that's good: it shows something's very wrong!)

Taking all the above into account, I'm leaning more towards leaving this to a plugin to expose core data in this manner. Somthing you install on each site you want to monitor, and that exposes the information over whatever channel you choose and via whatever authentication mechanism. It could even be done with smd_access_keys, as you intimate, to access a hidden 'section' of your site that spits out data via a JSON-encoded `<txp:header>`.

We could certainly make it easier to get at this data without making a plugin repeat core code. When we rebuild the panels in a more class-based manner to further separate the data from its display, this might be a nice goal to expose the underlying data via an API that plugins can call to get the data in a machine-readable format ready for display. I can see us using that approach for accessing (parts of) the Image data from the Write panel, for instance.

I can see the value in this, definitely, I'm just not sure of the methods of access that are available to us. If you have any ideas on a way of accessing the data that wouldn't burden the user in minutiae/key management, wouldn't potentially expose the server access credentials, or be subject to exploit, then it's worthy of exploring further for sure.

**Comment by petecooper** [comment]
Thank you, @Bloke – eloquent and measured as always. I'm erring towards plugin or hack territory, also, having given it more thought after your reply. I'll close this for now and reformulate at a later date when we're both a bit further down the road & I have some ideas for implementation.
