### ISSUE TITLE
'Excerpt' Persistent Cross-Site Scripting (XSS)

### ISSUE THREAD

**Issue by tusharvaidya16** [textpattern/textpattern#1645]
### Cross-Site Scripting (XSS)

When I enter malicious XSS payloads on the Excerpt field moreover I got a prompt. The XSS triggers and the attacker can able to steal the cookie according to the crafted payload.

### Steps to reproduce

1. Login into Textpattern CMS admin panel.
2. Now go to the Content > Write >  Excerpt.
3. Now paste the below payload in the URL field.

XSS payloads 

4. Now click on the Save button.
5. Now go to the articles page
5. The XSS will be triggered.

#### Additional information

Textpattern version:  4.8.4  

Web server : 
![textpattern_xss_1_excerpt_p_out](https://user-images.githubusercontent.com/30749153/109861724-a1ae9580-7c85-11eb-8190-0563c345b3b1.png)
https://release-demo.textpattern.co/

**Comment by Bloke** [comment]
Thank you for your interest in Textpattern.

Please see [Security considerations and user privileges in Textpattern](https://textpattern.com/weblog/security-considerations-and-user-privileges-in-textpattern). We believe this is not an exploitable issue and is by design to allow trusted authors to publish any content of their choosing. If a user is untrusted to publish content, they should not be granted access to the administration area.

**Comment by philwareham** [comment]
Not a legitimate issue for reasons outlined above. Closing.
