### ISSUE TITLE
function since($stamp) limitation for localisations

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1648]
Our current function...

```
function since($stamp) {}
```

...has some limitations when it comes to localisation. We expect a pattern of `x time ago` as in "4 days ago". However some languages require the reverse logic of `ago time x` as in "ago days 4" (e.g. Fulah language).

Can we code this in somehow, based on user's site language setting? i.e. if site language = `ff` then do the reversed logic? There's probably other languages that follow this pattern too (although it's not been flagged before).

Note: Fulah language is an LTR language.

**Comment by Bloke** [comment]
Sure, that's always bugged me. We swapped it out so that the `{since}` label was passed to the lang table, but that string is hard-coded as you say.

My first thought was to pass into the 'ago' lang string _two_ variables:

1) the singular/plural of the time period; and,
2) the actual value of the number of time_preiods ago

so the English lang string would then be something like:

```
ago => {qty} {period} ago
```

And ff.ini would then be:
```
ago => ago {period} {qty}
```

Slight upheaval for translations but a one-off exercise.

However, there is one fly - and I don't know if it's an actual issue or not because my knowledge of language conventions is limited - but we assume in the code that if the value is 1 then the singular noun applies. 1 day, 5 days, or 11 days. In other languages, maybe the singular always applies? Currently we'd get round that by defining 'day' and 'days' as the same translation. And that works fine.

But what if in, I dunno, Klingon the singular was used for _any_ value that ended in a '1'? 1 day, 5 days, or 11 day. Are there any such languages out there where the singular form of the noun is used for times that aren't represented by '1'? If so, we need a better system. If not, our current system will be fine and I'll hack `since()` now.

Anyone? Bueller? Anyone?

**Comment by philwareham** [comment]
Let's investigate as part of 4.9 cycle. Too close to 4.8.5 release to change now.

**Comment by Bloke** [comment]
Depends if you don't mind flicking the lang string for 'ago' to use a dual replacement now. I've just modified it in my local copy to do so, and it's better than we have now, whether or not the single/plural thing has any bearing. As you say, nobody's complained so far, so maybe there's nothing to it. So if you want to squeeze it in 4.8.5 and we can do the lang string stuff reasonably easily then I'm fine with that. Otherwise, 4.9.

**Comment by philwareham** [comment]
OPK, can you commit your change to the 4.8.5 branch and I'll carry the requirements over to translations.

**Comment by Bloke** [comment]
No probs. Is `{qty} {period} ago` okay? Kinda makes sense to me but if you prefer other replacement names, shout now.

**Comment by philwareham** [comment]
Yes that seems logical.

**Comment by Bloke** [comment]
One very minor caveat: in the 'a few seconds ago' case the string that is output is this:

~~~
 a few seconds ago
~~~

Note the leading space, because the `{qty}` will be replaced by an empty string and the space between it and the `{period}`is still there. That's a lang replacement issue and there's nothing we can do about it. HTML will swallow it, and if people care about the space they can use `<txp:posted trim />`. Just something to be aware of.

**Comment by Bloke** [comment]
Okay. See 2730fead.

**Comment by philwareham** [comment]
OK, translations updated. Thanks!
