### ISSUE TITLE
Tables overheat

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1653]
### Is your feature request related to a problem?

Not really but a kind of.

### What is the feature?

Some Textpattern tables are overheated during the production life of websites. That's the case for the `txp_discuss` (maybe `txp_discuss_nonce`), `txp_prefs` tables and depending on uses also the `textpattern` and `txp_plugin`. Core functions include a `safe_repair()` one. Did you project to call this function after processes are executed (write, update, delete)?

**Comment by bloatware** [comment]
The docs say 'normally you should never have to run REPAIR TABLE', but `safe_optimize()` could be beneficial on batch operations.

**Comment by Bloke** [comment]
We could look into offering table management options in Diagnostics, maybe? We list all the tables there, so it might be possible to borrow some of the functionality from rss_admin_db_manager to add a new step:

* low
* high
* tables

The third step would show all the tables and allow you to optimize/repair on a table-by-table basis if necessary, maybe? Is that of benefit or too edge casey?

I'd rather not automatically optimize/repair unless we're sure it's a safe operation. Maybe if we moved to more transactional, atomic database operations throughout core I might feel more confident doing that as part of far-reaching batch operations. Alternatively, it could be done on a simple schedule: perhaps every N admin actions, or a counter is flipped after at least 24 hours or a week or something since the last check, so that when the next admin panel visit is performed it runs a quick check/repair/optimize on tables that require it.

But doing that has the potential to cause errors on seemingly innocuous 'view the page' operations, so I'd rather lean towards giving people the option to do it themselves in Diagnostics. Plus, that means they can optimize plugin tables if they see fit.

**Comment by petecooper** [comment]
>I'd rather not automatically optimize/repair unless we're sure it's a safe operation.

+1. It's one thing explaining how this can be done with the right tools for the job (CLI, GUI) but this scares me a little.

**Comment by Bloke** [comment]
@cara-tm and others: please try out branch diag-tables. It's pretty much a copy of rss_admin_db_manager's table pane with options to repair/optimize IF the database engine supports it. Currently (for repair) that means MySQL MyISAM tables *only*.

When we move to PDO, this panel will only be able available if your chosen driver is MySQL, but I guess we either live with that, or not bother with this feature. I'm happy either way if it's useful. It's not much code either way.

Thumbs up / down?

**Comment by petecooper** [comment]
>[…] please try out branch diag-tables

https://github.com/textpattern/textpattern/archive/refs/heads/diag-tables.zip

**Comment by Bloke** [comment]
Tagging tentatively with 4.8.6. If we keep this, great; not too invasive for a patch. If we decide it's a crap idea, the branch can silently disappear.

**Comment by bloatware** [comment]
Can we test it in local `diag-tables` branch? I don't find the magic button...

**Comment by Bloke** [comment]
Yep. Diagnostics dropdown. Pick the third 'Tables' option.

**Comment by bloatware** [comment]
Fine! Is it checking for missing tables/fields too?

**Comment by Bloke** [comment]
It isn't, but it could. We know the expected fields in Textpattern\DB. There's already `checktables()` in the high diagnostics step but I think it just checks tables exist.

**Comment by Bloke** [comment]
SIde note: as it stands right now - if we keep this feature - it reads all tables and allows you to optimize/repair them all. Even plugin tables.

If we went down the route of checking fields, we'd have to probably _not_ look at the plugins and instead iterate over the tables defined in Textpattern\DB\Tables\. Or consider all tables but only do this extended checking of fields on core tables if they have definitions in a .table file.

Part of me thinks we should only check core tables, but if your system as a whole is misbehaving due to data corruption, why not allow plugin table repair too, since it may be the plugin tables that need fixing?

**Comment by bloatware** [comment]
Repair for all tables is fine. Later we could introduce a standard way for plugins to add/alter tables via their definitions. Then we could scan plugin dir for these definitions and check plugin tables too. We could probably even install missing stuff at repair step.

**Comment by Bloke** [comment]
I was thinking that too about the definition files. If they're in the same .table format as we use, game on. MySQL only, again, of course since other database vendors will use different types and conventions.

**Comment by bloatware** [comment]
If there is a way to abstract table manipulations in PDO and this requires changing `.table` format, we can do it, I guess. Merely speculating here, I have no PDO experience.

**Comment by Bloke** [comment]
Actually, I presume (not checked) that PDO will accept standard format SQL92 format queries. So CREATE TABLE _should_ use the standard syntax across database  - even things like SQLlite and PostgreSql should work and if there are any idiosyncracies in implementation details under the hood, I'd hope that PDO would abstract them away. Otherewise implementation would be 'if such-and-such-driver, use this syntax' which negates the point of PDO being database agnostic.

However, what we can't do (as far as I can tell) is offer to repair tables other than MyISAM and repair/optimize MyISAM and InnoDB. From reading around it seems these two queries are MySQL (and presumably their off-brand forks) specific.

So for database drivers other than MySQL we can either allow them to see the tables and any issues - and if we can check table integrity re: expected fields and sizes then this has value - but simply omit the 'actions' column. Alternatively, omit the Tables feature entirely for non-MySQL drivers.

**Comment by Bloke** [comment]
Added rudimentary field/type checking on tables in f1277487. Doesn't catch situations where you add columns. We could do more, and I'm not sure the reporting aspect is much use right now but if you muck about with the database schema (e.g switch INT to SMALLINT or TINYINT or rename a column like 'permissions' in the txp_file table (which is unused so is safe) then it will display the number of expected fields, and the number it found not matching, plus list which fields were affected.

Not pretty. Ideas welcome if we intend to keep this feature.

**Comment by Bloke** [comment]
btw, it doesn't check field widths. Again, we could if we thought it was worth it. We pull out CHARACTER_MAXIMUM_LENGTH from the schema so could extract the size from `type(size)` definition in the .table file and use it. At the moment I strip it off and compare.

Again, thoughts or code improvements welcome.

**Comment by Bloke** [comment]
Incidentally I don't know if INFORMATION_SCHEMA is MySQL specific. Searches so far have been inconclusive. If anybody knows or has a resource that indicates whether we can use it under PDO for all database types, that'd be grand.

Not that we're using PDO right now, but I want to keep an eye on the future so we don't add features that can't be implemented easily when we switch.

**Comment by cara-tm** [comment]
Sorry Stef I didn't see these comments...
So, this is your plugin into the Core; am I right?
Useful! A simple way to all site owners for database optimization.
Just a detail. Please, could you change the @0 o@ notice by this one instead (more significant) @0 octet@.

**Comment by petecooper** [comment]
How far away (time- or work-wise) are we from folding this into `4.8.6`, @Bloke? Is it still appropriate for a patch release?

**Comment by Bloke** [comment]
This is branched off 4.8.6. It can go in at any time if we think it works and is appropriate for core. If not, we can either shelve it (i.e. leave for plugins) or defer it to a later release.

I'm not fussed either way. If it has value to us (for diagnostics) and users (for not having to round-trip to their hosting control panel) then I'm fine keeping it as a core component. My only reservation is that this is only of benefit for MySQL and its equivalents.

So when we move to PDO, the panel will likely be hidden if you're using a different driver (or, at minimum, becomes read-only since no other database vendors seem to offer the same 'repair' and 'optimize' SQL commands - I might be wrong but I can't find docs on any of them with regards fashioning queries from PDO). That to me smacks of bloat/a waste of space, since there are, what, 11 or 12 drivers built into PDO and we're adding a panel that can only be used for one of them?

My gut says leave it for a plugin but introduce a callback suite on the diagnostics panel to allow things like rss_admin_db_manager to integrate with it, rather than on its own Extensions panel. Seems a more logical place for it.

If we decide to lose this branch, no foul: I'll copy the code back into rss_admin_db_manager because it's done better in this branch compared to how it's done in the plugin.

**Comment by petecooper** [comment]
> On the flipside, when we move to PDO, how many people will take up the feature and migrate to MongoDB or SQLite or Postgre or SQL Server et al? If the answer is not many then this panel still serves the majority and therefore has value.

>My gut says leave it for a plugin but introduce a callback suite on the Diagnostics panel to allow things like rss_admin_db_manager to integrate with it, rather than on its own Extensions panel. Seems a more logical place for it. And then other diagnostic-type plugins could crop up on there too.

+1, honestly. PDO is some time away, and given our user base we'll still likely have a sizeable chunk (many or most) using MySQL because it's on their hosting and it works.

>If we decide to lose this branch, no foul: I'll copy the code back into rss_admin_db_manager because it's done better in this branch compared to how it's done in the plugin.

I like this idea a lot. Would that cover @cara-tm's OP for this issue? It sounds like it probably would.

**Comment by cara-tm** [comment]
Sure! But I admit you make a huge work Stef!
My question was: "Why not add `safe_repair()`/`safe_optimize` function when some TXP process were made?"

**Comment by Bloke** [comment]
Because they're potentially invasive, especially on large tables. I don't know what those functions do under the hood - maybe reindex or something, but doing them at the end of operations has the potential to be somewhat expensive. Imagine a site with 20K articles or 50K images. You save an article or an image and it does an optimize/repair operation. You wait. And wait. And wait.

I'd rather these functions were opt-in than mandatory.

**Comment by Bloke** [comment]
P.S. I'm 90% of the way through tweaking the txp_diag panel to accept plugins and have refactored rss_db_admin_manager to sit in that panel. One major hurdle to overcome. If I can beat that, the concept of custom steps might have legs and can perhaps be rolled out to other panels. It's only a few new callbacks so nothing invasive, but the potential it opens up to cut down on the amount of code in things like smd_user_manager and various other plugins that augment core functionality, it might be generally useful.

**Comment by Bloke** [comment]
Okay, please give this a whirl:

* Pull down 4.8.6 branch, to at least commit 144cb02ed5, which introduces a few panel-level callbacks
* Install the [diag-panel branch](https://github.com/Bloke/rss_admin_db_manager/tree/diag-panel) or rss_admin_db_manager.

That installs the plugin inside the Diagnostics panel and adds links to the three panels to the Details level dropdown. Not rigorously tested yet but it seems to work fairly well.

Using this same approach of allowing plugins to register their own steps in each panel, we could let plugins do some seriously cool manipulations of the admin side. Please if you test this, also try and break it. It should _not_ be possible to overwrite or meddle with the core's 'low' and 'high' steps. There's nothing to stop you registering your own handler and adding content to the end of what core outputs or, in the case of rss_admin_db_manager, replacing it entirely with your own content.

Look at the way the plugin hooks into the `steps` callback to see how it's done.

@bloatware Do you think this kind of approach could be rolled out to other panels? It's pretty simple to add a single callback and tweak the step handling code on each panel so the core routines are sandboxed and untamperable (so people can't overwrite core functionality) but plugins can play in a slightly better manner than they currently do by hooking into save/edit steps. Any improvement welcome.

**Comment by petecooper** [comment]
@cara-tm – is the post above (https://github.com/textpattern/textpattern/issues/1653#issuecomment-818076099) something you would be able to test?

**Comment by petecooper** [comment]
Call to action here: "$":https://forum.textpattern.com/viewtopic.php?pid=329914#p329914

**Comment by philwareham** [comment]
This is the final blocker for 4.8.6 - can you give an update on current status? Thanks.

**Comment by Bloke** [comment]
No blocker as far as I'm concerned. I think the plugin solution does the job and I've not noticed any ill effects.

Anyone who's willing to try and break these callbacks from a security standpoint (e.g. to stomp on what core outputs on this panel or the Users panel), do so. Seems as robust to me as before, but it's always nice to have someone more rigorously test.
