### ISSUE TITLE
Custom form template types, wildcard title vs named language title

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1660]
### Expected behaviour

This code…:
```
[shortcodes]
*="Shortcodes (all)"
```
…should be a catch-all and display "Shortcodes (all)" as the title for the `[shortcodes]` custom form type.

### Actual behaviour

The custom form type is displayed as "shortcodes".

![Screenshot 2021-03-22 at 09 29 13](https://user-images.githubusercontent.com/226578/111968512-222c1d80-8af1-11eb-91dd-7a362e19794f.png)

Overriding the title with this code…:
```
[shortcodes]
en="Shortcodes (en)"
```
…works just fine, and displays the title as "Shortcodes (en)":

![Screenshot 2021-03-22 at 09 29 32](https://user-images.githubusercontent.com/226578/111968552-2a845880-8af1-11eb-931d-a21da30357c8.png)

### Steps to reproduce

Enable advanced options and use this code in Advanced Options:

```
[shortcodes]
*="Shortcodes (all)"
```

![Screenshot 2021-03-22 at 09 30 54](https://user-images.githubusercontent.com/226578/111968692-599aca00-8af1-11eb-9e3e-04482f6f2bb4.png)

#### Additional information

Textpattern version: 4.8.5-dev

PHP version: PHP 8.0

**Comment by bloatware** [comment]
IIRC, `*` wildcard worked in pre-release versions, when title was the only custom forms parameter. But since the introduction of `mediatype`, it was deprecated in favour of `title`, to avoid any ambiguity:
```
[shortcodes]
title="Shortcodes (all)"
en="Shortcodes (en)"
```

**Comment by philwareham** [comment]
Just hijacking this thread, it would be very handy if we could define the above in a packaged theme along with it's corresponding directory.

Currently I believe we have no way of supplying additional folders in the theme forms directory over and above the standard `misc`, `article`, `links`, etc. so will I have to include my shortcakes in the `misc` folder for now.

**Comment by bloatware** [comment]
I don't even know what happens on theme import if `forms` contains non-standard subfolders. I guess we will need to revisit the hard-coded part of it in cf branch, but have no idea for 4.8.5. What if a theme tries to add an already existing custom type which are currently shared by all themes? Can we have per theme prefs?

**Comment by petecooper** [comment]
>But since the introduction of mediatype, it was deprecated in favour of title, to avoid any ambiguity

Ah, that makes sense. I was cribbing from .com, I've just updated the options there.

**Comment by Bloke** [comment]
At the risk of derailing this issue further (should we open a new one to track this?) in 4.9 I want to think about possibly moving this setting from Advanced Prefs to the Forms panel itself, so the media type is a part of the Form definition (i.e. in the txp_forms DB table). This should allow form types to be created (those that don't already exist) on the fly during theme installation/update.

We'll have to think about how to handle what happens if a type already exists but I expect that can be handled quite neatly by adding a 'theme verify' step just like we do with plugins. So when you install a theme it reads all the metadata and (potentially) prefs and maybe even plugins bundled with the theme and whatnot, then presents you with an 'intent' panel: this is what is gonna be installed. Any clashes can be highlighted and you can be given the option via a series of checkboxes to decide what parts of the incoming theme you want to install/overwrite. Theme updates might be trickier as they affect Forms/Pages/Styles only so if a new Form is on disk and it's in a different group to before tat doesn't exist in the database the type will need to be created. But if it already exists, well, not sure what's best.

In any case, I'm not sure language strings should be supplied. Do they hold intrinsic value to name groups in different languages in this manner? Would they be better served via a Textpack that's installed alongside? If so they should be handled by txp_lang. Otherwise, just name your custom form types in one language.

Not sure what the media type of the existing form types should be. HTML, I guess.

**Comment by petecooper** [comment]
>At the risk of derailing this issue further (should we open a new one to track this?) 

Yes, we should. OP is a non-issue now I understand it, so take this elsewhere so we don't lose valuable discussion. Perhaps fork from https://github.com/textpattern/textpattern/issues/1660#issuecomment-803956625 ?

**Comment by Bloke** [comment]
Done #1661 .
