### ISSUE TITLE
Deprecate txp:search_result_count tag from 4.9.0, replace with `items_count`

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1726]
Since this tag now counts articles as well as search results – and can do so before or after a corresponding `<txp:article>` tag – is it about time we renamed it?

See https://forum.textpattern.com/viewtopic.php?id=51496 for discussion.

Easy win to rename the function and throw a deprecation warning on the old tag stub function name for a few versions.

Current leading tag name suggestion is: `<txp:items_count/>` which leaves scope for counting other 'stuff' via a `type` attribute or something in future.

Anyone got any better ideas or comments?

**Comment by petecooper** [comment]
+1 from me, and I like `items_count` a lot.

**Comment by petecooper** [comment]
> is it about time we renamed it?

Given the frequency we have people changing their site designs (not often) and falling foul of tag changes on upgrades (more often), I'd be inclined to suggest we introduce `<txp:items_count/>` with the desired functionality, deprecate `<txp:search_result_count>` for a release series or two, and then bin it.

**Comment by petecooper** [comment]
Bumping for a straw poll on inclusion in 4.8.8, push to next patch (if we're doing that) or 4.9.

Paging @Bloke @bloatware @philwareham for consensus.

**Comment by bloatware** [comment]
This is not hard to do if we agree on the name.

**Comment by philwareham** [comment]
`items_count` sounds fine to me, yes!

**Comment by petecooper** [comment]
@bloatware - if you're broadly comfortable with `items_count`, we have a consensus!

**Comment by bloatware** [comment]
Fine. Should we deprecate it right now (and then update the default theme) or wait for 4.9? I would wait.

**Comment by petecooper** [comment]
My 2c: wait for 4.9, more eyeballs will see it in the release notes.

**Comment by Bloke** [comment]
We could simply add it as an alias tag in core now, mention it as a line item in the changelog and redirect to the new tag in the docs only? Then officially deprecate it in the next release. Or just do the entire thing next time around. it's not a deal-breaker for me either way.

**Comment by petecooper** [comment]
If it's straightforward to do,  I really like @Bloke's approach in https://github.com/textpattern/textpattern/issues/1726#issuecomment-993003830

Bearing in mind there will be a longer gap between releases if we're going to 4.9, it makes sense to have people start using it sooner rather than later, get a head start, whatever. So, proposed POA:

- [ ] introduce `items_count` for 4.8.8 (in whatever way you see most appropriate)
- [ ] mention in release notes
- [ ] mark deprecated tag(s) as deprecated from 4.9.0

Sound like a plan?

**Comment by bloatware** [comment]
[Aliased](https://github.com/textpattern/textpattern/commit/0f659c149495597eb3b8fd5eb5e0142fe16d268a)

**Comment by petecooper** [comment]
So, presumably, if we can spin out a doc for `items_count`, and make mention in `HISTORY.txt`, this is all that's needed for 4.8.8, right?

**Comment by petecooper** [comment]
I'm gonna update the title to this shortly, since we're at a point that it's ready for 4.8.8 (via https://github.com/textpattern/textpattern/commit/0f659c149495597eb3b8fd5eb5e0142fe16d268a - thanks @bloatware). We can do the docs tweaks after 4.8.8 beta 1 is out.

Given future plans, it feels sensible to mark as deprecated from 4.9.0.

**Comment by bloatware** [comment]
Delegated to https://github.com/textpattern/textpattern.github.io/commit/9cd6eacff913b5731a4e8e2d427db9e035d28782
