### ISSUE TITLE
`max_url_len` does not warn or truncate article's `url_title` if it's too long, throws front-side error on viewing

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1731]
### Expected behaviour

When `max_url_len` is set, an advisory or warning should be shown when an article `url_title` is too long.

### Actual behaviour

An article with a `url_title` can be published, but viewing the article shows an unstyled "Nice try." notification and a 503 status.

### Steps to reproduce

* Set `max_url_len` to 50
* Publish an article with a title of 'Lorem ipsum dolor sit amet, consectetur adipiscing elit viverra.'
* View the article.

#### Additional information

Textpattern version: 4.8.7

Web server vendor and version: Nginx 1.21.1

Database server vendor and version: Percona 8.0.25-15

PHP version: 8.0.9

**Comment by bloatware** [comment]
That's tricky, since the length of an URL depends on its scheme: switching a section to `breadcrumb/title` can make its articles URLs much longer than they were in `title` scheme. And we can not take the scheme into account on check-ups, since they are done before the scheme is detected, to protect this very detection from extra-long strings.

I'd say set `max_url_len` to 1024 and don't care?

**Comment by petecooper** [comment]
>but I'd say rather set the latter to 1024 and don't care?

I'm erring towards this. What's the reason for having it, anyway? The pophelp isn't very specific.

**Comment by bloatware** [comment]
It is not the max length of URL that txp will produce, but this of incoming URLs (including search terms etc) txp will accept to treat. The treatment includes, for example, splitting URLs by `/` into an array, which can become too large if a malicious URL is too long. So it's just a usual protection from users input. We actually shouldn't expose this value, but it is not clear what is a reasonable length.

**Comment by petecooper** [comment]
Thank you @bloatware – I'll re-close, I'm clearly being nitpick-y!

**Comment by bloatware** [comment]
@petecooper not at all, you just need to modify the issue title. Shortening `url_title` would not solve the problem, since `max_url_len` filter applies to all URLs (in particular, search terms length is taken into account too). Save for replacing 'Nice try' with something more informative, dunno what we can do.

**Comment by petecooper** [comment]
Understood. I'll leave this closed and reconsider for another issue with a revised scope.
