### ISSUE TITLE
Add db-level check for 'table exists'

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1751]
#### Background

Sometimes plugins need to do something only if a table exists or not, e.g. populate data on first install but not on subsequent upgrades.

Using any of our `safe_*()` calls to find this information results in txplib_db throwing a warning/error in debugging mode, which is ugly. `safe_show()` or `safe_row()` or `safe_query` etc will all complain.

According to [stack overflow](https://stackoverflow.com/a/24623531) the fastest way to test for a table's existence is to execute `SELECT 1 FROM table LIMIT 1` and then test `mysqli_errno` for the magic constant 1146 (ER_NO_SUCH_TABLE).

Sadly, this cannot be done via our `safe_*()` calls at present which means plugins must go back to bare metal to do it. Reference: https://github.com/Bloke/smd_user_manager/commit/812894f97b21eef50c6947d58729aa9d121fa666

#### Proposal

Introduce `safe_table_exists()` which does the above and returns true/false if the given table (tables?) exist.

Caveats: I expect this magic number is very MySQL specific so if there's a better way of testing for a table's existence that won't explode when we move to PDO, it would be preferable. Further investigation reveals:

```
SELECT count((1)) AS ct
FROM INFORMATION_SCHEMA.TABLES
WHERE table_schema = 'yourdatabasename'
AND ( table_name = 'yourtablename' OR table_name = 'yourtablename1' OR ... );
```

But again, is INFORMATION_SCHEMA a MySQL convention or does it work across the board for PDO?

**Comment by MioVisman** [comment]
https://dev.mysql.com/doc/refman/8.0/en/information-schema.html

You can use INFORMATION_SCHEMA for both pure mysql_ *, mysqli_ * and PDO MySQL. 

```
SELECT 1
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = :table
```

**Comment by Bloke** [comment]
Thanks, @MioVisman that's great to know. Thank you for digging that out. Looks like this is possible then. I'll take it and see what I can do.

**Comment by vanmelick** [comment]
Benchmarks!

Generate files with each 10.000 times the same query. Doing this in a separate step, because I found generating the files took way more time than actually executing the queries:
```
seq 10000 | xargs -I{} echo "SET @noop = null;" > noop.sql
seq 10000 | xargs -I{} echo "SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'txp_textpattern';" > information.schema.sql
seq 10000 | xargs -I{} echo "show tables like 'txp_textpattern';" > show.tables.sql
seq 10000 | xargs -I{} echo "select count(*) from txp_textpattern;" > select.count.sql
seq 10000 | xargs -I{} echo "select 1 from txp_textpattern limit 1;" > select.limit.sql
```
How much time does it take to do pretty much nothing at all. Just to get an idea what the lower limit is of running 10.000 SQL commands.
```
time cat noop.sql | mysql bunscom > /dev/null
real    0m0.337s
user    0m0.075s
sys     0m0.073s
```
The standard way. Should work in at least MySQL and PostgreSQL, but NOT in something like sqlite. For PostgreSQL, see:
https://www.cybertec-postgresql.com/en/show-tables-in-postgresql-whats-wrong-with-it/
```
time cat information.schema.sql | mysql ruud > /dev/null
real    0m1.791s
user    0m0.216s
sys     0m0.143s
```
The most easy to understand method, but MySQL-only.
```
time cat show.tables.sql | mysql ruud > /dev/null
real    0m1.885s
user    0m0.154s
sys     0m0.146s
```
Slightly faster and works fine when the table exists, but really ugly because you're intentionally creating an error and it wouldn't surprise me if the error is logged somewhere so you don't want to do this too often. Not sure if this works in other databases than MySQL. 
```
time cat select.count.sql | mysql ruud > /dev/null
real    0m0.845s
user    0m0.131s
sys     0m0.127s
```
Pretty much the same as with the select.count query.
```
time cat select.limit.sql | mysql ruud > /dev/null
real    0m0.941s
user    0m0.181s
sys     0m0.091s
```
Running these benchmarks multiple times, I see around 10% variation in timing results. Did this on a production server with very little traffic, but not completely idle. I've tested with almost empty tables, large tables and non-existent tables. All three give approximately the same results regardless of the method used.

Even the "slowest" methods use less than 20 microseconds to run, so yes, the information_schema method is fine. If you plan on never supporting anything but MySQL (and MariaDB), then "show tables" could be an alternative, but since there's not speed advantage, go for information_schema

--Ruud

**Comment by Bloke** [comment]
That's fantastic work, thank you @vanmelick. Looks like the information_schema is the approach to use, the most widely adopted, and will work with PDO when we get round to it.

**Comment by Bloke** [comment]
That should do the trick. Please give it a grilling. You can either specify a single table, a list of tables, or an array of them. The function will return TRUE if ALL the given tables exist.

``` php
$res = safe_exists('smd_thumbnail');
$res = safe_exists('smd_thumbnail, txp_image');
$res = safe_exists(array('smd_thumbnail', 'txp_image'));
```
