### ISSUE TITLE
Publishing articles where no sections exist

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1765]
Caveat: possibly edge case-y, open to advice. Client is coming from Wordpress (doesn't like Gutenberg), so their patience is already worn a bit thin.

Scenario: fresh Textpattern instance as a playground, default content stripped out, no sections, no articles.

Publishing a new article where no section is chosen (because there are none in this case) throws a "Unknown section" error. While this is semantically accurate, it could be a bit friendlier / useful. Should we consider an alternative gTxt to advise the user that a section is required? Not sure if we need to hand-hold as far as creating one, but it might not hurt to throw a link to Sections.

![Screenshot 2021-12-25 at 10 14 37](https://user-images.githubusercontent.com/226578/147382918-a1a4fd69-ee48-4302-811a-4a4bd0aee8e1.png)

**Comment by Bloke** [comment]
Better wording is fine if you can dream something up. Just check it still makes sense on the front end because I believe the same string is used there. You can usually trigger it by making a pageless section then writing an article assigned to it and hitting View from the Write panel.

**Comment by petecooper** [comment]
>Just check it still makes sense on the front end because I believe the same string is used there.

Yes, exactly. That front-side offering feels fine, if a little cryptic, but we don't leak any info. Tagging https://github.com/textpattern/textpacks/issues/309 for reference.

Could we re-use `no_sections_available`? That would currently throw "No sections available." instead of "Unknown section". I don't know the complexity of assigning it for just this scenario (i.e. publish article where no section is assigned), so I'm open to advice on how much of a bum ache this would be to address.

**Comment by Bloke** [comment]
Good find. `no_sections_available` makes more sense. Lemme see what can be done to swap it out for that.

Related: https://github.com/textpattern/textpacks/issues/309

**Comment by Bloke** [comment]
Right, `no_sections_available` is in the `[tag]` group, so only available to the tag builder at present. But if we shift it from there to the `admin-side` group, that would work fine.

I'm always a bit wary of just moving strings at the code level in case it stuffs up Crowdin synchronisation, so I'll defer this part to @philwareham. If we have a way of moving strings en masse in Crowdin (do we? or does it need to be done by hand?) then pulling them into our Textpack repo and finally across to dev, it's a potentially smoother workflow and perhaps a little less work (umm, I think). Not sure.

**Comment by petecooper** [comment]
Nice one, @Bloke - there are a few housekeeping bits and pieces to do in https://github.com/textpattern/textpacks/issues, so I'll open an issue over there to track this.

**Comment by petecooper** [comment]
To do:

- [ ] https://github.com/textpattern/textpacks/issues/310 (@philwareham)
    - [ ] update gTxt for article with no section (@Bloke), depends on above

**Comment by philwareham** [comment]
So, to clarify, you want:

1. `no_sections_available` in Textpack `admin-side` group
2. `unknown_section` in Textpack `public` group
3. Remove `unknown_section` from `mode.ini` file

Let me know if above is correct.

**Comment by Bloke** [comment]
Yes but... just checked and we also use unknown_section if you try and hack the section edit process. e.g. visit Presentation>Sections, click to edit a section then alter the URL's `name` parameter to a section that doesn't exist (or you don't have permissions to access). So let's go with:

* `no_sections_available` in Textpack `admin-side` group.
* `unknown_section` in Textpack `common` group.
* Remove `unknown_section` from mode.ini file

**Comment by philwareham** [comment]
OK, I've revised the strings as requested. Over to you!

**Comment by Bloke** [comment]
Drat. I have an inkling that the reason we use `unknown_section` on the Write panel is because the section validator doesn't necessarily know if you have no sections vs you've renamed it or borked it somehow.

Consider this:

* User A starts writing an article in section 'blog'
* User B (or user A in another tab) renames section 'blog' to 'news'
* User A hits Save/Publish on the article.

Result: the section is 'unknown' because it's been moved/renamed. It's not because we don't have any sections at all.

Granted, that is an edge-casey scenario and the case Pete highlighted with the zero theme is more likely to be encountered, so I'm happy to proceed with using `no_sections_available`. Just noting here for the record that the new message could be equally misleading in the scenario I outlined above.

Whether it's possible for the validator to distinguish between "no sections at all in the DB" and "someone has hacked the DOM or removed the section someone is trying to use" I'm not sure. I suspect it could be done but would possibly require an extra query, which pollutes the validator code. But the section list might be available in a global which, although yucky, at least doesn't come with the performance overhead.

**Comment by Bloke** [comment]
Done in 4.8.8 (since the strings have been moved now anyway). Please test.
