### ISSUE TITLE
If available, show server load in High diagnostics

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1767]
### Is your feature request related to a problem?

Nope.

### What is the feature?

If we can show the server load average in High diagnostics, we should - useful for support cases where server responsiveness may be impacting Textpattern performance.

Notes: https://www.php.net/manual/en/function.sys-getloadavg.php

**Comment by Bloke** [comment]
> Note: This function is not implemented on Windows platforms.

Soooo, bypass it somehow if not *nix?

**Comment by vanmelick** [comment]
On 2021-12-25 15:39, Pete Cooper wrote:
> Notes: https://www.php.net/manual/en/function.sys-getloadavg.php

You would have to divide that by the number of cores, otherwise it's 
meaningless. See comments in the manual for that function for ways to do 
that. And if you're fetching info from /proc/ try to get the CPU wait 
time as well, because that tends to be a good indicator of I/O issues.

--Ruud

**Comment by petecooper** [comment]
@vanmelick - yes, exactly that…although if there's some visibility from the admin who knows it's a 4x core CPU, then a load average might be a quick-and-dirty metric. I'm not suggesting we go down the "netdata":https://www.netdata.cloud route, but some basic metrics on server load might be useful.

**Comment by petecooper** [comment]
Gut feeling says this is plugin territory. Closing.
