### ISSUE TITLE
RFC: add a link to view the article section on the article panel

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1771]
### Is your feature request related to a problem?

Nope. It's a convenience feature.

### What is the feature?

Link to view associated parent section (implying an article list) from either the `txp-write-sort-group` or `txp-article-actions` panels on article page.

Example: I publish an article called "Lemons" in the "Fruit" section of a site. I can use the 'View' link to see what "Lemons" looks like at the article level. I can use the site root link in the top bar (`txp-view-site`). It's not clear to me how I can see the section landing page - the glue between the site root and the article in a lot of cases.

Perhaps a duplicate link in the lower panel that copies the 'View' link, that seems to tally most with the Section being shown there…or a link to the article parent / section in the top panel.

Viz:

![Screenshot_2021-12-29_at_17_57_35](https://user-images.githubusercontent.com/226578/147690925-bbce0461-96eb-4d63-9c13-8b5894e3cba5.png)

**Comment by Bloke** [comment]
I do (did) kinda like this idea, but I'm not sure if it would clutter things on the Write panel, given that you can click 'Edit' alongside the section and then click 'View' to see the landing page of any section from that panel.

Yes, two clicks instead of one. The downside to this proposal is we would need some kind of javascript intervention on the Write panel at click time to read the current state of the dropdown and populate the section link, which adds further weight to the page.
