### ISSUE TITLE
Fresh eyes for `v4.8.8` branch

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1777]
I am 99% sure all the stuff from `v4.8.8` has made it into `main`, either during the beta or GA release process, but I don't want to zap the branch just yet if that's not the case.

I would appreciate additional eyes to make sure `main` actually _is_ 4.8.8, and then I can safely remove `v4.8.8`, or someone else can. No major hurry, just be aware `v4.8.8` is hanging around until it's confirmed able to be put to pasture.

Thanks!

**Comment by philwareham** [comment]
I've done a test merge into `main`and it's not showing any additional files, so I take that as it being fine (and I can see 4.8.8 commits in the `main` branch as expected). 

FYI `main` is never worked on directly, so there's no reason for it to have merge conflicts anyway (as we branched from `main` to `4.8.8` in the first place, and there would be no commits since then).

**Comment by petecooper** [comment]
Thanks Phil - I'll tidy up.
