### ISSUE TITLE
4.9-dev + PHP 8.1, error (strftime() is deprecated) when installing a plugin

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1780]
### Expected behaviour

silence

### Actual behaviour

Installing a plugin, either by pasting in the `textarea` or uploading a `.php` file, results in an error message at the (p)review stage:

```
8192 "Function strftime() is deprecated"
in /Users/username/Sites/_phiw13/textpattern/vendors/Textpattern/Security/Token.php at line 138.

textpattern/vendors/Textpattern/Security/Token.php:138 adminErrorHandler()
textpattern/vendors/Textpattern/Plugin/Plugin.php:650 Textpattern\Security\Token->generate()
textpattern/include/txp_plugin.php:542 Textpattern\Plugin\Plugin->generateToken()
textpattern/include/txp_plugin.php:795 plugin_verify()
textpattern/include/txp_plugin.php:54 plugin_upload()
textpattern/index.php:231 include()
```

The plugin installs correctly

**Comment by Bloke** [comment]
Mea culpa. Will fix.

**Comment by Bloke** [comment]
We still have a bunch of `strftime()` and `gmstrftime()` instances in core - even in 4.8.8. Two are within our `safe_strftime()`:

https://github.com/textpattern/textpattern/blob/main/textpattern/lib/txplib_misc.php#L2783

https://github.com/textpattern/textpattern/blob/main/textpattern/lib/txplib_misc.php#L2787

Presumably, we should fix these too in 4.9.0. And if we do need to go back and do 4.8.9 then we'll need to cherry-pick these commits so they'll need to be atomic.

**Comment by petecooper** [comment]
>And if we do need to go back and do 4.8.9

Assuming PHP folks stick to their schedule, we have PHP 8.2 GA in about 10 months, and going by [past releases](https://textpattern.co/release-history) + the 4.9 milestone I don't think we're gonna have it all ready this year…so 4.8.9 as a bug fix / security / PHP 8.2 scope might be on the cards after all.

**Comment by Bloke** [comment]
With a concerted focus, and merging some of the big ticket items in this coming month, 4.9.0 could arrive sooner :)

**Comment by Bloke** [comment]
So here's an interesting one:

https://github.com/textpattern/textpattern/blob/main/textpattern/lib/txplib_admin.php#L2053

We are trying to work out, presumably, if we have support for the `%e` modifier, which is not available on some systems (e.g. Windows). If not available, we want to fall back on `%d`. The way we currently do this:

``` php
$daynum = is_numeric(@strftime('%e')) ? '%e' : '%d';
```

A few things wrong with this approach:

1. It uses `strftime()` - now deprecated. Easy to fix (ish) by replacing it with a call to our `safe_strftime()` (although this comes with timezone baggage) or a straight swap for `date()`.
2. Since PHP 8.0, the way `is_numeric()` works has changed:

> 8.0.0 | Numeric strings ending with whitespace ("42 ") will now return true. Previously, false was return instead.

This also applies to numeric strings beginning with whitespace. So the above code will always return true, regardless of whether support is built in or not.

I think the safest (sanest) way to do this is to forget the test and use:

$daynum = date('j');

"j" seems to [return the numeric day of the month _without leading zeros_](https://www.php.net/manual/en/datetime.format.php) all the time, and there's no indication of OS incompatibilities.

Anyone see anything wrong with this approach? The same kind of approach will presumably apply to the `%Oe` a few lines further on, although I'm not entirely sure what that's supposed to do yet.

**Comment by Bloke** [comment]
Since `date()` isn't very international friendly, suggestions on how to make this part of Txp work (among others) without throwing a deprecation warning/error are more than welcome.

**Comment by bloatware** [comment]
I would simply trash these system-dependent formats, and caveat utilitor if someone needs to restore them manually.

**Comment by Bloke** [comment]
So can we just use `safe_strftime()` in place of the current `@strftime()` or does that introduce weirdness because of the time zones?

**Comment by Bloke** [comment]
I think, as you suggest, in the `txp_dateformats()`function, let's forget `strftime()` altogether and choose standard formatting strings that are available everywhere.

The only remaining question mark I have surrounds the commit [I just reverted](https://github.com/textpattern/textpattern/commit/1f6e21e4299bb3957a593c165c49afaa4f909470) inside the `safe_strftime()` function itself. No idea what to do here. If 99% of the cases are handled by intl date formatting earlier in the function, can we get away with just axing the chunk of code with the `(gm)strftime()` in it?

**Comment by Bloke** [comment]
See 655ebb40.

**Comment by bloatware** [comment]
If we remove this part (or replace `strftime()` with `date()`), people without `intl` extension would be in trouble. Sure, we can consider `intl` as required extension, but this might be a bit restrictive. Even if it is bundled with php as of 5.3+, it does not seem to be enabled by default in all php 5 distros. And one does not always have access to php config.

On the other hand (might be wrong), `intl` seems to come enabled in php 8. If so, as it is now, only a hypothetical 1% of php 8.1+ users who have disabled `intl` for some obscure reason is concerned. Enabling `intl` back again will then fix the problem.

Let us wait and see?

**Comment by Bloke** [comment]
Waiting makes sense. If it's only going to affect a very small number of people anyway, we can probably live with it until PHP 8 becomes more widely adopted.

**Comment by petecooper** [comment]
>If so, as it is now, only a hypothetical 1% of php 8.1+ users who have disabled intl for some obscure reason is concerned. 

~1% of the ~1% of PHP users running PHP 8.1!

**Comment by bloatware** [comment]
In txp context it makes less than 1 user :-/

**Comment by petecooper** [comment]
Arguably a pretty safe edge case, then…

**Comment by bloatware** [comment]
The wait is over, closing (until we definitively switch to `intl`).
