### ISSUE TITLE
Support for SVG image format

### ISSUE THREAD

**Issue by osadl** [textpattern/textpattern#1847]
Currently, SVG image format is not supported, but it can easily be added with a couple of lines of code.

**Comment by bloatware** [comment]
Thank you for the suggestion. Are we sure all security issues evoked [here](https://github.com/textpattern/textpattern/issues/856) are resolved?

**Comment by petecooper** [comment]
Tagging https://github.com/textpattern/textpattern/pull/1848

**Comment by osadl** [comment]
No, I don't want to make this functionality available to frontend users, only for the Web programmer through the backend - and they must know what they are doing anyway.

**Comment by bloatware** [comment]
That's what I usually say too. Though, we'd need to enable SVG uploads only for admin users (levels 1 and 2), to be consistent with the general txp security policy.

Opinions welcome.

**Comment by philwareham** [comment]
I'm OK with it security-wise, if it's admin level only. There's plenty of security risks an admin can introduce if they so wish, so SVG wouldn't place anything unprecedented in into the system.

**Comment by petecooper** [comment]
SVG security issues can (mostly or fully) be mitigated with CSP, which should be left as an exercise for the site operator.

+1 for admin SVG upload.

**Comment by phiw13** [comment]
I would be quite happy to see SVG upload build-in on the Image tab (issue 856  !), although I have no immediate need for now.

Top level admin only  (Publisher, Managing Editor) is a good  setting.

**Comment by osadl** [comment]
Followed your security advice and restricted SVG image upload to users with Publisher or Managing Editor level through the newly introduced global permission image.svg.upload. Tested everything successfully. As far as I'm concerned, the SVG image upload feature is now fully implemented.

**Comment by bloatware** [comment]
Thank you, will test, awaiting @Bloke and others opinion.

We actually still have a deprecated `image.create.trusted` priv that served to enable SWF uploads, removed since txp 4.7. We could probably use it instead of `image.svg.upload`?

**Comment by bloatware** [comment]
> SVG security issues can (mostly or fully) be mitigated with CSP, which should be left as an exercise for the site operator.
> 
> +1 for admin SVG upload.

I *knew* Pete enjoys replying '*I have successfully uploaded a malicious image*' CVE kiddies :-)

**Comment by osadl** [comment]
> [..]
> We actually still have a deprecated `image.create.trusted` priv that served to enable SWF uploads, removed since txp 4.7. We could probably use it instead of `image.svg.upload`?
I did not use this one because it is still referenced. Reviving it could activate the otherwise excluded line 8 in 
get_safe_image_types(), potentially causing harm. May I remove this reference so that I can reuse the deprecated priv "image.create.trusted"?

**Comment by bloatware** [comment]
I think yes, since nobody is able to upload SWF/SWC files any more anyway.

**Comment by osadl** [comment]
Ok, done.

**Comment by phiw13** [comment]
@petecooper 

> SVG security issues can (mostly or fully) be mitigated with CSP, which should be left as an exercise for the site operator.

Partly OT but since the possible security implications of SVG images are mentioned. What would your idea of CSP mitigating directives be ? 

This is worth exploring to include in the documentation of this feature.

**Comment by bloatware** [comment]
There is also a [sanitizer](https://github.com/darylldoyle/svg-sanitizer), for those willing to write a plugin.

**Comment by osadl** [comment]
I added some more validity checks to the SVG image and tweaked the code a bit. I also ran a lot of tests and could not find any misbehavior.

**Comment by jools-r** [comment]
Great contribution. While it's easy enough to bring in svg's via other means (flat file, txp form, etc.) there's no easy way to store the svg width and height with it, causing pagespeed to complain about the risk of cumulative layout shift. I'd welcome this (also incorporating sanitising)

**Comment by jools-r** [comment]
I've given the current PR (up to and including https://github.com/osadl/textpattern/commit/cb44a2392f147de0f0994f52a99f701b638addeb) a whirl on my local webserver running PHP 8.1 using your fork of Textpattern as the codebase. First of all, I love the possibility of being able to upload svgs but currently I am unfortunately getting mixed results.

### Not all SVGs upload

When trying arbitrary svg files on my hard drive, quite a few of them fail to upload showing the error message `Only .gif, .jpeg, .jpg, .png, .svg, .webp, .avif file types allowed` (=`only_graphic_files_allowed`). Note that svg does feature as a file type in the error message as an allowed file type so the new file type has been added.

However, other svg files do upload successfully without any problems.

From what I can tell looking at their code, it has something to do with how well-formed the svg files and perhaps also the presence (or lack thereof) of `width` and `height` height attributes in the opening `<svg…` tag, or their units. Pretty much any svg that has been been passed through an optimiser (e.g. using [ImageOptim](https://imageoptim.com/) or one of the many online optimisers or build tools (e.g. [svgo](https://github.com/svg/svgo)) fails to upload. Those svgs are very common, though.

Here are two examples of the same svg file (the yellow box with JS logo).

This is the original – which uploads successfully and shows a thumbnail if the width has been set beforehand:

```
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<svg width="256px" height="256px" viewBox="0 0 256 256" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" preserveAspectRatio="xMidYMid">
    <g>
        <path d="M0,0 L256,0 L256,256 L0,256 L0,0 Z" fill="#F7DF1E"></path>
        <path d="M67.311746,213.932292 L86.902654,202.076241 C90.6821079,208.777346 94.1202286,214.447137 102.367086,214.447137 C110.272203,214.447137 115.256076,211.354819 115.256076,199.326883 L115.256076,117.528787 L139.313575,117.528787 L139.313575,199.666997 C139.313575,224.58433 124.707759,235.925943 103.3984,235.925943 C84.1532952,235.925943 72.9819429,225.958603 67.3113397,213.93026" fill="#000000"></path>
        <path d="M152.380952,211.354413 L171.969422,200.0128 C177.125994,208.433981 183.827911,214.619835 195.684368,214.619835 C205.652521,214.619835 212.009041,209.635962 212.009041,202.762159 C212.009041,194.513676 205.479416,191.592025 194.481168,186.78207 L188.468419,184.202565 C171.111213,176.81473 159.597308,167.53534 159.597308,147.944838 C159.597308,129.901308 173.344508,116.153295 194.825752,116.153295 C210.119924,116.153295 221.117765,121.48094 229.021663,135.400432 L210.29059,147.428775 C206.166146,140.040127 201.699556,137.119289 194.826159,137.119289 C187.78047,137.119289 183.312254,141.587098 183.312254,147.428775 C183.312254,154.646349 187.78047,157.568406 198.089956,162.036622 L204.103924,164.614095 C224.553448,173.378641 236.067352,182.313448 236.067352,202.418387 C236.067352,224.071924 219.055137,235.927975 196.200432,235.927975 C173.860978,235.927975 159.425829,225.274311 152.381359,211.354413" fill="#000000"></path>
    </g>
</svg>
```

and this is an optimised version of the same svg – which does't upload:

```
<svg height="256" preserveAspectRatio="xMidYMid" viewBox="0 0 256 256" width="256" xmlns="http://www.w3.org/2000/svg">
<path d="m0 0h256v256h-256z" fill="#f7df1e"/>
<path d="m67.311746 213.932292 19.590908-11.856051c3.7794539 6.701105 7.2175746 12.370896 15.464432 12.370896 7.905117 0 12.88899-3.092318 12.88899-15.120254v-81.798096h24.057499v82.13821c0 24.917333-14.605816 36.258946-35.915175 36.258946-19.2451048 0-30.4164571-9.96734-36.0870603-21.995683"/>
<path d="m152.380952 211.354413 19.58847-11.341613c5.156572 8.421181 11.858489 14.607035 23.714946 14.607035 9.968153 0 16.324673-4.983873 16.324673-11.857676 0-8.248483-6.529625-11.170134-17.527873-15.980089l-6.012749-2.579505c-17.357206-7.387835-28.871111-16.667225-28.871111-36.257727 0-18.04353 13.7472-31.791543 35.228444-31.791543 15.294172 0 26.292013 5.327645 34.195911 19.247137l-18.731073 12.028343c-4.124444-7.388648-8.591034-10.309486-15.464431-10.309486-7.045689 0-11.513905 4.467809-11.513905 10.309486 0 7.217574 4.468216 10.139631 14.777702 14.607847l6.013968 2.577473c20.449524 8.764546 31.963428 17.699353 31.963428 37.804292 0 21.653537-17.012215 33.509588-39.86692 33.509588-22.339454 0-36.774603-10.653664-43.819073-24.573562"/>
</svg>
```

I've seen quite a lot of svg icons that lack height / width in the svg tag but then contain a bounding rectangle with width and height attributes in the content.

However, there do also seem to be situations where the svg fails to upload when width, height and viewBox attributes _are_ present in the svg, for example this loader.svg:

```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background-color: transparent; display: block; shape-rendering: auto; background-position: initial initial; background-repeat: initial initial;" width="71px" height="71px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
<circle cx="50" cy="50" r="0" fill="none" stroke="#353535" stroke-width="3">
  <animate attributeName="r" repeatCount="indefinite" dur="4.545454545454545s" values="0;51" keyTimes="0;1" keySplines="0 0.2 0.8 1" calcMode="spline" begin="-2.2727272727272725s"></animate>
  <animate attributeName="opacity" repeatCount="indefinite" dur="4.545454545454545s" values="1;0" keyTimes="0;1" keySplines="0.2 0 0.8 1" calcMode="spline" begin="-2.2727272727272725s"></animate>
</circle>
<circle cx="50" cy="50" r="0" fill="none" stroke="#666666" stroke-width="3">
  <animate attributeName="r" repeatCount="indefinite" dur="4.545454545454545s" values="0;51" keyTimes="0;1" keySplines="0 0.2 0.8 1" calcMode="spline"></animate>
  <animate attributeName="opacity" repeatCount="indefinite" dur="4.545454545454545s" values="1;0" keyTimes="0;1" keySplines="0.2 0 0.8 1" calcMode="spline"></animate>
</circle></svg>
```

I'm guessing these are failing in the `txpgetimagesize()` or `findSVG()` functions where either the attributes aren't found or not returned when the svg is parsed.


### Error when uploading svg webfonts

Perhaps not a likely scenario now that woff and woff2 are widely supported, but uploading an svg webfont shows two error dialogs in succession in the browser with `Warning "Undefined array key 2".` and `Warning "Undefined array key 3".` The svg does not upload. You can try this out, for example with a fontawesome svg confront.


### Symbolsets

I had no luck uploading svg symbolsets, e.g. of the format `<svg…><defs><symbol id="…" viewBox="…">…</symbol><symbol id="…" viewBox="…">…</symbol> … </defs></svg>` but this may be the same problem as above as they typically lack width, height or viewBox attributes in the opening svg tag, or these are set to zero so that the symbolset doesn't show if used inline in the html. Symbolsets are a useful replacement for the older svg sprite technique, but it's debatable whether these needs to be user-uploadable as strictly speaking it's a website asset (collection of icons / symbols) that the web designer / developer deals with rather than a content manager. Currently, however, the file fails to upload. FWIW my OS (Mac) doesn't show a preview for these files.


### Error when “creating a thumbnail” from the image edit pane

From a fresh site installation, clicking “Create” under “Create thumbnail” from the image_edit pain exits with the following error.:


```
Fatal error: Uncaught mysqli_sql_exception: You have an error in your SQL syntax; 
check the manual that corresponds to your MySQL server version for the right syntax to use near ', date = NOW() WHERE id = 1' at line 3 in /path/to/svg-site/textpattern/lib/txplib_db.php:442
Stack trace:
#0 /path/to/svg-site/textpattern/lib/txplib_db.php(442): mysqli_query(Object(mysqli), 'UPDATE txp_imag...', 0)
#1 /path/to/svg-site/textpattern/lib/txplib_db.php(503): safe_query('UPDATE txp_imag...', false)
#2 /path/to/svg-site/textpattern/lib/class.thumb.php(613): safe_update('txp_image', 'thumbnail = 1,\n...', 'id = 1')
#3 /path/to/svg-site/textpattern/include/txp_image.php(1123): txp_thumb->write()
#4 /path/to/svg-site/textpattern/include/txp_image.php(64): thumbnail_create() #5 /path/to/svg-site/textpattern/index.php(231): include('/path/to/S...') #6 /path/to/.composer/vendor/laravel/valet/server.php(235): require('/path/to/S...')
#7 {main} thrown in /path/to/svg-site/textpattern/lib/txplib_db.php on line 442
```

However, after a thumbnail width has been set (which you have to do once from the image edit pane), the svg does show in the thumbnail preview box. While it is a separate file, it is in effect the same as the main svg but with an additional width and height (if set) attribute. The error still occurs when clicking "Create" in the image edit pane.

...

I'd love to see svg upload become part of the forthcoming release but I guess the many forms that svg files can take means one has to cater for / defend against several edge cases.

**Comment by osadl** [comment]
On 12/18/22 17:55, jools-r wrote:
> I've given the current PR (up to and including https://github.com/osadl/textpattern/commit/cb44a2392f147de0f0994f52a99f701b638addeb) a whirl on my local webserver running PHP 8.1 using your fork of Textpattern as the codebase. First of all, I love the possibility of being able to upload svgs but currently I am unfortunately getting mixed results.
> 
> ### Not all SVGs upload
> [..]
> I'm guessing these are failing in the `txpgetimagesize()` or `findSVG()` functions where either the attributes aren't found or not returned when the svg is parsed.
No. All your SVG samples that fail to load simply miss the first line starting with "<?xml". Let me improve the load function so such SVG files are accepted as well.

> ### Error when uploading svg webfonts
> 
> Perhaps not a likely scenario now that woff and woff2 are widely supported, but uploading an svg webfont shows two error dialogs in succession in the browser with `Warning "Undefined array key 2".` and `Warning "Undefined array key 3".` The svg does not upload. You can try this out, for example with a fontawesome svg confront.
I'll check it out.

> ### Symbolsets
> 
> I had no luck uploading svg symbolsets, e.g. of the format `<svg…><defs><symbol id="…" viewBox="…">…</symbol><symbol id="…" viewBox="…">…</symbol> … </defs></svg>` but this may be the same problem as above as they typically lack width, height or viewBox attributes in the opening svg tag, or these are set to zero so that the symbolset doesn't show if used inline in the html. Symbolsets are a useful replacement for the older svg sprite technique, but it's debatable whether these needs to be user-uploadable as strictly speaking it's a website asset (collection of icons / symbols) that the web designer / developer deals with rather than a content manager. Currently, however, the file fails to upload. FWIW my OS (Mac) doesn't show a preview for these files.
Let me have a look into that.

> ### Error when “creating a thumbnail” from the image edit pane
> 
>>From a fresh site installation, clicking “Create” under “Create thumbnail” from the image_edit pain exits with the following error.:
Looks like browsers automatically insert values from earlier sessions, if empty. If from a fresh site installation there are no earlier values, they remain empty. I'll check it and show an alert message, if at least one of width or height are not provided.

Thanks for testing,
Carsten

**Comment by osadl** [comment]
On 12/18/22 17:55, jools-r wrote:
> I've given the current PR (up to and including https://github.com/osadl/textpattern/commit/cb44a2392f147de0f0994f52a99f701b638addeb) a whirl on my local webserver running PHP 8.1 using your fork of Textpattern as the codebase. First of all, I love the possibility of being able to upload svgs but currently I am unfortunately getting mixed results.
> 
> ### Not all SVGs upload
Would you mind to test your optimized SVGs with the recent commit? Please note that I have not yet investigated the other issues.

Thanks,
Carsten

**Comment by jools-r** [comment]
> No. All your SVG samples that fail to load simply miss the first line starting with "<?xml". Let me improve the load function so such SVG files are accepted as well.

> Would you mind to test your optimized SVGs with the recent commit?

Yes, that was it. It now accepts pretty much everything I've tried to upload. Thank you!

As you say, if the thumbnail width has already set previously, a thumbnail shows but the current behaviour for the SVGs is different to how other pixel-based images are handled:

With an png or jpg, you can set just the width of a crop and the height will then adjust according to the images aspect ratio. With the SVGs, if just the width, the height is 0 and the SVG thumbnail appears as a horizontal line (actually the top and bottom border around the image).

If you set a height, the thumbnail shows too but if the thumbnail is taller than it is wide, then the vertical constraint causes the SVG to appear thinner, i.e. not at full width. Presumably, if just the thumbnail width or height is set, you need to calculate the other value proportionately based on the SVGs aspect ratio rather than it being 0 or empty

**Comment by osadl** [comment]
On 12/18/22 22:50, jools-r wrote:
> [..]
> With an png or jpg, you can set just the width of a crop and the height will then adjust according to the images aspect ratio. With the SVGs, if just the width, the height is 0 and the SVG thumbnail appears as a horizontal line (actually the top and bottom border around the image).
> 
> If you set a height, the thumbnail shows too but if the thumbnail is taller than it is wide, then the vertical constraint causes the SVG to appear thinner, i.e. not at full width. Presumably, if just the thumbnail width or height is set, you need to calculate the other value proportionately based on the SVGs aspect ratio rather than it being 0 or empty
Yes, dimensions of SVG thumbnail images are now calculated in the same manner as for other images.

Thanks,
Carsten

**Comment by osadl** [comment]
On 12/18/22 22:50, jools-r wrote:

> As you say, if the thumbnail width has already set previously, a thumbnail shows but the current behaviour for the SVGs is different to how other pixel-based images are handled:
The cropping function of SVG images now mostly simulates the behavior of 
other image types. May I ask you to test the thumbnail function again?

Thanks,
Carsten

**Comment by jools-r** [comment]
Excellent updates – Danke Carsten!

Yes, I can confirm:

- [x] Uploading SVG files with/without XML header generally reliable (see exception below)
- [x] Setting just width or height: the other dimension is calculated as per the aspect-ratio
- [x] Setting width and height and ticking crop crops the image
- [x] Creating thumbnails of SVGs in the image edit panel successful
- [X] Uploading an svg webfont no longer produces an error (fails silently, nothing is uploaded) 
- [ ] Uploading an svg symbolset* appears at first also to fail silently. However, on refreshing the page or uploading another image, an image has been added but without a thumbnail (which is logical given that it is a container including multiple svgs). One just does not see the image panel update on first upload.

_*You can try creating a symbolset yourself by visiting https://remixicon.com, clicking the "+" next to several different icons to add them to a collection, then clicking on the "collection folder" icon and choose "download font". In the zip that downloads is a file called remixicon.symbol.svg (not to be confused with remixicon.svg in the same archive, which is an svg icon webfont)._

----

I did come across a couple of SVGs where I received the following error as a browser dialog in debugging mode and PHP 8.1. It also happens if you use "Create thumbnail" in the image edit pane:

```
8192 "preg_match(): Passing null to parameter #2 ($subject) of
type string is deprecated"
in /path/to/svg-site/textpattern/lib/txplib_misc.php at line 631.
adminErrorHandler0
textpattern/lib/txplib_misc.php:631 preg_match ()
textpattern/lib/txplib_admin.php:555 svgtopx()
textpattern/lib/txplib_admin.php:580 txpgetimagesize ()
textpattern/lib/class.thumb.php:220 txpimagesize ()
textpattern/lib/class.thumb.php:622 wet_thumb->write ()
textpattern/lib/txplib_admin.php:746 txp_thumb->write ()
textpattern/include/txp_image.php:827 image_data()
textpattern/include/txp_image.php:64 image_insert ()
textpattern/index.php:231 include ()
```

This is an example of the svg that produced it (the letter R against a colored background):

```
<svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg"><path d="m0 0h512v512h-512z" fill="#eb5f3b"/><path d="m376.15 397.35-64.08-113.27c30.26-13.67 50.42-40.14 50.42-81.79 0-67.35-49.25-88.21-109.33-88.21h-102v283.27h64v-101.94h35.22l54.07 101.94zm-161-232.42h32.85c33.68 0 51.78 9.35 51.78 37.36s-18.1 42.27-51.78 42.27h-32.81z" fill="#fff"/></svg>
```

----

This is a rare edge case: if you try and create a thumbnail for a symbolset SVG – which doesn't have one because it contains multiple svgs within it – it simply zeros out the dimensions again. That seems fine to me (macOS doesn't show a preview either). However, if you happen to also have the [x] Crop ticked, it exits with the following error:

```
Fatal error: Uncaught DivisionByZeroError: Division by zero in /Users/julian/Sites/svg-site/textpattern/lib/class.thumb.php:311 Stack trace: #0 /Users/julian/Sites/svg-site/textpattern/lib/class.thumb.php(622): wet_thumb->write('/Users/julian/S...', '/Users/julian/S...') #1 /Users/julian/Sites/svg-site/textpattern/include/txp_image.php(1123): txp_thumb->write() #2 /Users/julian/Sites/svg-site/textpattern/include/txp_image.php(64): thumbnail_create() #3 /Users/julian/Sites/svg-site/textpattern/index.php(231): include('/Users/julian/S...') #4 /Users/julian/.composer/vendor/laravel/valet/server.php(235): require('/Users/julian/S...') #5 {main} thrown in /Users/julian/Sites/svg-site/textpattern/lib/class.thumb.php on line 311
```

**Comment by osadl** [comment]
On 12/20/22 11:52, jools-r wrote:

> [..]
> - [ ] Uploading an svg symbolset* appears at first also to fail silently. However, on refreshing the page or uploading another image, an image has been added but without a thumbnail (which is logical given that it is a container including multiple svgs). One just does not see the image panel update on first upload.
> 
> _*You can try creating a symbolset yourself by visiting https://remixicon.com, clicking the "+" next to several different icons to add them to a collection, then clicking on the "collection folder" icon and choose "download font". In the zip that downloads is a file called remixicon.symbol.svg (not to be confused with remixicon.svg in the same archive, which is an svg icon webfont)._
Added some more sanity checks when SVG images are loaded; thus, images 
with zero width or zero height are now refused.

> ----
> 
> I did come across a couple of SVGs where I received the following error as a browser dialog in debugging mode and PHP 8.1. It also happens if you use "Create thumbnail" in the image edit pane:
> 
> ```
> 8192 "preg_match(): Passing null to parameter #2 ($subject) of
> type string is deprecated"
> in /path/to/svg-site/textpattern/lib/txplib_misc.php at line 631.
> adminErrorHandler0
> textpattern/lib/txplib_misc.php:631 preg_match ()
> textpattern/lib/txplib_admin.php:555 svgtopx()
> textpattern/lib/txplib_admin.php:580 txpgetimagesize ()
> textpattern/lib/class.thumb.php:220 txpimagesize ()
> textpattern/lib/class.thumb.php:622 wet_thumb->write ()
> textpattern/lib/txplib_admin.php:746 txp_thumb->write ()
> textpattern/include/txp_image.php:827 image_data()
> textpattern/include/txp_image.php:64 image_insert ()
> textpattern/index.php:231 include ()
Looks like my PHP version is less picky about empty arguments, sanity 
check added to prevent this error.

> [..]
> This is a rare edge case: if you try and create a thumbnail for a symbolset SVG – which doesn't have one because it contains multiple svgs within it – it simply zeros out the dimensions again. That seems fine to me (macOS doesn't show a preview either). However, if you happen to also have the [x] Crop ticked, it exits with the following error:
> 
> ```
> Fatal error: Uncaught DivisionByZeroError: Division by zero in /Users/julian/Sites/svg-site/textpattern/lib/class.thumb.php:311 Stack trace: #0 /Users/julian/Sites/svg-site/textpattern/lib/class.thumb.php(622): wet_thumb->write('/Users/julian/S...', '/Users/julian/S...') #1 /Users/julian/Sites/svg-site/textpattern/include/txp_image.php(1123): txp_thumb->write() #2 /Users/julian/Sites/svg-site/textpattern/include/txp_image.php(64): thumbnail_create() #3 /Users/julian/Sites/svg-site/textpattern/index.php(231): include('/Users/julian/S...') #4 /Users/julian/.composer/vendor/laravel/valet/server.php(235): require('/Users/julian/S...') #5 {main} thrown in /Users/julian/Sites/svg-site/textpattern/lib/class.thumb.php on line 311
In an earlier discussion it was decided to reject multi-image SVGs. The 
above mentioned sanity check now takes better care of such multi-image 
SVGs, if the parent image has a size of zero.

Hope this helps.

Thanks,
Carsten

**Comment by jools-r** [comment]
That did it. I can't break it anymore :-) I haven't tried any deliberately dangerous SVGs but your last commits have silenced all the remaining errors I could produce and uploading SVGs works much like with any other image file type. A worthwhile addition, I think.

I suppose there's one debatable situation: SVGs with multiple content and no parent image – e.g. svg webfonts and svg symbolsets – are simply rejected*: One sees the `only_graphic_files_allowed` error, although the file is an SVG file type. That might raise “It doesn't work” enquiries. Then again, if upload was permitted, users may ask “My SVG uploaded but I can't get it to produce a thumbnail”... Not sure what other people think about that.

The only other thing I noticed in the code is that the Textpattern devs may want some code conventions to be followed, such as `{…}` braces on single-line `if` statements. I can't remember if that was a stipulation.

**Overall, I like this addition a lot and hope this can get added to txp 4.9. Thank you Carsten!**

_*svg sprites also contain multiple items but they are in effect a single large image so they do upload._

**Comment by osadl** [comment]
On 12/21/22 12:17, jools-r wrote:
> That did it. I can't break it anymore :-)
Good.

> [..] 
> I suppose there's one debatable situation: SVGs with multiple content and no parent image – e.g. svg webfonts and svg symbolsets – are simply rejected*: One sees the `only_graphic_files_allowed` error, although the file is an SVG file type. That might raise “It doesn't work” enquiries. Then again, if upload was permitted, users may ask “My SVG uploaded but I can't get it to produce a thumbnail”... Not sure what other people think about that.
I agree that it would be good to generate more specific error messages. 
I'll think about it and see what I can do.

> The only other thing I noticed in the code is that the Textpattern devs may want some code conventions to be followed, such as `{…}` braces on single-line `if` statements. I can't remember if that was a stipulation.
Yes, I know. This is one of the very few deviations from my own style 
guide so it may well be that I have overlooked some of them. I will send 
style guide consideration patches later.

> **Overall, I like this addition a lot and hope this can get added to txp 4.9. Thank you Carsten!**
Thank you for your support!
Carsten

**Comment by bloatware** [comment]
Many thanks @osadl, @jools-r and all contributors. It's in History now, closing.
