### ISSUE TITLE
Add columns to Users table to show counts for articles, files, images, and links

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1863]
### Is your feature request related to a problem?

No.

### What is the feature?

Additional columns on the Users panel table: quantity for each of articles, files, images, and links. The Themes panel table already shows per-theme counts for Sections, Pages, Forms, and Styles.

When I'm deleting one or more authors from a larger site, it's not immediately clear of that author's 'work done' in that table view, so the impact of binning each author needs more investigation. If I know Alice The Freelancer has 1500 articles, Bob The Designer has 300 images, and Charlie The Staff Writer has 900 links, I can assign each author's content to an appropriate author, or someone in the same user role (which I can already see, helpfully).

**Comment by Bloke** [comment]
smd_user_manager adds these, iirc. So it ought to be fairly easy to copy the relevant code over and do it neater for core.

**Comment by Bloke** [comment]
[Like this](https://github.com/textpattern/textpattern/commit/73c29f498fd1b74a5228f81be377577fb90b603b)?

Please test. And note that if you also install smd_user_manager in its current guise it might render the 4 columns again. But (more likely) it'll break until the plugin's list panel is patched.

**Comment by cara-tm** [comment]
Perfect!
But the full date of the latest connection will be useful too (with the day).

**Comment by Bloke** [comment]
Sadly, we don't know the last login date exactly because the cookie has 30-day validity. So if you log in via cookie (which is most of the time) the best we can do is get the month in which the cookie was issued.

Not really sure how to get round that. Would probably need some major refactoring of how we handle cookies. We do need to do that at some point, and I think there's an Issue for it somewhere, so maybe we can look at that then.

**Comment by Bloke** [comment]
An interesting side-note to this. During installation, no user is assigned to the data that is brought in from the Textpattern/DB/data directory via `\Textpattern\Import\TxpXML->ImportXML()`. This means that the Links column on a default installation shows '1' article and '0' links belonging to the user, when 4 links actually exists, assigned to nobody.

Difficult to get round, as we can't assume in the `ImportXML()` method that the table has an `author` column. One possible avenue is a magic value in the data file, e.g.:

```
<item>
            <date>NOW()</date>
            <category>textpattern</category>
            <url>https://textpattern.com/</url>
            <linkname>Textpattern website</linkname>
            <linksort>10</linksort>
            <description></description>
            <author>{TXP_CURRENT_USER}</author>
        </item>
```
So that can be swapped out for $txp_user during installation.

@bloatware Thoughts?

**Comment by bloatware** [comment]
@Bloke is that what we do for the 'welcome' article? Looks natural then. Or we could introduce a repair option to diagnostics, to assign eventual orphan (for whatever reason) items etc, maybe..

**Comment by Bloke** [comment]
@bloatware For articles, we just add `$txp_user` to the content automatically because that routine is specific to articles and we therefore know that there's an AuthorID column that needs populating.

For the (generic) routine that handles XML files for other tables, there's no guarantee that such an author column exists. The data file just has an empty placeholder `<author>` element, which thus never populates the DB table on import.

We could look out for this specific tag and, if it's empty, shove the current user in as content. But if a plugin or future core table has a different structure and uses a different column name, that won't work.

The only reliable thing I can think of is to permit a 'magic' content value which is swapped out for the current user. I don't particularly like magic values as they're difficult to document for plugin authors to take advantage of them, but I can't think of anything else. Unless you have any other ideas>?

**Comment by petecooper** [comment]
OP sorted, closing.

Thank you @Bloke!
