### ISSUE TITLE
`dev` branch shows files modified notification during install

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1869]
![Screenshot 2023-04-03 at 14 49 32](https://user-images.githubusercontent.com/226578/229529852-0a762727-84b4-46a2-8efd-830cc23d4d63.png)

We know that `dev` is in-progress code and not intended for production, so it's a bit jarring when there's a notification for these files being modified. Could we bypass these checks (or hide the results) if we're on dev mode? I suppose the other thing to consider would be to generate checksums as part of CI, so it'd always be up-to-date, but that feels over the top.

**Comment by Bloke** [comment]
Hmmm, darnit. We only set the version and txp_is_dev in textpattern/index.php which is never called during setup. So we don't actually know what version is being installed nor if it's live or dev.

We can't include that file as it will scupper a load of globals.

One thing we could do is move those two constants from index.php to constants.php, as that is included in both places, albeit a little later in the execution.

Not sure what the ramifications are. Anyone got any thoughts?

**Comment by bloatware** [comment]
I would say that most of this setup folder (theme, lang) is redundant and should be integrated into core... if someone else than me could do it :-)

**Comment by Bloke** [comment]
Well, we split it off from core in 4.7.0 when the Langs were all bundled so the strings don't pollute the main table. And having everything self-contained means it's easier to just omit and is good for security so setup can't be run again. But I'm open to change ideas if they're of benefit.

**Comment by bloatware** [comment]
Okay, then why wouldn't we @include@ setup instead of clicking a link?

**Comment by bloatware** [comment]
> You mean if setup exists just include it by default so every time someone visits the admin side they see the setup process until they remove the folder?

No, only if there is no valid `config.php`, like it works now.

> I've not tried it, so it might work.

It does not, or requires too much modification. The way setup sets paths when included, one finishes in some  PEAR folder. I have not tried too hard, though.

**Comment by Bloke** [comment]
> No, only if there is no valid `config.php`, like it works now.

That makes sense actually. Presumably we'd throw an error message to the screen if setup doesn't exist, rather than keep showing a link to a folder that doesn't exist (and sometimes gets into a loop of appending `/setup` over and over to the URL).

> The way setup sets paths when included, one finishes in some PEAR folder.

Yeah, I can well believe that. It's written as if it's the only environment in existence so might be quite a faff to rework.

**Comment by Bloke** [comment]
Although OT, does 9855417d make sense to redirect to the setup dir if config is missing and the setup files are available? A simple `include` was no good because all the paths in setup rely on the URL reflecting the actual endpoint, so a redirect was required.

Can't see a way round the endless loop if you hit the error message and follow the link (besides just removing the link of course).

**Comment by petecooper** [comment]
Nice one, @Bloke - thank you very much. Aiming to have some time after work tomorrow so will test.
