### ISSUE TITLE
Using multi-byte characters in the name of section

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#249]
_From [dev.nnnn@gmail.com](https://code.google.com/u/dev.nnnn@gmail.com/) on August 20, 2012 07:51:43_

What steps will reproduce the problem? 1.Login to admin page. Create or edit a section.
2.Use an multi-byte character in the section name
3.Save and try to edit by clicking the section name What is the expected output? What do you see instead? EXPECTED: The edit page for the section
INSTEAD: almost nothing except with a version info, user name, and logout button Please use labels and text to provide additional information. When I look in the source, I can see something is not going right.
I'll paste the whole source I get.
It only happens when I use a multi-byte character in the section-name, and it does not occur when I use the same characters in the section-title.

</div><div class="txp-footer"><a id="mothership" href=" http://textpattern.com/ " title="go_txp_com" rel="external"><img src="theme/classic/carver.png" width="40" height="40" alt="Textpattern" /></a>
<p>Textpattern CMS &#183; 4.5.0-beta</p>
<p id="moniker">user <span>****</span><br /><a href="index.php?logout=1">logout</a></p>
<script type="text/javascript">

</script>

</div></body>
</html>

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=245_

**Comment by vanmelick** [comment]
Stuff got lost while transferring from Google Code. Let's try that again:

---

What steps will reproduce the problem?
1.Login to admin page. Create or edit a section.
2.Use an multi-byte character in the section name
3.Save and try to edit by clicking the section name

What is the expected output? What do you see instead?
EXPECTED: The edit page for the section
INSTEAD: almost nothing except with a version info, user name, and logout button

Please use labels and text to provide additional information.
When I look in the source, I can see something is not going right.
I'll paste the whole source I get.
It only happens when I use a multi-byte character in the section-name, and it does not occur when I use the same characters in the section-title.

> `</div><!-- /txp-body --><div class="txp-footer"><a id="mothership" href="http://textpattern.com/" title="go_txp_com" rel="external"><img src="theme/classic/carver.png" width="40" height="40" alt="Textpattern" /></a>`
> `<p>Textpattern CMS &#183; 4.5.0-beta</p>`
> `<p id="moniker">user <span>****</span><br /><a href="index.php?logout=1">logout</a></p>`
> `<script type="text/javascript">`
> `<!--`
> `textpattern.textarray = null`
> `// -->`
> `</script>`
> 
> `</div><!-- /txp-footer --></body>`
> `</html>`
> `<!-- runtime: 0.0294 -->`
> `<!-- Memory: 4096Kb -->`

**Comment by vanmelick** [comment]
The original problem no longer exists. 
What remains is double urlencoding and the loss of percentage chars when saving again as Robert describes.

Pull request #514 fixes this

**Comment by Bloke** [comment]
Fixed by 4e5df263f9cd657bb57d2cb152ce5171fef4f75b
