### ISSUE TITLE
Improve (pop)help support

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#292]
_From [stefdawson](https://code.google.com/u/stefdawson/) on October 15, 2012 13:59:08_

The current help topics from the RPC server return complete markup and styling which makes it difficult to embed in Textpattern. It's also a barrier for plugin authors to write their own help topics using the new admin_help callback.

Propose adding a JSON-esque return path for RPC help topic requests, triggered by adding &type=json to the help URL. Returned data might include:
- Title
- Language code (which may be the requested lang or the default lang if help topic not yet translated)
- Raw (currently Textile) description which may be locally passed through a Textfilter (not sure if this is useful)
- Cooked HTML description suitable for direct injection into a markup template

As well as reducing traffic, help topics can then be built and styled locally, permitting modal and other implementations. Plugin authors could then just replace core URL paths with their own endpoint to serve similar JSON objects and have custom help topics rendered as per the current in-force theme.

See http://forum.textpattern.com/viewtopic.php?pid=259991#p259991

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=288_

**Comment by philwareham** [comment]
Current status is that @petecooper is batch converting the English (GB) pophelps at https://github.com/textpattern/pophelp into raw HTML. We will then clean-up the output and integrate this into work on https://github.com/textpattern/textpattern/issues/838.

**Comment by petecooper** [comment]
See also: https://github.com/textpattern/pophelp/issues/32 for completeness.

**Comment by makss** [comment]
Please check the work of popHelp, this functionality is already available.

**Comment by Bloke** [comment]
This is fantastic, makss. Thank you. The popup is so much nicer than the separate window, and it works beautifully in other languages too (I gave it a quick test with a `fr_pophelp.xml` file).

The pref is a great idea too. One thought: in future, are we thinking of offering pophelp in a variety of formats? If so, would it make sense to rename the pref now and (maybe) use a select list here instead of a yes/no radio? Then we could more easily extend the system in 4.8 and beyond. For example:

Help system
* None
* Pophelp
* Slidey drawer thingy
* Menu
* ...

As it stands, if we define those as constants in future, we'll need to ensure that 'pophelp' = '1' so that people who have set the current 'use pophelp' yes/no value retain that setting in the next version. But then other values won't make sense and we get in the same pickle we have now with `use_textile` taking on three or more values, some of which don't even relate to Textile!

Renaming the pref now to something like `help_system` offers us one advantage: the current name is a 'boolean' name ('enable' something), whereas a more generic pref name would make it more extensible in future (even if we elect to just store the actual values as numbers).

What do you think?

**Comment by philwareham** [comment]
Hi Stef, for now and foreseeable future the pophelp will be only solution. Not adverse to a slide drawer one day though if satisfactory UI/UX is found (I’ve not found anything I’m 100% happy with though).

**Comment by Bloke** [comment]
That's cool. Just want to make sure that new pref options are as flexible as we can define, so we don't get into the situation we have now, where we end up overloading prefs with options that don't make sense to the pref name itself.

Things that start `enable_` or `disable_` for example, ring alarm bells in my head because then the prefs can only have two states: on/off forever more, unless we faff with altering everyone's prefs during upgrade when we rename things.

**Comment by makss** [comment]
Yes, you are right. We must try to make a flexible option.
As for the name for preference `module_pophelp`:
* None
* Pophelp
(if necessary, then add more)

For the future help system, we can use the pref: `module_help`.
Maybe someday we will have: module_link, module_image, module_file, module_comment, ...

**Comment by Bloke** [comment]
`module_pophelp` is fine. Is the plan to make pophelp separate from general help then?

I envisaged that we have the inline instruction help always available - and that's for an admin to set up by hand. After that an option for:

* no additional help at all (for people comfortable with the system or those that use inline instruction help extensively).
* OR pophelp on individual widgets via the '?' links.
* OR general help for all widgets on the page in one slide-out panel (although this might be tricky on the Prefs panel because each sub-page of prefs is just switched via JS).
* OR a pulldown help menu with the groups->topics for that panel available.
* OR ...

But if the aim is to keep 'pophelp' and 'help' separate then that's also cool.

**Comment by makss** [comment]
I would like to make two independent settings, one for `pophelp`, and the second for `help` (maybe there will be more settings here). Software is going to be one class, but I would like to share them logically in the interface.

**Comment by makss** [comment]
Yes, can close it.

**Comment by philwareham** [comment]
Yay! Well done @makss - lovely stuff! 👏👏👏

**Comment by petecooper** [comment]
Great job, @makss -- thank you!
