### ISSUE TITLE
Option to encode values returned by template tags

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#399]
_From [jukka.m.svahn](https://code.google.com/u/jukka.m.svahn/) on October 21, 2013 10:44:48_

Currently Textpattern offers no way to use template tags within anything else than HTML; and even then not within tag attributes. Using tags within JavaScript, attributes, or URL component, will lead into XSS issues and broken markup.

For instance:

<script> alert('<txp:except />'); </script>

<a href="#" title="<txp:excerpt />"><txp:title /></a>

Generates:

<script> alert('<strong>Hello
World!</strong>'); </script>

<a href="#" title="<strong>Hello
World!</strong>">Test</a>

This creates unnecessary requirements for plugins, or that the user uses raw PHP. It's pretty lousy that the system offers no way to prevent XSS vulnerabilities. You literally can not use tags as attribute values etc.

Todo:
- Namespaced attributes, allowing global functionality shared by all tags. Global attributes are processed _before_ and/or _after_ the tag.
- Potential txp:escape/ tag.

The basic issue which we have is that Textpattern expects that everything is HTML. The main offender being Textile; it unnecessarily uses entities which fucks up everything. Not that it necessary matters because we already have some double encoding going on.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=395_

**Comment by vanmelick** [comment]
Copied again, this time with proper code escaping:

Currently Textpattern offers no way to use template tags within anything else than HTML; and even then not within tag attributes. Using tags within JavaScript, attributes, or URL component, will lead into XSS issues and broken markup.

For instance:
> `<script> alert('<txp:except />'); </script>`
> `<a href="#" title="<txp:excerpt />"><txp:title /></a>`

Generates:
> `<script> alert('<strong>Hello World!</strong>'); </script>`
> `<a href="#" title="<strong>Hello World!</strong>">Test</a>`

This creates unnecessary requirements for plugins, or that the user uses raw PHP. It's pretty lousy that the system offers no way to prevent XSS vulnerabilities. You literally can not use tags as attribute values etc.

Todo:
* Namespaced attributes, allowing global functionality shared by all tags. Global attributes are processed *before* and/or *after* the tag.
* Potential `<txp:escape/>` tag.

The basic issue which we have is that Textpattern expects that everything is HTML. The main offender being Textile; it unnecessarily uses entities which fucks up everything. Not that it necessary matters because we already have some double encoding going on.

**Comment by philwareham** [comment]
We have an extended `escape` attribute now - so can it be assumed this issue has been resolved? @bloatware @Bloke

**Comment by Bloke** [comment]
Yep, done, with bells on.
