### ISSUE TITLE
Implement PRS-0/PSR-1/PSR-2 and automatic styling check

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#412]
_From [jukka.m.svahn](https://code.google.com/u/jukka.m.svahn/) on April 05, 2014 17:12:49_

We should use the accepted standard rather than doing our own thing.

* https://github.com/php-fig/fig-standards/tree/master/accepted

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=408_

**Comment by Bloke** [comment]
Closing this now as we've adopted PSR-2 throughout. Any latent issues will be picked up by PHPCS or contributors during development.

PHPDoc blocks still need adding in places (see #278), but doc formatting is not part of PSR-2.

**Comment by NicolasGraph** [comment]
I started to use [linter-phpcs](https://atom.io/packages/linter-phpcs) and it seems that PSR-2 is not totally adopted by Txp yet…
[Here](https://github.com/NicolasGraph/textpattern/commit/5c13ee2b84ad83cc8bcd151c5b46d113617121f1) are needed changes just for _txp_admin.php_.
Now, let me know: I missed something or you need help for cleaning?

**Comment by philwareham** [comment]
@NicolasGraph PSR-2 is done as far as it needs to be at this stage, it's an ongoing task - personally I've used [php-cs-fixer](http://cs.sensiolabs.org) and that throws up quite a lot of changes - I just cherrypicked the ones that were most appropriate/important.

**Comment by NicolasGraph** [comment]
Ok, just let me know if you need someone to help in that easy boring thing to do in a near future.
See you!

**Comment by NicolasGraph** [comment]
…Sorry, I can't get this question out of my mind: what does it mean _PSR-2 is done as far as it needs to be at this stage_? It is a standard, you follow it or not. no?

**Comment by Bloke** [comment]
The trouble with automatic linters is they're not very smart. Last time I ran one, it ballsed up my admin side because it put line breaks where it shouldn't have (in JSON output), which introduced syntax errors and bugs.

We've been taking a softly-softly approach and applying PSR-2 where it makes sense. But in some places, e.g. separating every parameter onto its own line, it makes the code far too spread out and harder to comprehend.

Like all good standards, there are things we try to follow to the letter of the law (e.g. bracket / brace placement, spacing, indentation, etc) and other places where we employ a little wiggle room (e.g. not always putting each parameter of a function call on its own line).

Since linters are a one-size-fits-all approach, if you employ one, you then need to go through and check it hasn't broken anything, which is sometimes more time-consuming than simply spotting a few PSR-2 violations that would aid readability near a place where you happen to be editing and fixing them by hand.

Does that make sense?

**Comment by NicolasGraph** [comment]
I didn't run any automatic task; just manually corrected where errors were shown, so I don't think that it introduces any bug (well it could, I make mistakes…).
I understand that you could want to not display short arguments on one line but by doing it I was also able to correct badly indented code, mainly in txp_article.php. Potential contributors are also asked to follow the PSR-2 coding style and they could be surprised by the "_as far as it needs to be_ PSR-2 coding style" used in the core, don't you think?

**Comment by philwareham** [comment]
By all means please submit pull requests with PSR-2 updates on a file by file basis. What I meant was that this close to 4.6 final releases it would be unwise to reformat vast parts of the code. That can be done in the 4.7 cycle more safely.

**Comment by NicolasGraph** [comment]
Ok, I tried to send a pull request but some wrong content was push in few files; I don't know why… Let me take more time and help you cleaning for 4.7; Phil is right it is safer.
