### ISSUE TITLE
SQL Field definitions are wrong

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#414]
_From [jukka.m.svahn](https://code.google.com/u/jukka.m.svahn/) on April 10, 2014 11:39:38_

All fields must either:
- Have default value
- Or set as NULL

Currently Textpattern is abusing:

> If strict mode is not enabled, MySQL sets the column to the implicit default value for the column data type.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=410_

**Comment by vanmelick** [comment]
You can set STRICT_TRANS_TABLES on older MySQL versions as well. I did so and performed a few tests which lead me to believe that the assumption in this issue and the resulting fix are incorrect.

Table field definitions don't have to have either a default value or accept NULL.
There is a difference between:
1. `NOT NULL default 1`: cannot be set to null and defaults to one if value not provided
2. `NOT NULL`: cannot be set to null, so a value must be given during insert
3. `default 1`: can be set to null (if supplied as value explicitly), but defaults to 1

Having NOT NULL without a default will still work in MySQL 5.6 with STRICT_TRANS_TABLES set, but you have to make sure you provide a value for that column when inserting.

Fixing this by adding a default in the table field definition is only correct if there really is a sensible default value for that column, but if it's a column where the value has to be supplied on inserts, setting a default just makes bugs in your code harder to find, because you want to get an error if you leave out a column that is essential. 

For example, in the txp_form table you don't want the 'name' to default to an empty string, because it's the primary key, which should be unique. Making it default to an empty string leads to SQL errors about a duplicate entry, which is more confusing than getting an SQL error about column that cannot be NULL, which you would get without a default.

**Comment by Bloke** [comment]
Thanks for the insight. If you want to revert what I've done or improve it in light of your findings, that's fine. I'll commit whatever you can throw this way. I was shooting semi-blind as I don't fully understand the benefit over why MySQL enforces this in the first place. NOT NULL makes perfect sense to me if you want to make sure that a key contains a value.

**Comment by vanmelick** [comment]
Sure. Before I do so, I'd also like to hear what Jukka thinks about this, since he was the one who proposed changing it. Perhaps I'm overlooking something.

**Comment by petecooper** [comment]
Suggestion: change the scope (title) of the PR to reflect that Textpattern _does_ run on MySQL >=5.6 after all.

**Comment by petecooper** [comment]
Please see previous comment regarding the issue title: https://github.com/textpattern/textpattern/issues/414#issuecomment-223756608

It's not accurate, and unnecessarily alarmist as we approach 4.6 release.

@Bloke @philwareham @bloatware @rwetzlmayr @vanmelick - respectfully requesting someone change it to something more appropriate, at a convenient time. Thank you.

**Comment by philwareham** [comment]
@Bloke any update on this issue? Is it still valid?

**Comment by Bloke** [comment]
I think it's been done. We do have a few niggles with people (like me) running Percona or MariaDB in strict mode, but I think it's close enough for now. Let's close it, and open a new issue when we officially intend to support more than just MySQL.
