### ISSUE TITLE
Make "Hive" more space efficient at higher breakpoints.

### ISSUE THREAD

**Issue by c2mrdale** [textpattern/textpattern#445]
Now that we're going to a two column design on the write page (which is great) we need to be more space efficient at larger screen sizes. It's not very usable to have to scroll down on a 1080p screen to get to your custom fields.

I would suggest using nested grid markup for items like the contents of "Sort and Display" which cannot be closed (which I understand from a UI perspective).

Behold..

![s-d-2](https://cloud.githubusercontent.com/assets/5280690/4580718/1187b976-4fd9-11e4-82c7-505108eb606d.jpg)
![s-d](https://cloud.githubusercontent.com/assets/5280690/4580719/1190c0d4-4fd9-11e4-912a-480e5d53abae.jpg)

**Comment by philwareham** [comment]
Closing this issue due to layout changes in admin-layout-branch using newer layout.

FYI since there is no upper limit on what a `select` field can house, it is not feasible to lock into a 2 column layout nested within a single column, so I;'m dropping that idea for now. May revisit at some point in the future if a satisfactory solution appears.
