### ISSUE TITLE
sync article and article_custom attributes or generate warnings

### ISSUE THREAD

**Issue by vanmelick** [textpattern/textpattern#457]
See this topic
http://forum.textpattern.com/viewtopic.php?id=44115&p=1

The user has excerpted="y" as an attribute in the txp:article tag, which isn't valid, but doesn't generate a warning, thus causing confusion. There should be a warning about using an unknown attribute or txp:article should handle the attribute as txp:article_custom does.

**Comment by Bloke** [comment]
Yes, this is always a source of annoyance since `<txp:article>` is just a specialised version of `<txp:article_custom>` and uses most of the same code. As you know, the upshot is that you can put any attributes you like that are valid for article_custom into a regular article tag, and they'll mostly be silently ignored.

This could probably be changed with some `if $(is_custom)` stuff to detect which attributes have been supplied and throw appropriate warnings, just never really investigated how best to untangle the two.

**Comment by vanmelick** [comment]
See pull request. 

Additionally, I wonder why TXP accepts 'y' as a valid value for that attribute, while TXP uses 0 or 1 for boolean attributes in all other places. Shouldn't that be corrected as well for consistency?

**Comment by rwetzlmayr** [comment]
Refs #511

**Comment by rwetzlmayr** [comment]
> Additionally, I wonder why TXP accepts 'y' as a valid value for that attribute, while TXP uses 0 or 1 for boolean attributes in all other places. Shouldn't that be corrected as well for consistency?

+1

**Comment by Bloke** [comment]
Closed by 26db1247d5049dd28b87d95d1573afb41f28fc2a
