### ISSUE TITLE
Create a latest.zip & latest.tar.gz for Textpattern releases

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#478]
Background: http://forum.textpattern.com/viewtopic.php?id=41629

More jibber-jabber from here downwards: https://github.com/textpattern/textpattern/pull/477#issuecomment-97465771

Requested: 2x symlinks for the current release of Textpattern - one for .zip, the other for .tar.gz.

Syntax: `ln -s /path-to-textpattern.com/latest.zip /path-to-textpattern.com/files/nn/textpattern.zip` and `ln -s /path-to-textpattern.com/latest.tar.gz /path-to-textpattern.com/files/nn/textpattern.tar.gz`.

I volunteer to test if someone can set these links up.

**Comment by rwetzlmayr** [comment]
I've added two temporary redirects to the web server config instead of the suggested symlinks so the name of the downloaded files still carries the actual version number which I consider a good UI pattern, and the download is counted via the ```file_download``` route.

Requires amending the web server config for new releases. Ugly.
