### ISSUE TITLE
Heading on write tab

### ISSUE THREAD

**Issue by hcgtv** [textpattern/textpattern#506]
Just noticed on 4.5.7 that the Write tab is missing a heading:

    echo '<h1 class="txp-heading">'.gTxt('write').'</h1>';

The admin layout branch is fine, but the master branch is still missing the H1.

**Comment by Bloke** [comment]
This was kind of by design at the time, given the amount of stuff on that panel. Although it deviated from the consistency of the other panels, we decided to leave it off as the layout of that panel is rather different to the rest and didn't wish to take up any more vertical space than necessary (more to scroll past in order to Just Write).

I haven't looked at the admin-layout-update branch in a while, so maybe Phil's worked the title into the revised layout now.

**Comment by hcgtv** [comment]
Ok, just found it strange that was the only panel with no heading.

Again, late to the party.

**Comment by philwareham** [comment]
Yep, it is a design decision. But I've decided to now give it a heading.
