### ISSUE TITLE
Plugin panel: "Active" column

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern#525]
See Issue here: https://github.com/textpattern/textpattern.github.io/issues/24
I guess you would flag this Issue as an "enhancement"?

**Comment by Bloke** [comment]
I don't know what to do about this. Our AJAX href toggler is tied to Yes/No label text in the currently installed language, so would need some re-engineering (or a new function introduced) to handle other labels. And even then, it's imperfect.

Perhaps we need to rethink the whole Yes/No toggle thing. Taking the Plugin panel as an example, we currently have:

Column heading = "Active".
Column content = Yes or No, i.e. the plugin on this row is active (Yes) or is not active (No).

That's fine, and makes sense. The problem comes because there's a cognitive disconnect at the time you want to interact with that column:

"OK, I want to enable rvm_maintenance... so I'm looking to take a positive action... hmmm, wtf, I need to click 'No' to turn it on??!"

In that case, it makes sense to use 'Activate / Deactivate' as labels indicating the _action_. But that makes the column heading incompatible with the label, and makes it more difficult to quickly scan a list to see which plugins are on or off. Colours might help for those that aren't red/green colour blind.

It gets worse, as the thread explores: should the `title` attribute (shown by desktop browsers on hover) indicate what the _current_ label means (No, this plugin is not currently active) or what _will happen_ when you click it ("Yes, this plugin will become active)?

Argh, who can spell minefield?

Maybe there's a better and clearer way to handle toggle states in the core, before we start introducing these in other places and confusing everyone.

Ideas?

**Comment by philwareham** [comment]
Remove the title attribute - it seems to be missing Textpack strings anyway. Leave it at that. The issue can be closed then. I've never once been confused as to what plugins are active or not, or how to turn them on/off if not.

Maybe in 4.7 we can use UI switches for this if you think that gives a clearer indication (something along the lines of http://www.bootstrap-switch.org would be fairly easy to do I think).

**Comment by Bloke** [comment]
Sounds fair. I like the on/off slider buttons. We'd need to refactor the UI to cater to those if we were going to retain the yes/no functionality of the toggles on the Sections panel, which work okay there.

I've never had a problem with the yes/no buttons either, but from a documentation standpoint I can see where Destry is coming from, e.g.:

"To turn the plugin on, click No."

But it could probably be rewritten:

"To toggle the enabled or disabled state of each plugin, click the corresponding Yes/No links accordingly."

I think once the title attributes are removed that'll alleviate any ambiguity, good call. I'll do that.

**Comment by Bloke** [comment]
Closed by a0286d4719d8fb649b27190becdf51ef49a4da76

**Comment by philwareham** [comment]
As a side note, [I have created an issue](https://github.com/philwareham/textpattern-hive-admin-theme/issues/69) in my Hive theme to keep track of this.
