### ISSUE TITLE
.htaccess content in Diagnostics info

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern#546]
The displayed content for the _.htaccess_ file leads with an exposed pair of code tags, like this: 

`<code>.htaccess</code> file contents:`

The editorial style guide will recommend formatting all server paths and folder/file names as _italic_, not as code. A convention that will be followed in docs, at least. 

But whether you can do that here or not, I don't know, as it appears HTML formatting in general is a problem in the display box. So I'd suggest not adding formatting on paths and file names at all like this when the formatting can't effectively be applied as italic. Just leave it plain so the markup isn't showing:

`.htaccess file contents:`

**Comment by philwareham** [comment]
This is a Textpack issue. I will deal with it.

**Comment by philwareham** [comment]
Fixed.

**Comment by philwareham** [comment]
When you say 'italic' do you mean `<i>` or `<em>`?

**Comment by wion** [comment]
italic = <i>
emphasis = <em>

So, italic, because we don't need to emphasize it to the screen readers. (At least I don't think so, or at least it's unlikely to be necessary. Would a blind a person install Textpattern? Probably not.)

**Comment by philwareham** [comment]
I'm going to leave it as `<code>` for file paths since that is the correct tag for this.

From W3C: "The code element represents a fragment of computer code. This could be an XML element name, **a file name**, a computer program, **or any other string that a computer would recognize**."

http://www.w3.org/TR/html5/text-level-semantics.html#the-code-element
