### ISSUE TITLE
Use native PHP namespaces

### ISSUE THREAD

**Issue by rwetzlmayr** [textpattern/textpattern#556]
Textpattern currently employs pseudo-namespacing with underscores, e.g. ``Textpattern_Textfilter_Textile``, mainly serving as a workaround for pre-PHP-5.3 compatibility which is not needed any more. 

I propose to switch to PHP's native namespaces before the stable release.

**Comment by Bloke** [comment]
Sounds like a plan.

**Comment by rwetzlmayr** [comment]
TIL that parts of the framework @gocom started to build is apparently dead code not used anywhere in the project.

1. \Textpattern\Filter
1. \Textpattern\Request
1. TBC

**Comment by rwetzlmayr** [comment]
Needs testing.

**Comment by philwareham** [comment]
I'm getting this error when I try to view the preferences panel, is it related to this patch?:

    Fatal error: Class 'Textpattern\Date\DateTimeZone' not found in /Users/pwareham/Sites/textpattern/textpattern/vendors/Textpattern/Date/Timezone.php on line 118

**Comment by Bloke** [comment]
@philwareham  Fixed in https://github.com/textpattern/textpattern/commit/dab4561b6a518492192445484e4e1d2dc2f69db2

**Comment by vanmelick** [comment]
This bit of code in Textpattern/Loader.php confuses me:
``` php
if ($this->namespace !== null && strpos($class, $this->namespace.$this->separator) !== 0 ||
    !preg_match('/^[\\a-zA-Z_\x7f-\xff][a-zA-Z0-9_\\\x7f-\xff]*$/', $class)
```
That regex doesn't just match the class, it matches namespace + class. Shouldn't the regex be like this:

``` php
^[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*(\\[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*)*$
```

**Comment by rwetzlmayr** [comment]
Considered `Textpattern\BuilderTags` as a refactoring candidate. But as this class is such an outlier with no consumer code outside its own little space I left it as it is.

**Comment by rwetzlmayr** [comment]
> https://bugs.php.net/bug.php?id=50731

@vanmelick: The current regex matches names with a leading backslash or leading alphas AFAICS. I suspect that this is related to https://bugs.php.net/bug.php?id=50731. 

See https://github.com/composer/composer/blob/fbae6b1589ef28b77f0c38d1c9d4b964fb4d45bc/src/Composer/Autoload/ClassLoader.php#L316

**Comment by vanmelick** [comment]
I guess either use the workaround from Composer (remove leading backslash) or bump the minimum required PHP version to PHP 5.3.3.

**Comment by rwetzlmayr** [comment]
Bat-signalling this to @philwareham, @Bloke, and @vanmelick.

Shall we start discussions about

1. the minimum required PHP version for Textpattern 4.6?
1. why Textpattern needs its own class loader and cannot use the useful parts from Composer?

or even talk about...

1. to which degree the remaining members of Team Textpattern have groked `Textpattern\Loader` and other frameworkish code @gocom has contributed to the project before he disappeared? (Me: Not.)

**Comment by philwareham** [comment]
Since I am not involved n the PHP to any extent, I can't comment. However, if 5.3.x offers significant enhancements that are otherwise holding you back by support 5.2 I'd say it's pretty safe to bump it (anyone stuck on 5.2 can use Textpattern 4.5.x).

http://w3techs.com/technologies/details/pl-php/5/all

**Comment by Bloke** [comment]
Minimum version doesn't bother me too much. 5.3.x is fine if it streamlines our processes or means fewer workarounds in our code.

Regarding the Loader, I've used Composer's one a few times and always get in a pickle. What's with the md5-ish looking strings as method names? Plus it seems once it's employed, you're bound by its `composer.json` file and I always end up having to manually fudge non-packagist libraries (e.g. ones that are local to the project and not universally shareable) or it complains it can't find them at update time. This may all simply be because I'm a Composer dunce and I need to learn more, so go with it if it saves us hassle.

As for the mystical object-oriented codebase, I get chunks of the more readily-consumable parts like the tag registry and how we can use `Txp::get()` as a static convenience. I've written the new search filter using it. I do however struggle a little with Adaptable/Providable interfaces. I'm fine with the general notion of an Adapter: a standard Interface against which code can be written, allowing for new objects to be plugged in to provide needed functionality (the password hashing algorithm is a great example). But other classes I'm less familiar with and are a bit baffling at present. Again, a bit of hard graft on my part and it'll become easier.

**Comment by vanmelick** [comment]
As I understand it, the move to native name spaces already required 5.3, so we're past 5.2 anyway.

Regarding the first question, some bits of info:
* PHP 5.3 has been EOL since 14 aug 2014 (5.4 since 3 September 2015).
* PHP 5.3.3 was released on 22 july 2010. 
* Debian old-old-stable (two releases before the current stable branch and the oldest version still receiving security updates until february 2016) has PHP 5.3.3.
* Ubuntu 10.04 LTS had PHP 5.3.2, but that version is EOL since 30 april 2015. Newer releases have more recent PHP versions.
* CentOS 5.6 has PHP 5.3.3. Supported till 31 march 2017.

As for the last two questions... 

All this OO stuff appearing in TXP is one of the reasons why I started taking courses at university again since this summer, but I have yet to see anything as complicated as the factory/prototype/adapter stuff that Jukka wrote. I've looked at it and I can grasp bits of what it is supposed to do, but definitely not enough to maintain it or even work with it comfortably.

I have no experience with Composer. From what I understand, using Composer does involve running stuff on the command line. Would that prevent users from installing TXP via FTP?

**Comment by philwareham** [comment]
Looking at the usage of PHP 5.3.x - less than 2% of those running 5.3 are running it below 5.3.3:

http://w3techs.com/technologies/details/pl-php/5.3/all

Bear in mind that is the percentage of 5.3 installed, not overall PHP 5.x.

So a minuscule amount of systems running PHP are running those versions. I think it's totally safe to say 5.3.3 as a minimum requirement.

**Comment by Bloke** [comment]
Oh yeah, Factories too, thanks for reminding me Ruud. The way they're implemented in Txp is no doubt "correct" in terms of how it should be done from textbooks, but how it fits with our codebase is a little head-scratching to me at present. Again, sitting down and injecting copious quantities of `echo/dmp` and inspecting the output will probably get me on the right track.

The way I've been doing it so far has been Googling OO Design Patterns and trying to grok their use cases in real code from the rather abstract and, usually contrived, examples given. Adapter is the only one that I've found genuinely graspable in real life and I can see a use for. Most the others I'm left thinking "but it's so much extra code... and for what benefit?"

Once I see them in use in the wild and I can see the advantages each brings, maybe the patterns will 'click' in my head, like it did the first time I understood the point of OO over functional programming.

**Comment by rwetzlmayr** [comment]
1. PHP version decided, see #569 
1. I'll prepare more material re: Composer
1. Re: OO concepts: Looks like we've painted ourselves in a corner but there's hope that we like it there ;) Reminds me of the short Spark/Plug era with Sam Weiss.

**Comment by Bloke** [comment]
Hehe, my main objection to Spark/Plug ended up being that we'd have to write an entire layer on top of it to retain any semblance of backwards compatibility. At least this way we can iterate towards a full OO solution as we learn more.

**Comment by rwetzlmayr** [comment]
> I'll prepare more material re: Composer

I'd like to invite all interested parties to join me [over there](https://github.com/rwetzlmayr/textpattern/blob/rwetzlmayr-composerautoloader/README-composer.textile). We can litter around without tainting the canonical repo.
