### ISSUE TITLE
Purpose of txp_token table unknown.

### ISSUE THREAD

**Issue by vanmelick** [textpattern/textpattern#611]
The new txp_token table doesn't seem to be used yet by TXP.
* what purpose does it serve?
* how should we use it?
* what do each of the columns in the table mean?

I'm asking because I'm working on a patch that corrects the defaults for various table columns (one of the open issues) and I don't have enough info.

**Comment by Bloke** [comment]
It's currently used for just two things: new user registration and password reset request confirmations.

Columns:

* `id` auto_increment to avoid race conditions
* `reference_id` The id of a row in _another_ table to which this token refers. In the case of a new user registration/password reset, it's the ID of the user in question. This would work for most tables that have numeric IDs, but things like `txp_page` and `txp_css` (among others) are not able to use them at present because of their lack of numeric index.
* `type` an optional identifier to group the tokens. Txp uses `password_reset` and `account_activation`. This allows you to select by group so you can invalidate (delete) all requests of a particular type that match an ID, without affecting any other requests. Also a useful indicator when searching the table to know what the token relates to.
* `selector` a short, publicly visible hash that can be used to refer to the `reference_id` without revealing the ID itself. Handy as an extra layer in things like password reset requests as the selector can form part of the token so the row can be looked up in `txp_token` using the `selector` first to retrieve the token to match against.
* `token` the actual full cryptographic hash token.
* `expires` when the token expires. A zero-value = never expires. This probably needs updating to fix the null datetime issue in recent MySQL versions.

Does that help?

**Comment by vanmelick** [comment]
After reading the explanation I think 'type' shouldn't be optional, because you have to combine it with reference_id to uniquely identify a row (perhaps even add a unique index for those two rows?).

Should all of these fields have a default value or are there fields that must always be set by the user (like token)? Those that must be set by the user shouldn't have a default value. I'm hoping expires is among those.

P.S. What does ```bin2hex(pack('H*, $string))``` do other than return $string?

**Comment by Bloke** [comment]
You're right regarding the type. It makes sense to enforce it, even though you may elect to use the `selector` as a surrogate for public-facing access to the row without leaking the ID.

The default values, again, yes, makes sense to remove those which are required to be set by the user. But `expires` isn't necessarily mandatory. Certainly for user registration stuff it should be enforced by the application, but you may choose to (ab)use the table for creating unique values that refer to, I dunno, URLs; a kind of routing table like `smd_access_keys` uses. You may wish such URLs never expire until you manually delete them.

Clutching at straws, maybe, but I kinda don't want to limit the usefulness of a token reference/link table by making its use too tightly constrained by how we use it in core today.

Of course, if you can convince me that nobody would (or should!) ever use it for anything other than timed-access security tokens, then we can make the expiry enforced, no problem.

**Comment by Bloke** [comment]
Closed by bd1390b4129ae359d92b14a5fabac61c03865cfc.
