### ISSUE TITLE
Mismatch with published date for copied article

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#614]
Latest 4.6 dev branch.
Copy an article; see the publish date: in article list context, this is the actual publication date which is displayed but in individual article context this is the parent article's date which is displayed.

**Comment by vanmelick** [comment]
There are more differences:
Article list => select article => duplicate: 
* posted set to current time
* modified set to current time
* status same as the original article.

Article edit window => duplicate:
* posted set identical to original article posted time
* modified set identical to original article modified time
* status set to draft.

Are these differences intentional? If not, which of these is the correct behaviour?

**Comment by Bloke** [comment]
@cara-tm Sorry, not sure I follow. If I duplicate an article from the Write panel, the dates stay the same as the original. If I then go and view the article on the front side (in either List or Individual Article context), the date is correct. If I edit either article's Posted date and view it in either context, the date is as I set it. What am I missing?

@vanmelick Yes, intentional(ish), but could probably do with some tweaking. When duplicating an individual article from the Write panel, the Status should definitely become Draft, as the workflow is "I'm basing a new article on this old one" and you won't want it to appear immediately on the site if it's an exact clone. The dates, well, that's open to interpretation. One could argue that the dates should be changed to 'now'. For a blog-style workflow, that may be desirable so your new content (when it's made Live) appears as most recent. But for a corporate-style site where you've manually set the dates so your articles appear in a particular order, you might want the dates to remain the same. Although you can change to now with a single click on the _reset time to now_ checkbox.

From that perspective, the fact that you can choose how the dates are altered:

* one by one: clone from the Write panel, get an exact clone.
* en-masse from the Articles panel: all selected articles get 'now' date) gives flexibility.

But it could be confusing.

In either case, the fact the status flags stay the same when cloning from the Articles panel might be construed as undesirable.

But it goes further than that: does the change of status only affect Live articles? i.e. if Live, drop to Draft in all cases, but if Pending/Hidden, leave alone? And what about Sticky articles? Leave those too? Make them Draft?

I'm not sure of the exact answers. But you're right that we should either standardise both panels, or make them distinct in some way while making it clear what the outcome will be.

Open to discussion and patches on this.

**Comment by vanmelick** [comment]
I can't think of a situation where you'd want to copy a live article and have it go live without changing it, let alone multiple articles all at once. The "duplicate" function from the article edit window makes more sense to me in how it functions. A simple patch could be to just remove it as a multi-edit option.

I'm willing to patch once the discussion has ended.

**Comment by Bloke** [comment]
Agreed. Draft makes more sense to me across the board (at least for articles that are Live). My best guess is it makes sense to make that the default for all clones, regardless of initial status. I mean, you wouldn't have selected the article to clone if you didn't intend to publish it at some point... right?

So that just leaves the decision about the timestamps. I don't mind if they all go "now", all stay the same as their clones, or we come to some logical agreement about which panel does what.

My gut feeling is that the Write panel is correct in its assumptions, though I'm willing to be swayed. But I wonder if we can do more. Compare the _Duplicate_ functionality of the Write panel to that of the ones under Presentation. Let's choose the Forms panel. If you open a form up:

* Without making any changes, hit Duplicate. You get an exact clone of the Form, but with `_copy` appended to its name.
* If you change the Type and hit Duplicate, the new Form is filed under that Type.
* If you change the Name and hit Duplicate, the new Form gets that name. If it clashes with an existing Form, you are forbidden from creating it until the name doesn't clash.

To some extent the Write panel mirrors this. If you change the Category or Section or any of the content fields prior to hitting Duplicate, your new article gets that content. The only exceptions are:

* The article name (Title + URL title) is _always_ appended with the new article ID in parentheses, even if you change the title prior to duplication. Your new name will be used, but it will have the number appended.
* The _reset time to now_ checkbox is ignored. The timestamp is always the same as the original, unless you manually edit it.

The former point I can live with, though it'd be nice -- assuming the article didn't clash with another one -- to _not_ append the ID if possible.

I do think it'd be good to honour the _reset time to now_ checkbox prior to duplication if it's checked. That gives the option to easily keep it the same or change it to 'now'. It already honours any Posted and Expires if you edit them prior to duplication, so why not the reset checkbox too? Perhaps that's an oversight on my part that needs correcting?

As for the Articles panel, I'm not sure what would be deemed 'correct' behaviour for timestamps when making changes to more than one article at once. Suggestions welcome.

**Comment by philwareham** [comment]
Fixed.

**Comment by cara-tm** [comment]
Thanks, Ruud ;)
