### ISSUE TITLE
Write panel: Odd behaviour of the sub-panels in the sidebar on saving (continued)

### ISSUE THREAD

**Issue by bloatware** [textpattern/textpattern#669]
I have only observed it with `div.status`, but other panels could be concerned as well. When saving an article, `replaceWith()` js function replaces `div.status` with `pluggable_ui('article_ui', 'status', 'div.status', $rs)`. Now, if `something` is plugged into `article_ui.status` event, `pluggable_ui()` can generate `something+div.status`, which on save becomes `something+something+div.status`, and so on.

**Comment by bloatware** [comment]
It looks like most of `PARTIAL_VOLATILE` sections are concerned.

**Comment by rwetzlmayr** [comment]
It is odd, nevertheless this behaviour has not changed since 4.5.7. I think it has been so since the introduction of AJAX in the write panel back in 4.2.0.

Below is the output of [wet_test_pluggable_ui](https://github.com/rwetzlmayr/wet_test_pluggable_ui) on 4.6 and 4.5.7, respectively. 

- Lines with a red background are added at the initial page render
- Lines with a pink background appear with the AJAX updates

![wet_test_pluggable_ui-46](https://cloud.githubusercontent.com/assets/357054/14483778/e0899d42-014a-11e6-8af5-f5b41093d316.png)

![wet_test_pluggable_ui-457](https://cloud.githubusercontent.com/assets/357054/14483783/ec68b1f2-014a-11e6-8067-f25437614231.png)

So it looks like plugin authors have delt with this behaviour for the past few years without complaining.

I'm not quite sure what to do about this issue. Do you think there is anything we can fix while keeping at least a modicum of backward compatibility?

**Comment by bloatware** [comment]
Yes, the issue was already present in 4.5.7. I guess, most plugins totally replaced default panels or acted on static sections, so it was never noticed. I can not imagine how this behavior could be useful, so we must fix it, preferably in 4.6. Right now, a wrapper around `pluggable_ui()` should suffice, but imo in future versions AJAX responses should not contain markup at all, only data.

**Comment by bloatware** [comment]
It almost works (on Write tab) replacing
```php
'$("'.$p['selector'].'").replaceWith("'.escape_js($p['html']).'")'
```
with
```php
'$("'.$p['selector'].'").replaceWith($("<div>'.escape_js($p['html']).'</div>").find("'.$p['selector'].'"))'
```
save for recent articles section, but this can be fixed. Looks fragile, however?

**Comment by bloatware** [comment]
Patching and closing it. The fix is not fully backwards compatible, but if nobody complained before, the difference shouldn't appear.

**Comment by bloatware** [comment]
Nice little plugin, btw. Another odd issue: on async calls `article_partial_view_modes()` seems to return only the default html wrapped in `div#view_modes`, and I don't see why.
