### ISSUE TITLE
User account email address validation fails for @localhost addresses

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#678]
STR: in initial setup, add a user account with an email address ending `@localhost`. Validation will fail.

[SafariScreenSnapz001.mp4.zip](https://github.com/textpattern/textpattern/files/233168/SafariScreenSnapz001.mp4.zip)

As an extension to this, localhost/loopback equivalent IP addresses also fail validation. I've raised this before in the Google Code era and I believe it was fixed, but something's crept back in and it's no longer working as it should.

Possible solutions:

* regex the supplied email address (e.g., http://emailregex.com - untested)
* change the behaviour to ensure the domain is correct instead of checking for a syntactically-correct format (e.g., https://github.com/mailcheck/mailcheck)
* send an email to the supplied email address to make sure it's actually working (and avoid the messy regex)

**Comment by rwetzlmayr** [comment]
This issue with `filter_var($address, FILTER_VALIDATE_EMAIL)` has also been covered in [PHP bug 43402](https://bugs.php.net/bug.php?id=43402), open since 2007 and still unresolved.

The discussion there mentions https://github.com/dominicsayers/isemail as a viable solution until PHP addresses these deficiencies.

**Comment by petecooper** [comment]
Thinking about this, I consider it an edge case and a easy workaround is to use an RFC2822-compliant address, so I'll close this.
