### ISSUE TITLE
Inconsistent serialization / deserialization of search options

### ISSUE THREAD

**Issue by rwetzlmayr** [textpattern/textpattern#688]
Steps to reproduce:

1. Click on **Content > Images**.
1. Add at least one JPEG image. Content does not matter. Specify "foo.jpg" as its name.
1. Uncheck "Search all"  in the search widget options.
1. Check "Name" in the search widget options.
1. Enter "foo" as a search term and start to search.
1. Hover over the found image's ID number. The URL looks like so: `...search_method=name&crit=foo`. This is good.
1. Click on **Content > Images** again.
1. Hover over the same image's ID number. The URL looks like so: `...search_method=a%3A1%3A%7Bi%3A0%3Bs%3A4%3A%22name%22%3B%7D`. This is strange.

It seems that search method is saved to preferences in a [serialized format](https://github.com/textpattern/textpattern/blob/f67b8ae8d204dd15ae865c5469edc8524fefe68b/textpattern/vendors/Textpattern/Search/Filter.php#L112) while it is occasionally [read back as a plain string](https://github.com/textpattern/textpattern/blob/f67b8ae8d204dd15ae865c5469edc8524fefe68b/textpattern/vendors/Textpattern/Search/Filter.php#L212). OTOH, [the ctor uses unserialize](https://github.com/textpattern/textpattern/blob/f67b8ae8d204dd15ae865c5469edc8524fefe68b/textpattern/vendors/Textpattern/Search/Filter.php#L112).

Unserializing external input may also pose security risks. Needs investigation. 

@philwareham 52ca13ef53d8e58cff3d96333adfcc4ad77e0505 is the first commit with the relevant code I could find. Do you remember how it came into existence?

**Comment by Bloke** [comment]
My bad. Since the search_method is an array now and we still need to remember it, I had issues where storing it verbatim in the prefs table as it would just break stuff. Figured serialize was "safe" to store (in terms of stringifying it so it's stashable in the database without errors, not necessarily security).

Aside from the inconsistencies in fetching the value from the table, if not serialization, what do you suggest as a secure method of encoding an array for storage? json_encode / json_decode?

**Comment by rwetzlmayr** [comment]
I think that (un)serialize is to be avoided at any measure. There is no safety barrier against a plugin author or our future self introducing a class with a `__destruct` or  `__wakeup`  method and a code path from there to an external input value.

JSON seems like a sensible persistent data format for these simple values.

I think we should refactor the code dealing with preferences and `gps('search_method')` into some methods like `\Textpattern\Search\Filter::getSearchMethod` and `\Textpattern\Search\Filter::setDefaultSearchMethod` respectively to hide these particularities.

**Comment by Bloke** [comment]
Fine by me. If you fancy refactoring the search to do that, be my guest. You'll make a better job of it than I would, but if you're strapped for time I'll look into it. Just let me know.

**Comment by rwetzlmayr** [comment]
@Bloke I resorted to a comma-separated list as we store just array keys. Do you still remember why you "had issues where storing it verbatim in the prefs table as it would just break stuff"?

**Comment by Bloke** [comment]
Nice. A comma-separated list works fine for core and is much safer. Plays havoc with (for example smd_thumbnail) though, because the plugin just constructs the anchor using:

    ... 'page='.$page.a.'search_method='.$search_method.a.'crit='.$crit ...

using the `search_method` value from `gps()`, which triggers 'Array to string conversion' errors. So the `pluggable_ui()` callback (in this instance) will presumably need to either instantiate a `Textpattern\Filter` and build anchors using the method you just introduced, or manually detect if `search_method` is an array and handle it accordingly. Presumably, falling back to a plain string for backwards compatibility is not an option now?

Anyway, the issue I had previous was simply because search_method was sometimes an actual PHP array and I was (stupidly) trying to store it directly in the prefs table. Storing binary data from an internal PHP representation of an array in a text string works sometimes, but more often than not just stored or returned garbage. Hence the fallback on `serialize()` at the time.

**Comment by rwetzlmayr** [comment]
> using the search_method value from gps()

Maybe I'm tonedeaf to the essence of your comment, but my commits have not (intentionally) changed the type of `search_method` in the [POST data from the search widget](https://github.com/textpattern/textpattern/blob/f67b8ae8d204dd15ae865c5469edc8524fefe68b/textpattern/vendors/Textpattern/Search/Filter.php#L260). Did your plugin work before these changes were introduced?

**Comment by Bloke** [comment]
It probably didn't work beforehand. I'll fix the plugin either way. Using comma-separated values is absolutely the right way to go.

**Comment by rwetzlmayr** [comment]
All is calm.
