### ISSUE TITLE
Reset password 4.5.7

### ISSUE THREAD

**Issue by dragondz** [textpattern/textpattern#691]
Hi here is the detail:

1. Click on reset password on admin side
2. Receive email with a reset link, click on the reset link
3. Receive the new password by email
4. Go to the connect page (used the same page for the reset link http://website/textpattern/?kkjk;,kk;
5. try to connect with the new password, fails
6. Receive new password by mail each time i try to connect (4 times for me before i realised that i shouldnt use the login page used to reset the password)

Question: Should a reset link works multiple time?

Cheers

**Comment by Bloke** [comment]
Resetting passwords (and general password management) has changed significantly in 4.6. Reset links are unique each time they are used, and old ones are immediately revoked when a new one is generated. Could you perhaps try 4.6 and see if it works better than 4.5.7?

Either way, if you send a reset link to an email address and click that link in the same browser session as your Txp, you will be logged into Textpattern because the login cookie exists and overrides the reset link. For testing purposes you should open the reset link in an incognito / private browsing session.

**Comment by dragondz** [comment]
Thanks for clarification, it s only to let you know what happen and take action if necessary, but if that has changed on 4.6 it s ok.
