### ISSUE TITLE
Article title formatting in Write > HTML view

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#696]
Background: http://forum.textpattern.com/viewtopic.php?id=47043

STR: draft an article with a title. Body and excerpt are optional. View article via Write > HTML tab. Title is not HTML-formatted, whereas body and excerpt are.

![safariscreensnapz001](https://cloud.githubusercontent.com/assets/226578/15568258/d554d910-2322-11e6-8cb3-fc688bf410d9.png)

UX is somewhat misleading in that respect. Some potential solutions outlined in OP linked above.

**Comment by philwareham** [comment]
Thinking about it, the title content field does not contain any enforced HTML tags (a user would manually create whatever wrapping tags themselves, whereas the body and excerpt do (as they are fully Textile formatted.

So in this regard, it is correct in it's current layout.

**Comment by phiw13** [comment]
But the title field can eventually have characters converted to entities - which you may want to see. Example, type: `I'am` in the title field, which is converted to `I&#039;am`.

(and oddly in the body field, you get `I&#8217;am` - one of the two is wrong, but that is meat for another issue)

(yes, intentional mistake in that snippet!)

**Comment by philwareham** [comment]
@phiw13 Hmmm, good point. I don't know how to convert this to HTML or fix the other issue you mention, so maybe @Bloke or @bloatware can help?

**Comment by petecooper** [comment]
I'm going to close this issue as it's as-designed and the issue @phiw13 mentions is outlined in https://github.com/textpattern/textpattern/issues/697
