### ISSUE TITLE
Section popup shows titles instead of names

### ISSUE THREAD

**Issue by gomedia-adi** [textpattern/textpattern#715]
I notice that the section popup in the Article tab now lists sections by their titles.

Can a preference be made available so that the user gets a choice between name and title?  Or is it expected that a plugin should provide this previous behaviour?

BTW, under certain circumstances the popup becomes a pop-out - see attached.

![adi_git_article_section_popup](https://cloud.githubusercontent.com/assets/13227940/16293292/08c1d3d0-395c-11e6-9178-068d5555a907.png)

**Comment by Bloke** [comment]
I think Gocom changed this default behaviour. He [had a plugin](http://forum.textpattern.com/viewtopic.php?id=27749) to do this so, yeah, I guess his plugin in reverse is the only way to revert the old behaviour at the moment.

I'm not a fan of endless prefs for things like this, but maybe it's acceptable here (there may be a better way). If so, should such a pref apply to cats as well? Or are you happy to have those always show Titles? If not, would you expect a single pref to toggle both cats and sections simultaneously? A pref just for sections? A pair of prefs? No pref for cats at all? Leave everything as-is and stick with Titles throughout?

Not sure if name-vs-title affects anything else in the UI other than the Write panel.

@philwareham Anything you can do to overflow-hide long values in CSS?

**Comment by phiw13** [comment]
Re - preference: I vote for *Leave everything as-is and stick with Titles throughout?*

it is the more logical option: `title` being the user facing (and user friendly) string whereas `name` is for internal use.

re overflowing-out-of-the-window popup: that is the default/expected behaviour of such widgets, nothing can be done about it.

**Comment by bloatware** [comment]
I would leave `Title` too, but also add `name` as html `title` attribute of select options, for more clarity.

**Comment by gomedia-adi** [comment]
Remember that developers are "users" too ... & we work with names not titles.

Anyway, I'll plugin my way around this.  Thanks for looking into it.

**Comment by gomedia-adi** [comment]
> Not sure if name-vs-title affects anything else in the UI other than the Write panel.

There's "Default publishing section" in section tab as well & I don't believe this is pluggable.

**Comment by philwareham** [comment]
I vote to leave everything exactly as it is. Not even title attributes as they are of questionable value (and inaccessible).

**Comment by Bloke** [comment]
> There's "Default publishing section" in section tab as well & I don't believe this is pluggable.

No, it's not. The reason is that it's rendered above the list and used in two places (potentially). Once if there's content / search results, and once if not.

For that reason it's not currently pluggable and needs tinkering with. What would you expect the `$rs` parameter to contain? Presumably an array of all section names => titles?

By all means have a tinker and submit a pull request for this particular part of this issue. I had a quick play the other day but it involved a little more work than I had time available so I stopped. If you don't fancy submitting a request, I can look at it again over the next few days. Failing that, we can defer pluggability for this widget to later.

The remainder of this request has been deemed a non-issue, it seems!

**Comment by gomedia-adi** [comment]
It'll be OK to put on the back burner, thanks ... I think it's important to mention things like this, even if they're shot down in flames ... but I guess the priority is to get 4.6 out & official.
