### ISSUE TITLE
[UX] 4.5.7 Classic to 4.6.0 Hive error message snag

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#766]
Background: I'm a filthy commie that used Classic on 4.5.7, and following the upgrade instructions to replace everything in `/textpattern/` with the new distribution files ends up with the Classic theme components being deleted, as expected. The first login throws this error:

```
Theme classic (classic_theme) failed to load properly from file /var/www/vhosts/example.com/textpattern/admin-themes/classic/classic.php. The default theme will be used as a fallback.
```

And that's it. No login fields. From a UX point of view, this is a workflow hurdle. A refresh will make it go away, but there's no indication that this is required from the error thrown.

STR:

* install 4.5.7
* set Classic admin theme
* upgrade to 4.6.0 per instructions in readme (replace files, drop config.php in)
* attempt login
* splat

Proposal: update the error text string to include a link to the login page OR actually show the login page but have that error at the top of the browser window.

**Comment by Bloke** [comment]
I did wonder about the message not giving any obvious CTA. Not sure if it's possible to link to the admin side as we might not know which panel to link to. And since the theme has effectively "died" I'm not sure what options are open to us. Perhaps a forced page refresh is possible, somehow passing the message forward to show in the flash area. I'll investigate.

Failing that, perhaps adding the phrase 'when you refresh this page" to the end of the message will suffice?

**Comment by petecooper** [comment]
Doesn't need a panel to link to. Following the instructions:

* log out
* replace `/textpattern/*`, drop config in
* attempt login

A link to `/textpattern/index.php` should do the trick. I'll do a short screencast so you can watch the workflow.

**Comment by petecooper** [comment]
Workflow: Textpattern is logged out of 4.5.7 (Classic), files are uploaded, browser is refreshed to show 4.6.0 login dialog, throws error, browser is refreshed to make error go away, 4.6.0 login dialog appears.

Video is work-safe.

[766-classic-to-hive-ux.mp4.zip](https://github.com/textpattern/textpattern/files/469520/766-classic-to-hive-ux.mp4.zip)

**Comment by Bloke** [comment]
Thanks for the vid. You're right that, in this case, a link to index would be sufficient. The only minor snag (and it is very edge case) is that the same error is also thrown if your admin side is corrupted at any other time. Simulate it if you like:

* Switch to Hive Neutral in _Admin->Prefs_.
* Go write an Article.
* Before you hit Publish, go to your server and either delete or rename hiveneutral. Or in some way mangle the .php file inside.
* Hit Publish, Txp will panic and throw the message.

Now, in that case, if the message were to contain a link to the site root and you clicked it, you'd lose the article content. With a forced refresh, at least it would be reposted (uhhhh, in theory, but you'd have to take the step of agreeing to the repost, because of the stupid browser settings these days).

There's one further fly in the ointment. If your default theme becomes mangled (try the above while you're already using Hive, then rename it), Txp will just bork. Nothing it can do.

So I dunno what the best course of action is. Would be nice if it could repost or return you to the place you were going, just in case something breaks while you're taking a regular admin-side action, but I don't know how practical that solution is, nor if it's worth bothering about.

**Comment by petecooper** [comment]
If the whole thing reeks of edge case, let's ignore it. There're more important things that require attention. It's not a _massive_ inconvenience. Leave it open for now and see what the next week or so of upgraders bring in?

**Comment by Bloke** [comment]
Only the panic-while-txp-is-in-use thing is edge case. The chances of people running Classic or any other theme and encountering the message on upgrade are very real, and very likely.

**Comment by phiw13** [comment]
> The chances of people already running Classic or any other theme and encountering the message on upgrade are very real, and very likely.

Indeed, I ran into this 4 times today…

Improving the error message to *at least* mentioning “Please refresh” is something I suggested many month ago. Not sure if adding a link to `text pattern/index.php` will help in all cases, but it can’t hurt.

**Comment by petecooper** [comment]
Another potential workaround/advisory: switch 4.5.7 admin-side to Hive prior to upgrading.

**Comment by Bloke** [comment]
Yes, we could change that in the upgrade instructions too, providing people aren't upgrading from a version prior to the one in which Hive first appeared. And assuming people read the instructions!

We should probably take a multi-pronged approach and change docs / messages wherever we can to cover as many bases as possible. I'll also have a go at auto-refreshing the page.

We don't currently have a "flash message" concept where we can push a messages to the session and have it rendered automatically on the next page refresh. I prefer that approach rather than passing the string around from function to function, because it's more flexible. If the auto-refresh idea works, I might add a FlashMessage class to do it (I've written one before, that I can maybe pilfer and tweak) and use it in just this place for now. Longer term, we can maybe migrate all message functionality to it as we modularise the panel code.

**Comment by Bloke** [comment]
Pending a better method of updating the core in 4.7 (possibly moving to a more targeted Flash Message system, and dropping people on a more sexed-up Diagnostics page after upgrade) I'll close this issue for now.
