### ISSUE TITLE
Investigate Markdown parsing in core alongside Textile

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#770]
It's time to figure out how to ship Markdown parsing in core. Support for Textile appears to be dwindling, and Markdown is top of the pile in text to HTML parsing.

Things to consider:
- Textpattern currently assumes textfilter-ing to be Textile or None
- there are various flavours of Markdown, including CommonMark
- this might save a lot of time/work and appears to be a) maintained and b) appropriately licensed (IANAL): https://github.com/michelf/php-markdown
- Textile should not be removed (the _horror_)
- Comments and articles can both use Textile

**Comment by Bloke** [comment]
Simplest might be to roll wet's plugin in, from his github account. I think it uses parsedown, which is my fave as it's fast. But I don't know the licensing terms of the parser.

**Comment by petecooper** [comment]
Adding for completeness: https://github.com/rwetzlmayr/wet_textfilter_markdown

**Comment by philwareham** [comment]
MIT license is fully compatible with GPLv2.

Parsedown looks very promising - follows the commonmark spec and also supports GitHub's flavour of Markdown.

**Comment by petecooper** [comment]
I haven't figured out the licence on https://github.com/rwetzlmayr/wet_textfilter_markdown -- @rwetzlmayr: are you able to clarify, please?

**Comment by philwareham** [comment]
Where else is Textile used in Textpattern? The pophelps currently are although I'm changing them to pure HTML in the repo gradually.

**Comment by petecooper** [comment]
Comments can use limited Textile.

**Comment by rwetzlmayr** [comment]
My code is GPLed.

**Comment by philwareham** [comment]
If Markdown were to be available right from first install (which we should allow), then the setup article and excerpt would have to be available in both Textile and Markdown formats.

**Comment by tecumsehmaverick** [comment]
Guys

Obviously you guys have the inside track on the vision and development of Textpattern.  FWIW, respectfully, I disagree with rolling Markdown into Textpattern.

Not because of the Textile vs. Markdown debate.   Rather, it is because, despite the popularity of Light-weight markup languages, not everyone wants them or uses them.  Even when people do want them,  there are multiple flavors of Markdown, other languages, WYSIWYG editors, and of course Textile.

While I do think Textpattern has needed to allow more features in the core, I am still a fan of plugins extending functionality in most cases.

Instead, I'd rather see all text filters all handled as plugins, even our beloved Textile.  Not everyone wants to use Textile, not everyone wants Markdown, some have no interest in either. Why clutter the core up?  Why unnecessarily tie the core to other projects to provide non-essential features when their development may languish or cease?

I find this even more compelling as we move to unlimited custom fields.  From the excursions I've made into the world of Symphony CMS (which was influenced by Textpattern to some extent from what I've gathered), they allow each custom field to have one or more text filters assigned to it. I like that. Use what you want, where you want, and no more than you want.

Perhaps CommonMark and Textile, and maybe one WYSIWYG as up-to-date plugins ready for new installs.

Just a fwiw.

**Comment by cmroanirgo** [comment]
As to the *reasoning* for this enhancement: I suggest that @petecooper look at Grav and the gajillion other blogs/cms' that use markdown.

I've been using textile for many years and simply don't understand the fan-boi-isms that relate to Markdown, particularly in the blog-o-sphere. Markdown is *not* a good feature set for a blogging language (it's great however, for readme's and simple documentation exercises, or boring sites). 99% of those projects then end up putting a WYSIWYG editor in front of it, making the whole 'Markdown' format utterly redundant.

In short, I can only agree with @tecumsehmaverick completely, (except for the CommonMark suggestion). 

While I understand that Markdown has it's time and place: if it's ever 'featured' as part of Textpatten, then I would simply say 'adieu' to this project and yet again start the search for a platform that is not WordPress, nor revolving around Markdown nonsense. The fact is, I *chose* Textpattern because of textile *and* because it doesn't subscribe to the Markdown hype.

If you're going to go for this, then make Textpattern truly agnostic and have all markup languages as plugins so that the klingon fan-bois can write their fav' klingon-to-english-to-html fllter, and make any Markdown decisions a by-the-by decision. At least, make it trivial to support the [same set of languages as github](https://github.com/github/markup#markups), via plugins, of course.

2c.

**Comment by philwareham** [comment]
Pushing this to v4.9 as there is already plenty of work assigned for v4.8. Possible decoupling of Textile could be done as part of multi-lingual support since a filly major rework of article handling would already be required for that feature.

**Comment by petecooper** [comment]
Closing this for now - covered by [wet_textfilter_markdown](https://github.com/rwetzlmayr/wet_textfilter_markdown).
