### ISSUE TITLE
Would love to have Ajax throughout the backend

### ISSUE THREAD

**Issue by aleshh** [textpattern/textpattern#799]
I have been just [informed](http://forum.textpattern.com/viewtopic.php?pid=302119) that the Article page uses Ajax, so that on save the edit position in the article isn't lost. This is awesome.

It would be even more awesome if it worked on Pages, Forms, and Styles. Especially in the latter, I for one am frequently making little tweaks and reloading, then having to scroll scroll scroll to find my previous place.

**Comment by Bloke** [comment]
See 2e36a15c72d0c26181ea4f617a2ead9b21bb63c6 for first steps towards AJAX saving other panels. First panel targeted was Stylesheets, since it's conceptually the easiest to handle.

I've refactored the partials code so it's not just confined to the Write panel, which means it's now available to roll out across Pages and Forms too. Please give the Styles panel a play and report back any findings. If it seems fine, I'll press on with the other panels.

**Comment by aleshh** [comment]
I'm launching my new site monday, so the dev site will be available for trying this out!

**Comment by Bloke** [comment]
@aleshh Yep: same as a regular upgrade. Clone the git repo or download the .zip package from GitHub and upload the files (minus the `.git` folder!) to your site as usual.

**Comment by Bloke** [comment]
Should be fixed via https://github.com/textpattern/textpattern/commit/2e36a15c72d0c26181ea4f617a2ead9b21bb63c6, https://github.com/textpattern/textpattern/commit/5aa009cd0bc60a88956e6ec11d0dc5bacc0f0edc and https://github.com/textpattern/textpattern/commit/a5e7f3766e5b4d01e8bce2f54d978df3e8b902f2.
