### ISSUE TITLE
RPC bug in 4.6+

### ISSUE THREAD

**Issue by makss** [textpattern/textpattern#807]
Forum [Report](http://forum.textpattern.com/viewtopic.php?id=47351)

Need Trace initialization to RPC server.  Like that:
file: `rpc/index.php`

```
define('txpinterface', 'xmlrpc');

require_once txpath.'/config.php';
include_once txpath.'/lib/class.trace.php';
$trace = new Trace();
```

**Comment by Bloke** [comment]
Good catch, makss, thanks. We were about to go live with 4.6.2, but we'll wait and investigate this first.

**Comment by bloatware** [comment]
Should be closed by [https://github.com/textpattern/textpattern/commit/48676bfa5c9125c7a594248671203e8578b38e41](https://github.com/textpattern/textpattern/commit/48676bfa5c9125c7a594248671203e8578b38e41), thanks!

**Comment by makss** [comment]
IMHO, It is advisable to use one and the same order of include files. This will simplify the ongoing maintenance of code. Tracing starts immediately after reading `config.php`.

See: index.php, css.php, textpattern/index.php

**Comment by Bloke** [comment]
I like the idea of consistency between `include` file orders, although as we move forward it will (hopefully) become less important when more things move to classes that can be instantiated with the autoloader.

The only thing that makes me nervous this close to release is the fact that RPC is so hit and miss, and I don't really have any concrete way to test if such changes have far-reaching effects on people's ability to us it. e.g. core language files, desktop editors, and so forth.

Can we leave it as it is for now and change the order of things in 4.7.0 as it'll give us a longer time to uncover any issues?

**Comment by makss** [comment]
Yes of course. Other changes can already be done in 4.7

**Comment by bloatware** [comment]
I agree re include order consistency, though, if we have a similar code in four different files, there should be a better way to handle it. @Bloke are checksums already calculated or we can yet reorder includes?

**Comment by Bloke** [comment]
I've done the checksums.

Unfortunately, not all the includes are the same in each file, otherwise we could centralise them somehow. But it would make sense to have whichever ones _do_ appear to be listed in a standard order so we can mitigate any "this can't happen before this function/constant is defined" bugs.

We can investigate this in 4.7 I think. I'd rather not rock the boat now in case there are legacy/functional reasons why the files are loaded in the orders we have them now.

**Comment by bloatware** [comment]
Actually, part of the common code in these .php files is present in [Textpattern/Security/Filter.php](https://github.com/textpattern/textpattern/blob/dev/textpattern/vendors/Textpattern/Security/Filter.php), which seems unused.

**Comment by Bloke** [comment]
Good find. Then we should start using it!

**Comment by bloatware** [comment]
> Then we should start using it!

If I knew how it was meant to be used... still have to discover the benefits of OOP in this case.

**Comment by Bloke** [comment]
Drat, I was hoping you'd understand it ;-)

**Comment by Bloke** [comment]
Well I now know why [/Textpattern/Security/Filter](https://github.com/textpattern/textpattern/blob/dev/textpattern/vendors/Textpattern/Security/Filter.php) is unused. The place we need to use it (as follows) is right at the top of both `index.php` files:

```
$maxUrlLen = get_pref('max_url_len', 1000);
Txp::get('\Textpattern\Security\Filter')->registerGlobals()->setMaxRequestUriLength($maxUrlLen);
```

Unfortunately, at that point, neither `txplib_misc.php` nor `txplib_db.php` are loaded (hence, no DB access, and no `get_pref()`) nor is the autoloader registered, so no access to `Txp::get`.

In order to use it, we'd have to defer its use:

* For the public side, to roughly where `bombShelter()` is called in `textpattern\publish.php`.
* For the admin side, to after the libraries are included (currently around line 98+).

Can we wait that long to unset potentially harmful globals or long URLs injected by malicious scripts? Is this a verifiable/demonstrable attack vector? Or could some stuff be refactored to safely start the autoloader and include the relevant minimal library files earlier -- certainly for the public side?

**Comment by Bloke** [comment]
Anyone anything to add to this? @makss ? @bloatware ? Or can we close it, since it's done and the optimization detailed in my post above that came off the back of the issue, is possibly insecure.

**Comment by makss** [comment]
So far I have no ideas. It would be nice to somehow later revise xmp-rpc and rewrite part of the code.

**Comment by Bloke** [comment]
> It would be nice to somehow later revise xmp-rpc and rewrite part of the code.

+1!

**Comment by philwareham** [comment]
Or dump it entirely and move to a RESTful API or something else modern.

**Comment by Bloke** [comment]
@philwareham On that note, might we consider something like [json-rpc](https://github.com/johnstevenson/jsonrpc-secure)? Could that suit our requirements? It might also help us with #839...

**Comment by philwareham** [comment]
@bloke not really keen on that. We should do something modern for example: https://www.sitepoint.com/best-practices-rest-api-scratch-introduction/

**Comment by Bloke** [comment]
Write our own API? Sure, if that's what we need and it's worthwhile doing, and we take security into consideration (tokens/salts/etc) to prevent replay/man-in-the-middle attacks. They don't address that in the sitepoint article, assuming that just because a connection is made over SSL that it's secure.

[JSON-RPC v2.0 itself](http://www.jsonrpc.org/specification) is of similar era to the secure implementation. Perhaps the reason it's not been revised since 2013 is because a) it's dead, or b) it's so flexible/complete that nobody needs anything else. Looking at the bare implementation in json-rpc-secure, it certainly seems as if "minimal" was one of the design parameters :-)

**Comment by philwareham** [comment]
Another API standard for possible consideration: [GraphQL](https://www.howtographql.com/basics/0-introduction/). Which has [a PHP framework](http://graphql.org/code/#php) available.

**Comment by petecooper** [comment]
Bumping this - is the original issue closed by https://github.com/textpattern/textpattern/issues/807#issuecomment-254815526 ? The sidetrack talk of a potential RPC replacement is valuable, of course, but perhaps warrants another issue or discussion elsewhere.

**Comment by makss** [comment]
Yes, the original question is closed.
