### ISSUE TITLE
A new tag needed

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#844]
Considering the "Section Title" field from the "Edit Section" tab is used into the "Section" list which affects the article in the "Write" tab, we need a new "Meta Title" field above/below the "Description" field into the "Sections" page.

This could allow to website creators a better way for their mastery of their SEO and introduice two kind of writing: short words for their "Section" list and at least 60 characters for their meta titles.

So `<txp:meta_title />` will be a compagnon tag to `<txp:meta_description />` and `<txp:meta_keywords separator="," />`.

**Comment by philwareham** [comment]
Trouble is that this would need 2 tags introduced (the `<txp:meta_title />` and a `<txp:if_title />`tag) which could confuse authors since it would refer to `meta_title` not the `title`, which is required for an article.

It's also 2 more tags to an already massive list of tags.

**Comment by cara-tm** [comment]
Ok. I understand, Phil.
But why did you introduce the meta_description tag without its pairing compagnon?
What solution?
Maybe you could consider to cut very long section title names with ellipses: thus, we could use significant titles and avoid too large input into the "Section" select list within the "Write" page and keep the actual `<txp:page_title />` for descriptive SEO. Perhaps the most simple alternative.

**Comment by cara-tm** [comment]
Note: The answer above has been edited.

**Comment by Bloke** [comment]
> why did you introduce the <txp:meta_description /> tag without its pairing compagnon

Because meta title can already be satisfied from a variety of sources (e.g. txp:page_url, txp:title, txp:category, txp:site_name, etc). Description is harder to fabricate because it often requires truncating if pulled from other sources, such as excerpt.

Plus, there is no direct analogue for landing (section and category) pages for automatically filling in description content. Article content cannot be used outside article context. People used to fall back on generic content for all landing pages (potentially poor SEO) or leave description empty (ditto), or have to fill swathes of txp:variables or forms in order to pull out per-section/category descriptions. It was a mess.

With the txp:meta_description tag, the hacks all go away. It's clear and clean. Meta title on the other hand is usually of a fixed format depending on where you land. e.g.:

* article | section | site
* section | site
* site
* ...

If we were to introduce a new meta title just for Sections, how does that benefit people who automatically construct meta titles for articles? Or for category/author landing pages? It complicates page logic with an extra -- and potentially confusingly-named -- conditional. I can't see how having two titles for a section improves site ranking. Surely matching elements of the meta title with the page title and URL is a stronger SEO signal, and then meta description content augments that for search excerpts?

Sorry, I don't see the benefit of this proposal for the majority of people, unless I've missed the point.

**Comment by philwareham** [comment]
I'm satisfied that this is covered by other tag methods - closing issue.

**Comment by cara-tm** [comment]
Right. 
So, without a specific tag, what we need is a strong example in the documentation, written by Core Devs with speed and efficiency in mind, to solve all the headache (see how many forum threads about it) with our meta titles.
