### ISSUE TITLE
[UI/UX] Split timezone into 2`select` dropdowns instead of 1

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#847]
Admin -> Preferences -> Time zone.

It's currently a 400+ line `select` dropdown, with `optgroup` for geographical regions and `option` entries for each city/area. There's a _lot_ of scrolling/swiping if the server timezone isn't correctly detected.

Proposal: have a two-stage timezone selector. First dropdown is the area (what is currently `optgroup` and the second dropdown is the city/area (that is currently the `option` part), according to the first dropdown value.

**Comment by Bloke** [comment]
Not saying it couldn't/shouldn't be done, but it'd mean:

* Some sort of Javascript to fetch/display the corresponding city selector based on the area.
* Some way of ignoring the area selector on save. At the moment, the pref save routine just loops over everything that's POSTed and sticks it in the DB -- give or take. We'd need another exception rule in there to handle it.

Not insurmountable, but actually slower to input in some ways because it becomes a two-step process. I gave up scrolling that selector a long time ago. Now I just resort to focusing on it and typing the first few letters of the city to jump straight to it.

Can we put this in the "let's think about it" category please?

**Comment by petecooper** [comment]
>Can we put this in the "let's think about it" category please?

Sure. If it's just me, then I'll close it -- no worries at all.

Where keyboards are available, it's a cinch to start typing the first few letters. Tapping and swiping is less clear cut, 'cos there's sometimes no keyboard available. Maybe more of an edge case than I first thought, since once it's set it won't need to be amended unless there's a server move.

I'll close. Thanks for your input, sir.
