### ISSUE TITLE
Rename timezone: Asia/Yangon -> Asia/Rangoon

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#848]
No idea how prolific Textpattern is in Myanmar, but Rangoon doesn't appear to be on the timezone list. GMT+06:30 if that helps.

https://en.wikipedia.org/wiki/ISO_3166-1:MM

**Comment by petecooper** [comment]
OK, solved: `Asia/Yangon` is now officially known in the tz list `Asia/Rangoon` - safe to rename?

**Comment by philwareham** [comment]
Yes please do

**Comment by petecooper** [comment]
I'm stumped; can't find the tz array anywhere. Any ideas?

**Comment by Bloke** [comment]
I think the place you're looking for is the [getTimezones](https://github.com/textpattern/textpattern/blob/dev/textpattern/vendors/Textpattern/Date/Timezone.php#L113) method and specifically PHP's [listIdentifiers](http://php.net/manual/en/datetimezone.listidentifiers.php). If PHP or the server have got it wrong, then we have it wrong in Txp since we iterate over the list given to us by that function. Presumably the list is server or PHP version specific, so results may vary.

**Comment by phiw13** [comment]
@petecooper 

As @Bloke notes, the list comes from the PHP version you’re running. On my localhost / OS X 10.11, PHP 5.5.38, I’ve got `Asia/Rangoon`. Ditto on  a live site hosted at DreamHost (PHP 5.6.24).
