### ISSUE TITLE
ID number into duplicate article URLs

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#851]
The new "avoid duplicate URL" feature for article duplications is excellent and I want to thank you. Thus, IMHO I think we can introduce a new schema in order to tell to Google bots that the ID number isn't part of keywords in permlinks.

Did you see how large websites, often press and medias sites, use a dot or an underscore with a number identifer within URLs?
So I tried a dot and an underscore into our TXP permlinks and both work just fine.
Changing hyphen for an another sign could enhance SEO for our Textpattern websites.

**Comment by philwareham** [comment]
@bloke thoughts on this?

**Comment by Bloke** [comment]
I'm unqualified in all things SEO to comment, sorry.

When duplicating an article, the ID is added in parentheses so it's distinguishable from the original in the Article List table. In terms of the url-title, that means the copy gets dumbed down by our standard sanitisation functions for suitability in the URL.

For people using section/id/title permalinks, this is duplication as the ID appears twice. For those using a different mode, the ID ensures uniqueness so that when you save, you don't get 'duplicate article' warnings in the UI.

If we want to add the ID to the article using a dot or underscore instead of in parentheses, that's fine by me as long as our sanitiser supoprts those characters (from memory, I think it converts everything non-alphanumeric to a hyphen, so it might not work without tweaking). Untested.

Given that adding the ID is just a hack to get round the 'require unique article titles' thing, I would expect most people to remove it and regenerate the url-title prior to publication of the duplicate. If that's not the case, then define what schema we want to employ instead of using using parentheses / hyphens and we'll go from there.

**Comment by cara-tm** [comment]
IMHO, add the ID to the article using an `underscore` at the end of the URL (as used by lot of professional CMSs) in order to distinguish it from keywords is the best choice.
;)

**Comment by philwareham** [comment]
This makes zero benefits for SEO, sorry. In fact using underscores actually makes search engines see the content after the underscore as part of the previous word (whereas hyphens make them treated as two separate words) so that may in adversely degrade your SEO. [See here for an explanation of that](https://moz.com/learn/seo/url).

Best practice is to change the url content of your new article to avoid confusion as to what the content is for both users and search engines.

Either way, urls have very little (if any) impact on page rank. Content is king.

**Comment by cara-tm** [comment]
@Phil

Not so sure for the little impact with URLs.

@Stef

Another idea: Many search engines consider as "blank" words such as "the", "a", "and" so on... into the URLs which are not treated (not relevant key-words). Would it be so difficult and so intensive requests to add a new core feature from the "Preferences" page in order to set a comma separated words (for internationalisation support) which will be atomaticaly removed from the article slug (in a new article creation's context)? This could improve lot the SEO and reduce the lenght of the URLs by default, too. Keeping to writers the posibility to change the slug if needed (as we can currently)

**Comment by stef** [comment]
@cara-tm i think you have miss-highlited some other stef, you might want to fix that to bring it to the attention of the correct stef.

**Comment by philwareham** [comment]
> Not so sure for the little impact with URLs.

What I'm saying is that if a page has good content then the URL structure is largely irrelevant (as long as the search engine can find the page in the first place). If you had two pages of identical content and one had a keyword optimised URL it *may* rank higher then the other in SERPs although it's debatable (this wouldn't happen in reality anyway, since no two pages should be identical content).

**Comment by cara-tm** [comment]
@philwareham: sure!

**Comment by philwareham** [comment]
Closing. This issue can be avoided by using a different URL pattern in preferences or by (recommended) giving your duplicate article a different URL manually in the 'URL-only title'.

**Comment by philwareham** [comment]
Thanks anyway!
