### ISSUE TITLE
UX: managing expectations for Textpattern upgrades from 4.7

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#871]
Scenario: RPC is not available, and a version check fails. The `problem_connecting_rpc_server` gTxt is displayed, and the `textpattern_version_update` pophelp is linked alongside, along with instructions on upgrading.

New pophelp or reuse an existing one? Rough screenshot attached, please note I'm on a new laptop and don't have screen grabbing software with cursors installed yet -- the URL is what's shown when hovering on the pophelp thing (blue arrow for…erm…clarity).

![rpc](https://cloud.githubusercontent.com/assets/226578/21613845/e64fdcb4-d1ce-11e6-8e93-e204be028dc2.png)

**Comment by Bloke** [comment]
This is an interesting one. With reliance on RPC disappearing in 4.7.0, we'll be looking at getting latest available stable version number from (potentially) two places: a text file on textpattern.com, and a file on GitHub. This makes it far less likely that we'll see any such error, unless both services are down or there's no connection to the outside world.

In which case, I wonder if it's worth going a step further now: if the admin side can't connect to an external resource for version checking, so what? Do we need to inform anyone? Chances are that next time their site tries (there's a 24 hour throttle) it'll be up, unless the admin side is in an intranet situation or used for local testing.

Whaddya think? Is there any point complaining if external resources like .com and GitHub aren't available?

**Comment by philwareham** [comment]
No, I don't think we need to complain in this case.

**Comment by petecooper** [comment]
Complain? No. I agree with @philwareham. Inform? Via diagnostics in high mode, possibly.

I'd counter the headline with some form of diagnostics (high or low) that indicated the most recent check for an update, on the main source (.com or GitHub) and secondary source (opposite of main) if main timed out. That's outside the scope of this issue, and a low priority discussion. That provides some kind of feedback to say there a check is taking place, without explicitly mentioning it in diagnostics.

It'd also be rather helpful if some kind of top-level indicator on the nav bar or footer could be set when an update is available. Take the following scenario:

* Textpattern site runs just fine and dandy, thanks
* Update check happens, new version available
* Diagnostics panel never gets checked, because Textpattern site runs just fine and dandy, thanks.

I'm hesitant to push this for discussion because it only came about when RPC went AWOL for a short time, and then came back, because DNS. Shrug.

What would I like? I'm asking too much: diagnostics entry for 'time last checked', and or a status/failure indicator. I know about Textpattern updates because I'm part of the community attached to it, but a large portion of admins won't ever get involved because they're busy and…Textpattern site runs just fine and dandy, thanks.

I'll formulate thoughts and write up elsewhere. I think there's stuff we can accomplish but it's strictly outside the remit of this issue.

**Comment by phiw13** [comment]
> It'd also be rather helpful if some kind of top-level indicator on the nav bar or footer could be set when an update is available. 

This.

An indicator for *every* user, because the admin is busy and the site runs dandily fine and who goes to the Diagnostics panel, really. Any user can then sent a message by pigeon… I once had a forum discussion about this with @vanmelick (he had plans for an extension along that idea? memory is a little fuzzy).

**Comment by Bloke** [comment]
While I like the idea of a permanote (heck, I even almost floated the idea of a permanent notification icon which could popout when clicked indicating that you need to do _something_ such as site update, plugin update, remove setup, visit the damn diagnostics panel since you've not been there for months, etc) there are some barriers:

* The check(s) would need to run on every page -- even if the results were cached, we'd need to centralise the code so any such test was available to all panels.
* Each test adds delay to loading every panel, as it potentially relies on third party sites responding.
* Implementation of an accompanying acknowledgement system. "Yes, I know, remind me later, or not at all".

My current view? Plugin territory. But there may be some way to do it down the road, in which case, it might be something worthy of exploring.

Some notification that a version check was attempted (maybe in high diagnostics only?) would be beneficial though. Good idea, Pete. So while the pre-flight wouldn't complain if a third party site was down, high diagnostics would at least let you know it tried.

**Comment by petecooper** [comment]
> Some notification that a version check was attempted (maybe in high diagnostics only?) would be beneficial though. Good idea, Pete. So while the pre-flight wouldn't complain if a third party site was down, high diagnostics would at least let you know it tried.

This.

**Comment by petecooper** [comment]
Revisiting this after 6 months with fresh eyes. Unless anyone has any objections, I'll close this and reformulate a proposal at a later date after more input and forum discussion.
