### ISSUE TITLE
Consider allowing access to the Edit Image Panel to all users

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#878]
But make it **read only** for users with low-level permissions (groups 4 and 5, role = Staff Writer or Freelancer, others?).

This would allow for removing the “View“ link from the list view, and simplify the UI for a grid display. At the same time, it gives to users with lower level permissions bits easier access to all meta-data.

A simple way: add the `readonly` attribute to all input fields / textareas. The lower level user still has the possibility of copying the information if desired.

Consider also adding a “Cancel” link next to the “Save” button (or should it be “Close” ?) - allowing the user to return to the Image List panel.

For reference & context, see this [conversation](https://github.com/textpattern/textpattern/commit/1e49e68340d7e3ab472ac5b4b4a059c3a068dec5#commitcomment-20634754).

PS - Even without grid display, this change would be useful I think - considering the ambiguity implied in the word “View” for the existing link.

**Comment by Bloke** [comment]
Does cbaf917 address this? Any weird or impossible access combos?

Can anyone break this, including multi-edit deletes for different priv levels and so forth?

**Comment by phiw13** [comment]
First light pass at testing. Narcissus, my lowly staff-writer alter-ego went to the images panel. He could only mess with his own images through the multi-edit widget. He had no problem accessing the edit panel for any image and see the image at larger size, or see and copy the meta-data. Back to the image list, he could upload images and then edit the meta-data for those new images.

**Comment by Bloke** [comment]
So is that a thumbs-up so far? Or do we need to refine the workflow a bit to restrict some stuff?

**Comment by phiw13** [comment]
> So is that a thumbs-up so far?

As far as Narcissus is concerned, yes! But he’s the more gentle one of us. :-)

**Comment by Bloke** [comment]
Okay, thanks. Let's leave this open until Cerberus has given it the green light :-)

**Comment by phiw13** [comment]
Ok, the more evil part of me now went around and tested as various users (using `smd_faux_role`) - while comparing with TXP 4.6.2. I didn’t find any problems so far. For privileged users, nothing has changed in terms of work flow. under privileged users (staff writer, free-lancer), it brings a nicer work flow to the table - they can now view all details and meta-data for all images.

One nitpick though about “Go back“ button. For users without edit permissions, that is perfect. However, for privileged users, the string feels a little out of place. Wouldn’t it be better if it reads “Cancel” – similar to all other Edit panels?

IOW:
👍🏽

**Comment by phiw13** [comment]
PS - first documented use of an emoji by me…

**Comment by Bloke** [comment]
I agonised over that 'Go Back' button. I didn't want to introduce a new string and that was the only string we had available (outside setup, which we can't use in the main code) that resembled the action I wanted.

The reason we have never used 'Cancel' on this panel is because of the destructive nature of the panel. You could open the Edit panel, replace an image with something else, replace the thumbnail with something else, or recreate the thumbnail. The existence of a 'Cancel' button implies that those actions can be undone by clicking the button to return to safety. They can't. The only thing the button will "undo" is any changes to the meta fields that have not yet been saved.

So I figured given the alternatives, that 'Go back' was fairly safe wording.

If we're unsure about this, there's another option: only show that button for under-privileged users so they can back out. But for privileged users, only show 'Save' as we did until very recently. That does mean that if you land on the page, the only way back is to either Save, use the browser back button, or click another menu item.

I'm fine with either keeping 'Go back' for everyone, or ditching it for privileged users. I'll go with whatever seems most logical to anyone who pipes up here.

**Comment by philwareham** [comment]
I’d rather keep our original wording here for privileged users.

**Comment by Bloke** [comment]
What's that then? No 'Go back' button for people who can edit anything?

**Comment by philwareham** [comment]
Actually, it's probably fine, sorry. You're right that users can edit images without pressing 'Save' specifically - so in this case it makes sense.

**Comment by Bloke** [comment]
Cool. Is the styling/HTML okay? I noticed that when I added the button and removed the `txp-save` class from the surrounding paragraph tag (because it's not just a 'save' action any more right?) the buttons shifted to the right instead of being left aligned.

Does that break on smaller screen sizes? Anything we can do about that or does it not matter?

**Comment by philwareham** [comment]
How about bringing the buttons into the panel, like so: http://design-patterns.textpattern.io/mockups/secondary/content-image_edit.html

Kind of feels right since the save only refers to that part of the page anyway (the other parts of page are separate forms).

**Comment by Bloke** [comment]
Hey, I like that! I'll do that today.

**Comment by Bloke** [comment]
Moved buttons into the Details block in commit d028c704.
