### ISSUE TITLE
UX: Admin -> Users for roles with no access to other users

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#899]
Roles with levels 4, 5 and 6 (Staff Writer, Freelancer and Designer in English) have no access to other user accounts, but are presented with Admin -> Users menu in the admin-side.

From a UX point of view, it's not ideal. The result of Admin -> Users is a bit sparse for those roles -- no heading, two buttons.

Two routes in my mind. Either Users should retain the same functionality but be more granularly titled:

* for roles with levels 1, 2 and 3 something like `Users and Account`
* for roles with levels 4, 5 and 6 something like `Account`

_Or…_ split the two tasks into two parts:

* an Admin -> Account menu item for roles 1 through 6
* an additional Admin -> Users menu item for roles 1 through 3 only

[SafariScreenSnapz001.mp4.zip](https://github.com/textpattern/textpattern/files/922383/SafariScreenSnapz001.mp4.zip)

**Comment by Bloke** [comment]
Yeah, an entire screen just to change your password does seem a bit of a waste. I think this is just one of those legacy areas because it was traditionally split into separate steps. What probably makes sense these days is for people to manage their own 'profile' info. Why should admins be the only people able to change a user's name? Role: sure, but name and email address should be available to edit by each user individually, right? And of course, for any user by an admin as it is now.

So, yeah, I kinda like your first proposal: less privileged users should be able to just edit the fields of their own info (minus role, which will be static). In other words, the 'edit' step a Publisher sees, but only for your own info. I'd probably retain the 'change your password' as a separate button/step, but lose the 'change your email address' button because that could be changed as part of the edit step.

**Comment by Bloke** [comment]
@petecooper Have at it. Please try and break this. Think I've caught all corner cases, but be as devious as you can to try and circumvent it (try adding or editing users for unprivileged roles, pass in role data even if you're not publisher or try to alter your own role, etc).

When hacking the URL, the worst you should see is a rogue 'Cancel' button and a 'Change your password' button on the Edit panel when you shouldn't normally see those UI elements. But they do no harm and should not appear out of place under general use.

**Comment by Bloke** [comment]
Gonna close this. Can reopen it if there are functionality issues found during testing.

**Comment by petecooper** [comment]
@Bloke -- thank you heaps for this, apologies for unintended radio silence.
