### ISSUE TITLE
Clear search should also clear search filters checkboxes

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#900]
Currently in 4.7dev when you click the 'Clear search' button, the results list is refreshed without any filters but the filter checkboxes within the search dropdown remain in their previous state. They should be reset back to 'search all'. Otherwise the next time a user searches those filters will be unexpectedly applied, which is bad UX.

**Comment by bloatware** [comment]
I would simply drop this link -- it looks and works poorly.

**Comment by philwareham** [comment]
I find the 'clear serach' link very useful though, so I don't want it removed.

Basically the real issue is that search widget filtering is stored in local storage when it shouldn't be. Sure it's OK to remember search state when staying on the panel, but when you move away to other panels then return you would assume search widget is back in 'search all' state, which it currently isn't. This gives unexpected results next time you search for something.

**Comment by Bloke** [comment]
Hmm, imo we should either store the state of the checkboxes and search criteria or we don't. How does local storage know you've moved away from the current panel vs refreshing the page with different query params? Or closing the browser tab? Or closing the browser entirely? It's open to problems.

I like the fact that the boxes stay checked the way I set them -- in the same way that when I come back to the panel, the sort direction and column are maintained. And the last Form/Page/Stylesheet are now remembered. The beauty is that each person can set the checkboxes to the items they search most frequently and leave it at that.

Having said that, if you haven't visited the panel for a while, it might be nice to (somehow) give a visual indicator that the search isn't a 'full' (all-field) search. i.e. that some boxes are unchecked. Could we add some sort of indicator nearby? Even in the field's placeholder itself, maybe? Or on the dropdpown arrow? Different colour? An asterisk or something to indicate some fields are unchecked? Dunno. With some indicator, it's just two clicks to check all the boxes prior to search.

I also like the 'clear search' functionality. Setting the checkboxes to 'all on' brings about some edge cases:

* It'd need to be present on-screen not only when a search is in force, but also when any checkboxes are unset, even if a search is not being performed.
* In that case, the fact it's labelled 'clear search' is insufficient if you're not performing a search and only clearing checkboxes.

Not quite sure how to factor that in. If I've set my checkboxes up to check three fields, performed a search and found no results, then click 'clear search' and try again (instead of just altering the search term in the box) I might be pretty annoyed that I then have to go back and re-set my three checkboxes. But I can see it from your POV too that 'clearing' the search should reset to a known base state.

I'm really not sure. Don't want to add two UI elements, like 'clear search' and 'search all fields' (for example). I think a visual cue that some filtration is in place -- in the same way that the 'clear' llink appears when a search is being performed -- might be the simplest solution. Just gotta factor it in somehow.

**Comment by philwareham** [comment]
Well OK, that makes sense. The problem for me is that there is no indication that the search is going to be filtered unless you actively go back into the dropdown to see what's checked. I agree we need some visual indiction directly on the panel that a filters are going to be applied at next search.

The colour of the dropdown arrow could be the winning idea here if ti came be done. That would need a classname applied to the widget if someone can code that. Let me try some colour options and get back to you on the visual side of it.

**Comment by philwareham** [comment]
I've committed a patch in the admin themes that will put a subtle blue colour on the search widget dropdown button if a `.filtered` class is present on the form tag. [See mockup here](http://design-patterns.textpattern.io/mockups/content-list.html).

I need a dev to do the class append magic though; basically if the list is currently filtered (i.e. if 'search all' is *not* checked) then the form tag with class `.txp-search` also needs a class of `.filtered`.

**Comment by Bloke** [comment]
Excellent! I'll try and do the necessary class wrangling today.

**Comment by Bloke** [comment]
Then agin, I might defer this to @bloatware :-)

I'm not sure the most efficient place to put the hook. Since the search box uses `txpMultiEditForm()` we could add it to the `lib.checked()` function, but that would be executed for all multi-edit checkboxes, including those alongside regular list content.

We could add a handler directly to `txp_search()` and monitor the 'select_all' checkbox to see if it's checked, but I don't know how to do that for 'passive' changes via other checkboxes.

We could monitor all checkboxes in the search div and check for changes, then test the 'select_all' to see if it's checked, but that enters race conditions with the actual checkbox handler, which makes it unpredictable.

In all the above cases, it doesn't take into account setting the `filtered` class on the form tag based on the localStorage setting on page load. And I can't find the bit of code where those values are read and applied on page load.

Help!

**Comment by bloatware** [comment]
All I know is that the search method is currently stored server-side, if it helps :-) And I'm not sure it should be made browser dependent (by localStorage).

**Comment by bloatware** [comment]
That seems to work [now](https://github.com/textpattern/textpattern/commit/569f6c0db33ba906e742566d54d2cd1f775247c8) (as I understood it), please test.

**Comment by philwareham** [comment]
Tested here and works as intended I think. Nice!

**Comment by Bloke** [comment]
Genius! I'd never have figured that out. Nice optimisations, too.

**Comment by philwareham** [comment]
Closing as this seems to work fine in my tests. Cheers everyone!

**Comment by bloatware** [comment]
Thanks! While working on it, I've noticed that the search combo is blinking on load (some js treatment behind?). We can css hide it before everything is processed, but isn't it better to hide the whole `<main />` block rather than individual elements? To test, append `.not-ready main` selector to `<style />` on line 131 of `txplib_head.php`.

**Comment by philwareham** [comment]
OK, so you are proposing getting rid of:

    <style>
    .not-ready .doc-ready,
    .not-ready table.txp-list,
    .not-ready form.async input[type="submit"],
    .not-ready a.async {
        visibility: hidden;
    }
    </style>

And replacing with:

    <style>
    .not-ready main {
        visibility: hidden;
    }
    </style>

I can't see a problem with doing that in my testing. It's simpler code and avoids all content jumping. Might make the UI slightly slower to render by milliseconds but the elements wouldn't be ready until JS loads anyway so no loss (plus the JS is cached after first page render so again no problem there).

**Comment by bloatware** [comment]
Yes, it's individual content jumping vs page display delay. We can continue targeting individual UI elements as now, but it's easy to forget when something is modified. Dunno...

**Comment by philwareham** [comment]
I'm voting for your method - one rule to rule them all. @bloke do you concur?

**Comment by phiw13** [comment]
> one rule to rule them all

+1

**Comment by Bloke** [comment]
Yep. I'm in.

**Comment by philwareham** [comment]
Done: https://github.com/textpattern/textpattern/commit/d16d2fcc3f26190a7b58437cf54482255e004e71

**Comment by phiw13** [comment]
This has a slightly naughty side effect on the login panel: the name field is not automatically focussed anymore (first tested with clear caches, nuke all cookies e.a, but reproduced on subsequent tests). Previously, both Safari and Firefox would automatically focus the field and offer the auto-complete drop-down with the login credentials (http connection) - or even fill the field (Safari, https://).

Nothing major, the field is one tab press away. Hmm, wonder it that field should use the `autofocus` attribute instead of using some script.

**Comment by bloatware** [comment]
One could replace `visibility: hidden` with `opacity: 0`, though I dunno what are side effects.

**Comment by philwareham** [comment]
@bloatware ah, yes. You are right - we should use `opacity:0`.

**Comment by phiw13** [comment]
> opacity: 0

Yes, that works, both for `http://` and `https://`; in both cases the field remains focussed (and Safari automatically fills in the data in the latter case). I can’t think of any (negative)  side effects, right now.

**Comment by philwareham** [comment]
@bloatware nah, best to keep the UI as quick as possible - fade just gives the impression the UI is slow, I'm not a fan either (it's OK on some websites but not for a web app IMO).

**Comment by philwareham** [comment]
Done anyway: https://github.com/textpattern/textpattern/commit/796d61dff4a4491d2aa9024d71fbb34aa818688c

**Comment by bloatware** [comment]
@philwareham sure, I meant custom themes, if the author wishes so.
