### ISSUE TITLE
checkPrefsIntegrity reset the glz_custom_fields html values

### ISSUE THREAD

**Issue by jpdupont** [textpattern/textpattern#907]
I searched for why **glz_custom_fields** no longer works with the latest versions 4.7 dev.

I discovered that at times the **html value** of the custom field preferences would go back to **custom_set** instead of staying at the value assigned by glz_custom_fields.

After looking without success in the plugin code what does a reset of these values, I realized it happened at **new login**. 

By commenting **checkprefsintegrity** in txp_auth, **no more bug** after a logout / login.

**Comment by Bloke** [comment]
Good sleuthing, thank you for the report. It shouldn't trample on glz_cfs if you've changed your fields to be of a different type. This will be especially important when unlimited CFs hit core eventually, as each custom field might have a different type (although we're going to approach CFs differently then, in a separate table, not in the core textpattern table).

Maybe for now, we shouldn't touch the field type during the prefs integrity check. Or just take a more softly-softly approach with custom_set values. @makss what do you think is best here?

**Comment by makss** [comment]
Can add the `nocheck` field to the` core.prefs` file.
```
    "custom_1_set": {
        "val": "",
        "type": "0",
        "event": "custom",
        "html": "custom_set",
        "position": "1",
        "nocheck": "1"
    },
```
or can more accurately describe the verification rules: `"nocheck":  "type,event,html,position"`.

**Comment by Bloke** [comment]
Hmmm, `nocheck` in the field data is an interesting idea, but I don't particularly care for "magic" values like this. Each item in the JSON file is a 'record' and the fields are supposed to represent DB columns. I know it's unlikely, but what if there's a `nocheck` column added in future, or in someone's plugin and they want to use our integrity API?

The thing is, we don't want to pander to plugins because that opens up a whole host of issues. But in this case, we do need to do something about it, without impacting our ability to rip Custom Fields apart later.

Maybe we could introduce another prefs file? Say, `custom.prefs`, and move the `custom_N_set` entries to that. During install, the arrays in both files are combined so all prefs are created, but during login/logout integrity checking, only `core.prefs` is used? Is that possible? Or is the same integrity check tied to both installation and verification processes?

**Comment by makss** [comment]
> Maybe we could introduce another prefs file? Say, custom.prefs, and move the custom_N_set entries to that. During install, the arrays in both files are combined so all prefs are created, but during login/logout integrity checking, only core.prefs is used?

Can simply exclude `custom.prefs` from checking the preferences. This is half a line of code. ;-)

**Comment by Bloke** [comment]
Neat! Thanks.
