### ISSUE TITLE
Trailing slash at end of section URLs or not?

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#929]
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BRYG9CKDZVS1Y1BSZA1FCQ4D/Trailing%20slash%20at%20end%20of%20section%20URLs)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BRYG9CKDZVS1Y1BSZA1FCQ4D/Trailing%20slash%20at%20end%20of%20section%20URLs/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BRYG9CKDZVS1Y1BSZA1FCQ4D/No%20trailing%20slash%20at%20end%20of%20section%20URLs)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BRYG9CKDZVS1Y1BSZA1FCQ4D/No%20trailing%20slash%20at%20end%20of%20section%20URLs/vote)

**Comment by drmonkeyninja** [comment]
I've voted 'no trailing slash', but which ever is chosen should be consistent throughout the CMS. 

The `.htaccess` file should be updated to include a rule to strip trailing slashes if they are to be gotten rid of to avoid robots seeing 'duplicate' content where it doesn't exist.

**Comment by bloatware** [comment]
The original request [here](https://github.com/textpattern/textpattern/issues/843) fwiw.

**Comment by Bloke** [comment]
Heart says no trailing slash - it's not a real directory, it's a resource, and it looks prettier.

Head says it depends if browsers have to do any double-fetching (like they did in the good ol' days) in order to determine it's not a "directory". Do they still do that?

Ignoring the SEO aspect for a moment, if I visit `example.org/section` does the browser say "Is that a directory? Do I need to list the contents or serve a file? I'd best check" and make a _second_ request to determine which? In that case, specifying the trailing slash is more efficient because we're telling the browser "it's a directory, treat it as such".

Now, does the fact it isn't a real disk-based directory but a pretty URL that references `index.php` make a difference to the number of requests the browser makes to serve the content? I honestly don't know. Never snooped it in that detail. But I read years ago that omitting a slash makes the browser/server do more work.

See [this guy's response](https://stackoverflow.com/a/15908858). Ignore his rambling about making a directory and file the same name, but consider the impact at the request level of a browser. Does it make a difference in terms of raw requests these days? If the answer is yes, go with the most efficient system that creates the fewest requests. If it means adding slashes, then so be it.

**Comment by bloatware** [comment]
Slashing is better for existing *physical* directories: `/rpc` will result in 301 redirect to `/rpc/`. Though this does not concern txp-generated urls (normally, they are just mapped to `index.php`), I would keep the trailing slash for listing pages, for consistency.

**Comment by bloatware** [comment]
Side note: some servers (my local wamp) seem to be configured for automatic file extension resolution. For example, I can access `HISTORY.txt` via `/history`. But `/history/` results in apache (not txp) 404 Not Found, which means I can not access a section named `history` (or `license`, or `package` or any existing file name) in clean mode. I would suggest that we move all unnecessary files from textpattern root to some sub-directory, to reduce the risk of name collisions.

**Comment by cara-tm** [comment]
From Google point of view: https://webmasters.googleblog.com/2010/04/to-slash-or-not-to-slash.html

But, if you access to the Blog page of the MOZ website: https://moz.com/blog

**Comment by bloatware** [comment]
On the other hand [http://api.jquery.com/](http://api.jquery.com/) has all its links slashed.

We could offer a `to-slash-or-not-to-slash` preference, with 301 redirection, but then there could be a redirection problem due to browsers cache if you switch from one mode to the other. So, the choice is

* either a fixed (slashed or not) scheme, with automatic redirection
* or a preference, but leave the duplicate content under users responsibility

**Comment by Bloke** [comment]
The poll is pretty much a dead heat between the two options so far!

With that in mind, instead of a site-wide setting either one way or the other, can we just decide on a sensible halfway implementation? For example, leave trailing slash on tags that result in section landing page URLs (category, author, ...) but remove it from other places that work 'higher up' the URL chain (e.g. site name).

I don't exactly know what the split should be, but if we can err on the side of convention, then everyone knows where they stand. So maybe all we need to do is pick which tags output what type of URL scheme, then just go through and ensure it's consistent in the core and the tag builders.

There may be fallout from people who use tags that have changed functionality to construct URLs by hand, but these should be minimised by judicial selection of a suitable URL handling policy.

Who wants to open up things by makig a stab at defining which types of URL should have them, and which should not? We can go from there and see hwo that maps ontop existing functionality to judge the impact any changes would have.

**Comment by bloatware** [comment]
Then I would suggest that we revert to 4.6 scheme (no slash for individual articles, slash for lists) awaiting a better solution.

**Comment by bloatware** [comment]
Reverted to 4.6, but with a possibility to remove the trailing slash. Just create this tiny public-side plugin:
```
register_callback('abc_no_slash', 'pretext_end');

function abc_no_slash($event, $step) {
    global $prefs;

    $prefs['no_trailing_slash'] = true;
}
```

**Comment by philwareham** [comment]
Legacy code decisions restrict us from solving this more consistently - so happy to close this issue now. Thanks Oleg!

**Comment by bloatware** [comment]
To solve the duplicate content issue, this public-side plugin will try to redirect `../section` links to canonical `../section/`:
```
register_callback('abc_add_slash', 'pretext_end');

function abc_add_slash($event, $step)
{
    global $pretext, $production_status;

    if (txpinterface == 'public' && empty($pretext['id']) && empty($_POST)) {
        $url = parse_url($pretext['request_uri']);

        if ($url['path'] == rtrim($url['path'], '/')) {
            txp_die('',
                $production_status == 'live' ? 301 : 302,
                $url['path'].'/'.($url['query'] ? '?'.$url['query'] : '').
                    (isset($url['fragment']) ? '#' . $url['fragment'] : '')
            );
        }
    }
}
```
Its disadvantage is that two requests will be made when accessing a page via a "wrong" link (though normally on the first access only, thanks to caching).

**Comment by catoblepas25** [comment]
There is a simple way to remove slash at the end of section

in v. 4.6.2 open /textpattern/txplib_misc.php

5401 line


` $url = hu.urlencode($keys['s']).'/';`

Need to change to 
`$url = hu.urlencode($keys['s']).'';`
