### ISSUE TITLE
[Themes Branch] blank Section panel with Safari

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#947]
Safari 11
Default install of the theme branch, access the Sections panel, the content part is not displayed (only navigation + footer are visible)

The inspector tells me that the `body` tag still has the `.not-ready` class…
The console flags the following:

```
[Error] Error: Syntax error, unrecognized expression: select[name=edit_method
	(anonymous function) (jquery.js:2:31697)
```

Which probably refers to this in `textpattern.js`, line 1939:

```
$('select[name=edit_method').change(function() {
        if ($(this).val() === 'changepagestyle') {
            var theSkin = $('#multiedit_skin').val();
            section_theme_hide(theSkin);
        }
```

**Comment by philwareham** [comment]
I'm seeing this behaviour too.

**Comment by phiw13** [comment]
@Bloke - Wow, trivial. Weird that Firefox didn’t throw a hissy fit.

**Comment by Bloke** [comment]
Yeah, I was surprised too. Didn't spot the missing bracket at first because I didn't expect only one browser to complain if there was a syntax error (despite what the message said!) so I was looking to see if all the stuff on the page existed and was referenceable first. Kicked myself when I saw the real reason.
