### ISSUE TITLE
Languages branch and fallback language

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#990]
### Expected behaviour

I think this is how it worked in 4.6 and earlier: but if you used a non-English language in Textpattern and one of the strings had not been translated as yet (an empty Textpack string in that particular language) then it defaulted back to the base English translation of that string (which in 4.7 the base is now 'en').

### Actual behaviour

Currently in languages branch if you are using a non-English language any missing translation strings just show the string name itself - no English translation.

As part of this, I think we need to load English `en` into the database *regardless* of which language a user elects to use. And that `en` needs to be non-removable (protected) in the admin language panel. Since that is the fallback language.

### Steps to reproduce

Select a language with missing translations (such as Bosanski), view any item with missing translations (an example in Bosanski is `tab_languages`). See the raw string name displayed.

**Comment by Bloke** [comment]
We could certainly do that, it's no great hardship to read two files and merge them like I did in setup. In fact, doing so in `load_lang()` might mean we can use that during setup too: less code.

The only historical reasons not to do it have been:

1. You'd have to install two languages or we'd have to alter the load routine to use a mixture of RPC and filesystem content (the bundled `en-gb.txt`).
2. It's damn obvious that a string is missing, which it was hoped might spur translators into supplying untranslated strings.

Now that everything's a file and fully available, you're right that it's more attractive to just default to English for untranslated content rather than raw string keys.

I can do this if everyone thinks it's the right thing to do.

**Comment by Bloke** [comment]
Give 763a811 a go and see.

When installing a language, it now fills in any empty (or missing) strings from the fallback language. No more core untranslated strings in the UI.

**Comment by philwareham** [comment]
I had another realisation on this at around dawn this morning - specifically about RTL languages!

So if we fallback to English strings when in a RTL language - the English is probably going to flow RTL currently, which is wrong. We need to fix that happening (allow bidirectional text).

Basically I need to read this document which outlines the solution: https://www.w3.org/International/articles/inline-bidi-markup/

**Comment by Bloke** [comment]
I did spot that actually. I installed ar-dz. If you go to the Articles panel and search for something you know doesn't exist, you get the following string returned:

`.No results found`

But the string in the `en` textpack is:

`No results found.`

So presumably it's doing some odd punctuation refactoring. Short of storing a direction for each string, I'm not sure how we can fix this. The English strings are installed as if they were attributed to the other language, otherwise the system would think there are 'two' languages installed when there aren't.

**Comment by philwareham** [comment]
Hi Stef,

The solution is in the document I linked to. I just need to decide which is the best route (there are 3 ways of achieving the desired result).

By the way, the fallback to English works great! Makes Textpattern about 100% more useable in languages where not much translation has currently been done.

Leave it with me.

**Comment by Bloke** [comment]
Just skimmed the doc. Can we just output `dir="auto"` on all translated strings somehow? Would that magically fix it?

**Comment by philwareham** [comment]
Hi @bloke. Right - read the doc now. I've put the CSS shim into my admin themes (will copy to core soon).

We also need a bit of logic in the system. I'll try to explain it as best I can...

1. The system is going to need to know the direction of your selected language *and* the direction of the fallback language.
2. If the selected language direction and fallback language are the same direction - do nothing.
3. If the selected language direction and fallback language direct differ, then any time the fallback language is used the [HTML tag `<bdi>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/bdi) needs to wrap the text string.

Can that be achieved? That's actually really semantically good too. It tells the browser this text is isolated from the global text direction of the page.

**Comment by philwareham** [comment]
By the way, `<bdi>` isn't supported in IE/Edge but the CSS shim fixes that. It's semantically better to use HTML5 `<bdi>` instead of HTML4 `<bdo>` (which is just an override whereas `bdi` explictly states to the browser that contained text is isolated form the global page text direciton).

**Comment by Bloke** [comment]
Right, well at the moment that's not possible the way I've done it. Not saying it's impossible, just not the way it currently works.

For speed and brevity - but mostly speed - the textpack wrangling is performed outside the critical path - i.e when you install a language. Because at that point of installation, you're barely going to notice the extra processing required to read and parse two language files and make a single "language" that contains a mixture of actual lang strings and fallback strings, all marked as "the lang you actually installed".

If that process was deferred to the point of use - i.e. when rendering every admin+public side page - you'd sure as hell notice it.

The upshot is that right now, we have _no idea_ which strings in the chosen language are actually in the chosen language and which are fallback. They're all mixed up in the database.

Could we find out? Sure. We could:

* Tag the strings with their language code, but that would show up as two installed languages and require some logic during rendering to merge them.
* Add a new DB column to indicate the direction of each string. So when we build "the language" during installation, it defines the direction of each string based on the value at the top of the file from which the string was taken. More complete, and would allow us to offer the above relativelty easily, but it's a lot of extra table space.
* Defer the decision on what to render, and how, to the point of use. But that would slow things down a lot.
* Be more clever and handle the DB/file interaction differently so we could achieve this.

@makss, @bloatware Any additional thoughts?

**Comment by philwareham** [comment]
Reading further, we could add `dir="auto"` to everywhere a tag is wrapping our `gTxt()` and that will give good enough results. Is that doable?

**Comment by Bloke** [comment]
That's the other option I alluded to, yes. Whenever we call `gtxt()` just get it to output `<bdi>the string</bdi>` all the time. Adds page weight. Is that an issue?

**Comment by philwareham** [comment]
Not really. We shouldn't be using `<bdi>` tags willy-nilly on every text regardless. That tells browsers that each and every one of the text items sits outside the global text direction - would 99% of the time it won't be.

However, as a saviour, we **can** put a `<span dir="auto">` on every text instead. That tells the browser to examine the first character of the following text and later the direction based on that. It doesn't have any rendering performance penalty as far as I can ascertain but it does add page weight.

If possible it would be nice to have the `dir="auto"` on whatever the wrapping tag is but if that is impossible using the `<span>` is an OK compromise IMO.

**Comment by Bloke** [comment]
I think we can do that without much performance penalty. I'll try it out later.

Thinking further, my idea about injecting the wrap tags at installation time won't work. It'll work fine if the directions of the fallback and installed language differ: the fallbacks get wrapped before being inserted into the `txp_lang` table. But if you switch language later, the strings we wrapped and stored in the DB might not require wrapping any more if the direction of the chosen language changes.

The only real solution is to do it at render time. The key will be to do it as fast as possible. I'm sorely tempted to do this:

* on public pages, only extract `public` and `common` strings, as we do now.
* on admin pages, only extract `common` plus the strings matching the page's `event`, plus non-core plugin strings.

That might mean refactoring a few and moving them to correct groups, but will cut down (tremendously) the number of strings in the textarray, which should result in faster admin page render times and a reduced memory footprint.

**Comment by philwareham** [comment]
The `<span dir="auto">` can simply be added onto everything - regardless of chosen language or chosen direction. You don't need to inject them at installation time. Since it has no semantic meaning - it simply tells the browser that it should analyse each text slug and choose it's direction based on whether it's Latin, Farsi, whatever.

I'm up for making admin panels only load the strings from it's panel plus common/public though. I know Oleg thought the current 'load everything' approach was bad.

**Comment by Bloke** [comment]
Yes it is poor loading all strings. But at the point that it loads the languages, it doesn't know which panel we're on. So it would require some refactoring to extract essential strings first (so it could do preliminary stuff), then the rest later. Another day.

As for adding `<span dir="auto">`, well that causes chaos! We use `gTxt()` strings inside other attributes such as aria labels so the whole page just blows up with unescaped quotes.

Back to the drawing board...

**Comment by philwareham** [comment]
Hi Stef, more thoughts. We only need to provide these spans when the language is RTL. So I’m thinking we conditionally add the span to certain Textpattern functions themselves. Not the gTxt function directly? I’d rather not have it on LTR languages as it is redundant for that.

**Comment by Bloke** [comment]
True. The question still remains how do we know which strings to apply it to?

We ned some trigger at the point the string is rendered that indicates it's to be treated differently. The only place we know that is when we read it from the database or file system. By the time it's loaded into `$textarray` (from which `gTxt()` gets its info) very early in the page load cycle, it only has two components: the key and the string to render. No other information is known about it. No direction, no language, no nothing. Hmmmm.

**Comment by Bloke** [comment]
Two arrays is the easiest way to go - one for the desired language and one for the fallbacks. But that ease of use comes at the price of loading up to nearly 1200 additional strings into memory that we might never use. So I'm reluctant to go that route.

**Comment by philwareham** [comment]
Surely the system knows when it’s in RTL mode doesn’t it? Can spans be put onto thing like function inputLabel and other functions when in that mode?

**Comment by Bloke** [comment]
The system only knows the mode because we assume that _all_ strings are in that language. Now we're mixing and matching strings - some in target language, some in fallback language - that assumption breaks down.

**Comment by Bloke** [comment]
And yes we could do it at the (low) tag level, but that's a lot of duplicate code every time a string is used. I'm trying to solve this at the language level so we present the system with a unified view of what strings we have available and which language (and/or direction) each is in. Then everything else remains pretty much the same and our output routine just needs to interpret the additional info to know whether it needs to render additional wraps.

**Comment by philwareham** [comment]
Ah I see now. Yes I guess that would be the most desirable outcome. Good luck! This is indeed a puzzler!

**Comment by Bloke** [comment]
Dammit, this is not working well enough. I got it limping along and it does it right in most places. But it totally falls apart when the strings are used in links. I think this is because they're run through htmlspeciachars. So in things like the `<title>` attribute you see:

```
<title>&#60;span dir=auto&#62;Languages&#60;/span&#62; - My site &#124; Textpattern CMS</title>
```

Yuk! You see that in other places too like the list options dropdown:

```
<span dir=auto>List options</span>
```
Hmmm. Not sure how to fix that, short of going through and ensuring that all those strings are added as 'raw' strings. That might have other implications I'm not sure yet.

**Comment by Bloke** [comment]
Further to my above comment, how should we handle tags in articles? Install an RTL language, go to an article and put in some tags like a figure/image? Or add some `<txp:php>` and put a bit of code in. Weird... it moves dollar signs to the right and cuts off other characters.

**Comment by philwareham** [comment]
Maybe we just do what we can. Our RTL support is all much better now than it's ever been - so maybe that's good enough.

Don't really want to saddle you with unsolvable issues.

**Comment by Bloke** [comment]
![rtl-notquite](https://user-images.githubusercontent.com/21252/32692052-31583a78-c709-11e7-8640-cb1a2de36b8d.png)

Just not sure what to do with something like the attached image. Can't really leave it this way...

**Comment by philwareham** [comment]
Maybe we just forget the dir=auto stuff. The browser and CSS does an ok job of handling rendering. It’s s nice to have but I can live without it.

**Comment by phiw13** [comment]
One place where it would be nice to add the `[dir=auto]` attribute is on the  languages panel.

Webkit and Blink (all platforms) based browsers put the brackets “(” and “)” in the wrong place when the page uses a RTL lang. Firefox and Edge 16 / Win 10 latest do it correctly.

Take a look at the page with the language branch, then compare it [my mockup](https://dev.l-c-n.com/txp/txp-admin-language-RTL.html)- all tiles and the first of the two select widgets have been changed: `<strong dir="auto">` and `<option dir="auto" />`.

Oh, and BTW - please check this: https://validator.w3.org/nu/?doc=https%3A%2F%2Fdev.l-c-n.com%2Ftxp%2Ftxp-admin-language-RTL.html

(the source code is straight copied from the Textpattern generated one).

This: `<span class="txp-button" disabled="disabled">` is invalid HTML - you probably want the `.disabled` class.

**Comment by Bloke** [comment]
Thanks, fixed in 5f85439.

I've abandoned the idea of adding `dir="auto"` throughout at the language level. Way too tricky to implement and does more harm than good in a lot of cases. Maybe when we visit multi-lingual content capabilities overall we can think about then.

For now I'm happy for this branch to be merged to dev if everyone else is.

**Comment by philwareham** [comment]
Yay! Do it! 😀

**Comment by phiw13** [comment]
> Thanks, fixed

Nice!

> or now I'm happy for this branch to be merged to dev if everyone else is.

Go, go!
